"""Buyer Project models — AI Project Forge.

A BuyerProject groups line items generated by AI analysis.
Confirmed line items become ProcurementRequests in the commerce flow.
"""
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base_model import Base, TimestampMixin, UUIDMixin


class BuyerProject(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_projects"

    buyer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    project_type: Mapped[str] = mapped_column(String(50), default="GENERAL", nullable=False)
    status: Mapped[str] = mapped_column(String(50), default="DRAFT", nullable=False, index=True)
    country: Mapped[str | None] = mapped_column(String(100))
    city: Mapped[str | None] = mapped_column(String(100))
    lat: Mapped[float | None] = mapped_column(Float)
    lng: Mapped[float | None] = mapped_column(Float)
    area_value: Mapped[float | None] = mapped_column(Float)
    area_unit: Mapped[str | None] = mapped_column(String(50))
    scale_json: Mapped[dict | None] = mapped_column(JSONB)
    budget_min: Mapped[int | None] = mapped_column(Integer)
    budget_max: Mapped[int | None] = mapped_column(Integer)
    currency: Mapped[str] = mapped_column(String(10), default="EUR", nullable=False)
    quality_preference: Mapped[str] = mapped_column(String(20), default="NOT_SURE", nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    ai_summary: Mapped[str | None] = mapped_column(Text)
    missing_questions_json: Mapped[list | None] = mapped_column(JSONB)
    assumptions_json: Mapped[list | None] = mapped_column(JSONB)
    risk_notes_json: Mapped[list | None] = mapped_column(JSONB)
    acceptance_criteria_json: Mapped[list | None] = mapped_column(JSONB)
    estimated_budget_json: Mapped[dict | None] = mapped_column(JSONB)


class ProjectFile(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_files"

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    url: Mapped[str] = mapped_column(String(1000), nullable=False)
    file_name: Mapped[str] = mapped_column(String(500), nullable=False)
    content_type: Mapped[str] = mapped_column(String(200), nullable=False)
    file_size: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    extracted_text: Mapped[str | None] = mapped_column(Text)
    vision_summary: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(32), default="UPLOADED", nullable=False)
    error_message: Mapped[str | None] = mapped_column(Text)


class ProjectAIRun(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_ai_runs"

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    provider: Mapped[str | None] = mapped_column(String(50))
    model: Mapped[str | None] = mapped_column(String(200))
    prompt_version: Mapped[str | None] = mapped_column(String(50))
    status: Mapped[str] = mapped_column(String(32), default="PENDING", nullable=False, index=True)
    input_snapshot_json: Mapped[dict | None] = mapped_column(JSONB)
    raw_output: Mapped[str | None] = mapped_column(Text)
    structured_output_json: Mapped[dict | None] = mapped_column(JSONB)
    token_usage_json: Mapped[dict | None] = mapped_column(JSONB)
    estimated_cost: Mapped[float | None] = mapped_column(Float)
    error_message: Mapped[str | None] = mapped_column(Text)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class ProjectLineItem(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_line_items"

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    ai_run_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    category_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    procurement_request_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    name: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    specs_json: Mapped[dict | None] = mapped_column(JSONB)
    qty: Mapped[float] = mapped_column(Float, default=1, nullable=False)
    unit: Mapped[str] = mapped_column(String(50), default="pcs", nullable=False)
    quality_tier: Mapped[str] = mapped_column(String(20), default="MID_RANGE", nullable=False)
    estimated_unit_price: Mapped[float | None] = mapped_column(Float)
    estimated_total_price: Mapped[float | None] = mapped_column(Float)
    currency: Mapped[str] = mapped_column(String(10), default="EUR", nullable=False)
    confidence: Mapped[float | None] = mapped_column(Float)
    sourcing_notes: Mapped[str | None] = mapped_column(Text)
    price_tiers_json: Mapped[dict | None] = mapped_column(JSONB)
    category_hint: Mapped[str | None] = mapped_column(String(200))
    include_in_estimate: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    source: Mapped[str] = mapped_column(String(10), default="AI", nullable=False)
    status: Mapped[str] = mapped_column(String(32), default="DRAFT", nullable=False, index=True)


class ProjectMessage(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_messages"

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String(20), default="USER", nullable=False)
    workflow_node: Mapped[str | None] = mapped_column(String(50))
    content: Mapped[str] = mapped_column(Text, nullable=False)
    file_ids_json: Mapped[list | None] = mapped_column(JSONB)
    structured_delta_json: Mapped[dict | None] = mapped_column(JSONB)


class ProjectMetricTemplate(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_metric_templates"
    __table_args__ = (
        UniqueConstraint("project_type", "key", name="uq_buyer_project_metric_template_scope"),
    )

    project_type: Mapped[str] = mapped_column(String(50), default="GENERAL", nullable=False, index=True)
    key: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    label: Mapped[str] = mapped_column(String(200), nullable=False)
    data_type: Mapped[str] = mapped_column(String(50), default="text", nullable=False)
    unit_options_json: Mapped[list | None] = mapped_column(JSONB)
    required: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    prompt: Mapped[str | None] = mapped_column(Text)
    active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False, index=True)


class ProjectMetricValue(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_metric_values"
    __table_args__ = (
        UniqueConstraint("project_id", "key", name="uq_buyer_project_metric_value_key"),
    )

    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    template_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)
    key: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    label: Mapped[str | None] = mapped_column(String(200))
    value_json: Mapped[dict | None] = mapped_column(JSONB)
    source: Mapped[str] = mapped_column(String(20), default="USER", nullable=False)
    confidence: Mapped[float | None] = mapped_column(Float)


class ProjectPriceSnapshot(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_price_snapshots"

    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    line_item_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    currency: Mapped[str] = mapped_column(String(10), default="EUR", nullable=False)
    sample_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    min_unit_price: Mapped[float | None] = mapped_column(Float)
    avg_unit_price: Mapped[float | None] = mapped_column(Float)
    median_unit_price: Mapped[float | None] = mapped_column(Float)
    p20_unit_price: Mapped[float | None] = mapped_column(Float)
    p80_unit_price: Mapped[float | None] = mapped_column(Float)
    price_tiers_json: Mapped[dict | None] = mapped_column(JSONB)
    samples_json: Mapped[list | None] = mapped_column(JSONB)
    source_summary: Mapped[str | None] = mapped_column(Text)


class ProjectReport(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_reports"

    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    current_version_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)
    frozen_version_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)


class ProjectReportVersion(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_report_versions"
    __table_args__ = (
        UniqueConstraint("report_id", "version_number", name="uq_buyer_project_report_version_number"),
    )

    report_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    version_number: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    status: Mapped[str] = mapped_column(String(32), default="DRAFT", nullable=False, index=True)
    source: Mapped[str] = mapped_column(String(50), default="SYSTEM", nullable=False)
    title: Mapped[str | None] = mapped_column(String(500))
    summary_json: Mapped[dict | None] = mapped_column(JSONB)
    totals_json: Mapped[dict | None] = mapped_column(JSONB)
    created_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)


class ProjectReportColumn(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_report_columns"
    __table_args__ = (
        UniqueConstraint("report_version_id", "key", name="uq_buyer_project_report_column_key"),
    )

    report_version_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    key: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    label: Mapped[str] = mapped_column(String(200), nullable=False)
    data_type: Mapped[str] = mapped_column(String(50), default="text", nullable=False)
    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    editable: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    system: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)


class ProjectReportRow(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_report_rows"

    report_version_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    line_item_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)
    category_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)
    name: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    specs_json: Mapped[dict | None] = mapped_column(JSONB)
    qty: Mapped[float] = mapped_column(Float, default=1, nullable=False)
    unit: Mapped[str] = mapped_column(String(50), default="pcs", nullable=False)
    currency: Mapped[str] = mapped_column(String(10), default="EUR", nullable=False)
    quality_tier: Mapped[str] = mapped_column(String(20), default="MID_RANGE", nullable=False)
    selected_tier: Mapped[str] = mapped_column(String(20), default="MID_RANGE", nullable=False)
    include_in_total: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    selected_for_purchase: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    price_tiers_json: Mapped[dict | None] = mapped_column(JSONB)
    custom_values_json: Mapped[dict | None] = mapped_column(JSONB)
    match_status: Mapped[str] = mapped_column(String(50), default="UNMATCHED", nullable=False)
    samples_json: Mapped[list | None] = mapped_column(JSONB)
    price_source: Mapped[str] = mapped_column(String(50), default="AI_ESTIMATE", nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)
    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)


class ProjectReportChangeLog(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "buyer_project_report_change_logs"

    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    report_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False, index=True)
    version_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)
    actor_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)
    change_type: Mapped[str] = mapped_column(String(50), default="MANUAL_EDIT", nullable=False)
    status: Mapped[str] = mapped_column(String(32), default="PENDING", nullable=False, index=True)
    user_message: Mapped[str | None] = mapped_column(Text)
    patch_json: Mapped[dict | None] = mapped_column(JSONB)
    before_json: Mapped[dict | None] = mapped_column(JSONB)
    after_json: Mapped[dict | None] = mapped_column(JSONB)
    error_message: Mapped[str | None] = mapped_column(Text)
    applied_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
