export function useDemoCatalog() {
  const demoSupplyPartners = [
    { name: 'Huawei Digital Power', category: 'Solar inverter, storage, smart energy' },
    { name: 'Sungrow', category: 'PV inverter, battery storage, EMS' },
    { name: 'LONGi', category: 'Solar modules and PV ecosystem' },
    { name: 'Xiaomi Ecosystem', category: 'Smart home, sensors, appliances, robotics' },
    { name: 'Hikvision / Dahua class', category: 'CCTV, NVR, video AI, access control' },
    { name: 'Tuya / Matter ecosystem', category: 'IoT modules, gateways, smart devices' },
    { name: 'BYD / CATL class', category: 'Battery, storage, EV energy ecosystem' },
    { name: 'China Tier-1 OEM/ODM', category: 'Panels, gateways, meters, edge AI boxes' },
  ]

  const demoCategories = [
    { id: 'knx-devices', name: 'KNX Devices' },
    { id: 'gateways', name: 'Gateways / Protocol Bridges' },
    { id: 'sensors', name: 'Sensors & Environment' },
    { id: 'smart-panels', name: 'Smart Panels & Scene Control' },
    { id: 'cctv', name: 'CCTV & Video AI' },
    { id: 'access-control', name: 'Access Control' },
    { id: 'network', name: 'Network & Edge AI' },
    { id: 'energy', name: 'Energy Meters / Solar / EV' },
    { id: 'factory-automation', name: 'Factory Automation / Machines' },
    { id: 'robotics', name: 'Robotics & Mobile Equipment' },
    { id: 'service-packages', name: 'Lifecycle Service Packages' },
  ]

  const demoSolutions = [
    {
      id: 'smart-villa-retrofit',
      slug: 'smart-villa-retrofit',
      title: 'Smart Villa / Future Home AI Brain',
      description: 'A staged villa solution covering KNX or Home Assistant control, identity access, lighting, HVAC, energy, EV charging, local AI, and robot-ready expansion.',
      target_scenarios_json: ['Villa', 'Apartment', 'L3-L5', 'Local AI'],
      pain_points_json: ['Disconnected smart devices', 'No long-term maintenance plan', 'Privacy concerns for cloud-only systems'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'L1-L2 retrofit, core lighting, sensors, CCTV, remote access.', starting_from: 3500 },
        standard: { label: 'Standard Plan', description: 'L2-L3 scenes, energy monitoring, HVAC coordination, support plan.', starting_from: 9800 },
        premium: { label: 'Premium AI Plan', description: 'L4-L5 local AI box, identity access, advanced automation.', starting_from: 22000 },
        future: { label: 'Future Autonomous', description: 'Robot-ready architecture and custom engineering review.' },
      },
      delivery_flow_json: ['AI assessment', 'Phase-1 proposal', 'Site survey', 'BOM review', 'Install & commission', 'Lifecycle support'],
    },
    {
      id: 'smart-hotel-room-control',
      slug: 'smart-hotel',
      title: 'Smart Hotel / Serviced Apartment',
      description: 'Guest room control, access permissions, housekeeping status, CCTV public area security, energy saving, and remote maintenance for hotels and serviced apartments.',
      target_scenarios_json: ['Hotel', 'Serviced Apartment', 'Energy Saving', 'Access Control'],
      pain_points_json: ['High room energy cost', 'Manual room status workflow', 'Fragmented lock, HVAC, and lighting systems'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'Room access, basic lighting and AC scenes.', starting_from: 6000 },
        standard: { label: 'Standard Plan', description: 'Room status, energy reporting, CCTV and maintenance flow.', starting_from: 18000 },
        premium: { label: 'Premium AI Plan', description: 'AI maintenance summary, occupancy-driven optimization.', starting_from: 42000 },
        future: { label: 'Future Autonomous', description: 'Robot delivery and autonomous facility roadmap.' },
      },
      delivery_flow_json: ['Room sample design', 'Pilot room', 'Supplier confirmation', 'Batch rollout', 'Remote support'],
    },
    {
      id: 'school-campus-brain',
      slug: 'school-campus-brain',
      title: 'AI School Campus Brain',
      description: 'A campus control layer for classroom environment, visitor safety, CCTV, network status, solar monitoring, maintenance tasks, and AI operations summaries.',
      target_scenarios_json: ['School', 'Campus', 'Safety', 'Energy'],
      pain_points_json: ['No unified facility overview', 'Hard to track classroom comfort and energy waste', 'Manual maintenance reporting'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'CCTV, network, and basic classroom sensors.', starting_from: 12000 },
        standard: { label: 'Standard Plan', description: 'Energy reports, access zones, maintenance dashboard.', starting_from: 36000 },
        premium: { label: 'Premium AI Plan', description: 'AI safety analytics and facility assistant.', starting_from: 78000 },
        future: { label: 'Future Autonomous', description: 'Predictive maintenance and patrol robot readiness.' },
      },
      delivery_flow_json: ['Campus assessment', 'Zone design', 'Pilot building', 'Admin training', 'Lifecycle support'],
    },
    {
      id: 'apartment-property-brain',
      slug: 'apartment-property-brain',
      title: 'Smart Apartment / Property Brain',
      description: 'Access control, common area lighting, elevator lobby CCTV, parking, metering, tenant service requests, and property energy reporting.',
      target_scenarios_json: ['Apartment', 'Property', 'Parking', 'Metering'],
      pain_points_json: ['Public area energy waste', 'Visitor and package access issues', 'Weak maintenance traceability'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'Common area CCTV, access, and basic lighting.', starting_from: 9000 },
        standard: { label: 'Standard Plan', description: 'Metering, parking, property report, maintenance workflow.', starting_from: 28000 },
        premium: { label: 'Premium AI Plan', description: 'AI anomaly alerts and tenant experience upgrades.', starting_from: 65000 },
        future: { label: 'Future Autonomous', description: 'Autonomous facility patrol and predictive repair.' },
      },
      delivery_flow_json: ['Building survey', 'Public area plan', 'Access policy', 'Installation', 'Monthly reports'],
    },
    {
      id: 'office-facility-brain',
      slug: 'office-facility-brain',
      title: 'Enterprise Office AI Facility Brain',
      description: 'Meeting room automation, visitor management, employee access, occupancy-aware HVAC, network monitoring, and AI facility operations reporting.',
      target_scenarios_json: ['Office', 'Enterprise', 'Meetings', 'Facility'],
      pain_points_json: ['Meeting rooms waste power', 'Visitor access is manual', 'IT and facility data are separated'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'Access, CCTV, network monitoring, basic room scenes.', starting_from: 11000 },
        standard: { label: 'Standard Plan', description: 'Occupancy, meeting room automation, energy dashboard.', starting_from: 34000 },
        premium: { label: 'Premium AI Plan', description: 'AI daily facility summary and local AI assistant.', starting_from: 72000 },
        future: { label: 'Future Autonomous', description: 'Robot-ready service routes and predictive facility control.' },
      },
      delivery_flow_json: ['Workflow mapping', 'Zone design', 'Pilot floor', 'Rollout', 'SLA support'],
    },
    {
      id: 'solar-energy-monitoring',
      slug: 'solar-energy-monitoring',
      title: 'Solar + Energy + EV Optimization',
      description: 'A visual energy layer for solar generation, battery SOC, inverter health, EV charging, tariffs, key loads, alarms, and monthly AI energy reports.',
      target_scenarios_json: ['Solar', 'Battery', 'EV', 'Energy Report'],
      pain_points_json: ['No unified energy view', 'EV charging not coordinated with solar', 'Inverter alarms are missed'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'Solar and meter monitoring dashboard.', starting_from: 4500 },
        standard: { label: 'Standard Plan', description: 'Battery, EV, tariffs, alerts, monthly reports.', starting_from: 14500 },
        premium: { label: 'Premium AI Plan', description: 'AI optimization and load priority logic.', starting_from: 32000 },
        future: { label: 'Future Autonomous', description: 'Autonomous energy dispatch requires engineering review.' },
      },
      delivery_flow_json: ['Energy audit', 'Meter integration', 'Dashboard', 'Alert rules', 'Monthly optimization'],
    },
    {
      id: 'cctv-access-control',
      slug: 'cctv-access-control',
      title: 'CCTV & Access Control Upgrade',
      description: 'Service-ready CCTV, NVR, PoE network, access control, smart locks, visitor QR, license plate recognition, and maintenance response.',
      target_scenarios_json: ['CCTV', 'Access', 'Retail', 'Office', 'Apartment'],
      pain_points_json: ['Unreliable remote access', 'No maintenance record', 'Cameras and access systems do not share events'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'CCTV, NVR, PoE, basic remote view.', starting_from: 2500 },
        standard: { label: 'Standard Plan', description: 'Access control, visitor QR, maintenance plan.', starting_from: 8500 },
        premium: { label: 'Premium AI Plan', description: 'Video AI, face or plate recognition, analytics.', starting_from: 18000 },
        future: { label: 'Future Autonomous', description: 'Patrol robot and autonomous security response roadmap.' },
      },
      delivery_flow_json: ['Security survey', 'Camera plan', 'Network check', 'Install', 'Remote maintenance'],
    },
    {
      id: 'knx-lighting-automation',
      slug: 'knx-lighting',
      title: 'KNX Lighting & Scene Automation',
      description: 'KNX-based lighting, scene panels, DALI gateways, sensors, IP routing, documentation, commissioning, and future AI-ready architecture.',
      target_scenarios_json: ['KNX', 'Lighting', 'DALI', 'New Renovation'],
      pain_points_json: ['Smart devices are not project-grade', 'No ETS documentation', 'Hard to maintain after handover'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'Core KNX lighting and simple scenes.', starting_from: 7000 },
        standard: { label: 'Standard Plan', description: 'DALI, sensors, HVAC interfaces, documentation.', starting_from: 24000 },
        premium: { label: 'Premium AI Plan', description: 'Energy analytics and AI-assisted scene optimization.', starting_from: 52000 },
        future: { label: 'Future Autonomous', description: 'Local AI building brain and predictive controls.' },
      },
      delivery_flow_json: ['ETS design', 'Panel schedule', 'Device supply', 'Commissioning', 'Documentation'],
    },
    {
      id: 'factory-automation-energy',
      slug: 'factory-automation-energy',
      title: 'Factory / Industrial Automation & Energy Brain',
      description: 'Factory-focused integration for production machines, PLC or gateway data, compressed air, HVAC, power meters, solar, alarms, maintenance, and robot-ready workflows.',
      target_scenarios_json: ['Factory', 'Warehouse', 'Machines', 'Energy', 'OT / IT'],
      pain_points_json: ['Machine energy use is invisible', 'Alarms are siloed', 'Maintenance depends on manual inspection'],
      budget_tiers_json: {
        budget: { label: 'Budget Plan', description: 'Metering, CCTV, network, basic machine status.', starting_from: 15000 },
        standard: { label: 'Standard Plan', description: 'PLC gateways, energy dashboard, alarms, maintenance tasks.', starting_from: 48000 },
        premium: { label: 'Premium AI Plan', description: 'AI anomaly detection, production-energy correlation, edge AI box.', starting_from: 98000 },
        future: { label: 'Future Autonomous', description: 'AGV/AMR, predictive maintenance, autonomous energy dispatch.' },
      },
      delivery_flow_json: ['OT/IT survey', 'Machine protocol audit', 'Gateway plan', 'Pilot line', 'Factory dashboard', 'Lifecycle support'],
    },
    ...['kitchenguard|KitchenGuard — Commercial Kitchen Safety Monitoring|Gas, CO, water-leak and temperature safety with automatic cut-off, alarm escalation, annual inspection certificates and AMC.|Hotel kitchens,Restaurant chains,Central kitchens',
        'aquaguard|AquaGuard — Water & Effluent Compliance Monitoring|pH, conductivity, turbidity and COD monitoring with environmental compliance reports, calibration and probe replacement (partner-led).|Factory effluent,Food & beverage,Hotel pools',
        'energyguard|EnergyGuard — Solar, Storage & Energy Monitoring|Solar, battery, EV and load monitoring with peak-tariff optimization, battery-health insight, monthly AI energy reports and remote operations.|Commercial solar,Battery storage,EV fleets',
        'factorypulse|FactoryPulse — Non-Invasive OEE & Predictive Maintenance|Non-invasive machine energy and run/stop monitoring, OEE dashboards, PLC/SCADA integration, predictive maintenance and point expansion.|Old factories,Packaging lines,Process plants',
        'assetpulse|AssetPulse — High-Value Asset & Tool Tracking|BLE/UWB/LoRa tag tracking with geofence alerts, inventory and multi-site reports as a tag subscription.|Construction sites,Hospitals,Warehouses',
        'agribrain|AgriBrain — Greenhouse & Farm Intelligence (Future-Ready)|Future-ready soil, climate, water and fertilizer monitoring with seasonal service. Concept scope until partners and demand are validated.|Greenhouses,Farms,Irrigation',
      ].map((row: string) => { const [slug, title, description, scen] = row.split('|'); return { id: slug, slug, title, description, target_scenarios_json: scen.split(','), pain_points_json: [], budget_tiers_json: {}, delivery_flow_json: [] } }),
    {
      id: 'storageguard',
      slug: 'storageguard',
      title: 'StorageGuard — Cold Chain & Storage Compliance Monitoring',
      description: '24/7 temperature and humidity compliance monitoring for cold chain and precision storage: continuous monitoring, door-event logging, power-outage alerts, audit-ready reports, annual calibration, sensor battery replacement, and an annual Compliance Maintenance Contract.',
      target_scenarios_json: ['Pharmaceutical Warehouses', 'Food Cold Storage', 'Supermarket Cold Chain', 'Central Kitchens', 'Laboratories', 'Vaccine / Medical Storage'],
      pain_points_json: ['Product loss from undetected temperature excursions', 'No audit trail for inspectors (HACCP / GDP)', 'Power failures discovered too late', 'Manual paper logs that are easy to miss or fake'],
      budget_tiers_json: {
        starter: { label: 'Compliance Starter', description: 'Single cold room: gateway + temperature/humidity + door + outage alert.', starting_from: 1900 },
        standard: { label: 'Multi-Room Compliance', description: 'Several rooms with audit reports, calibration plan, and alert routing.', starting_from: 6500 },
        enterprise: { label: 'Enterprise / Multi-Site', description: 'Many rooms or sites with SLA, spare pool, and Compliance AMC.', starting_from: 18000 },
      },
      delivery_flow_json: ['Facility Assessment', 'Point & Threshold Design', 'Install & Commission', 'Report & Alert Setup', 'First-Year Support', 'Annual Calibration', 'Compliance AMC'],
      lifecycle_content_json: {
        headline: 'Cold Room Compliance Monitoring Package — sold as a serviceable outcome, not a sensor.',
        monitoring_points: [
          { name: 'Temperature & Humidity', detail: 'Continuous 24/7 readings per room with high/low thresholds.' },
          { name: 'Cold Room Door Events', detail: 'Door open/close logging and door-ajar alerts.' },
          { name: 'Power Outage Detection', detail: 'Backup-powered alert so failures are caught immediately.' },
          { name: 'Multi-Room / Multi-Site', detail: 'One dashboard across rooms, freezers, and locations.' },
        ],
        alert_channels: ['SMS', 'Telegram', 'Email', 'Phone call escalation', 'In-app'],
        reports: [
          'Monthly compliance summary (sample until customer-specific reporting is configured)',
          'Annual audit-ready report for HACCP / GDP inspections',
          'Calibration certificates per sensor',
        ],
        calibration_consumables: ['Annual sensor calibration with certificate', 'Sensor battery replacement', 'Probe replacement on lifecycle schedule'],
        recurring_charges: ['Platform & monitoring fee', 'Compliance report fee', 'Annual calibration fee', 'Consumables (batteries / probes)', 'Alarm monitoring / watch service', 'Annual Maintenance Contract (Compliance AMC)'],
        amc_options: [
          { name: 'Basic', detail: 'Remote alarm watch + annual check.' },
          { name: 'Compliance', detail: 'Reports + calibration + probe checks + maintenance record.' },
          { name: 'Commercial', detail: 'Multi-room monitoring + priority response + spare pool.' },
        ],
        service_boundary: 'AinerWise provides system-level monitoring, support coordination, and lifecycle service. Hardware follows the original supplier warranty unless a managed warranty or fast-replacement plan is purchased. On-site visits are quoted separately.',
      },
    },
    {
      id: 'remote-maintenance-plan',
      slug: 'remote-maintenance-plan',
      title: 'Remote Maintenance & Lifecycle Support',
      description: 'Long-term support for installed smart building systems with remote monitoring, backups, firmware planning, spare parts, inspections, and AI reports.',
      target_scenarios_json: ['Maintenance', 'Lifecycle', 'SLA', 'Spare Parts'],
      pain_points_json: ['No clear owner after installation', 'Firmware updates are risky', 'Spare parts are not planned'],
      budget_tiers_json: {
        budget: { label: 'Basic Support', description: 'One year document and remote support.', starting_from: 900 },
        standard: { label: 'Lifecycle Support', description: '3-5 year monitoring, inspection, and spare parts plan.', starting_from: 2600 },
        premium: { label: 'Premium Enterprise', description: 'SLA, AI reports, priority response, long-term spare parts.', starting_from: 7800 },
        future: { label: 'Custom Contract', description: '8-10 year enterprise lifecycle agreement.' },
      },
      delivery_flow_json: ['System audit', 'Backup', 'Monitoring', 'Inspection', 'Optimization report'],
    },
  ]

  const demoProducts = [
    {
      id: 'knx-ip-router-pro',
      slug: 'knx-ip-router-pro',
      category_id: 'knx-devices',
      name: 'KNX IP Router Pro',
      brand: 'AinerWise Official',
      description: 'Project-grade KNX/IP router for ETS commissioning, building backbone connection, and future AI integration.',
      source_type: 'official',
      service_available: true,
      moq: 1,
      list_price: 320,
      currency: 'EUR',
      lead_time_days: 14,
      warranty_years: 3,
      supply_tier: 'China tier-1 / project-grade sourcing',
      service_term_years: [5, 8, 10],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year lifecycle support', annual_fee: 180, note: 'Remote support, firmware planning, spare parts guidance' },
        { years: 8, label: '8-year commercial support', annual_fee: 260, note: 'Commercial SLA planning and annual inspection coordination' },
      ],
      specs_json: { protocol: 'KNX/IP', scenarios: 'Villa, office, hotel, school', intelligence: 'L2-L5', status: 'Available Now' },
    },
    {
      id: 'dali-knx-gateway',
      slug: 'dali-knx-gateway',
      category_id: 'gateways',
      name: 'DALI to KNX Lighting Gateway',
      brand: 'Verified Supplier',
      description: 'Lighting gateway for professional DALI dimming, scene control, and KNX building automation projects.',
      source_type: 'supplier',
      service_available: true,
      moq: 1,
      list_price: 580,
      currency: 'EUR',
      lead_time_days: 21,
      warranty_years: 2,
      supply_tier: 'Verified China tier-1 lighting/control supplier',
      service_term_years: [5, 8],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year lighting support', annual_fee: 240, note: 'Gateway health checks and scene update support' },
        { years: 8, label: '8-year commercial support', annual_fee: 360, note: 'Long-term component replacement planning' },
      ],
      specs_json: { protocol: 'DALI / KNX', scenarios: 'Office, hotel, school', intelligence: 'L2-L4', status: 'Project Dependent' },
    },
    {
      id: 'presence-co2-sensor',
      slug: 'presence-co2-sensor',
      category_id: 'sensors',
      name: 'Presence + CO2 + Temperature Sensor',
      brand: 'AinerWise Official',
      description: 'Multi-sensor for occupancy, air quality, comfort automation, classroom monitoring, and energy optimization.',
      source_type: 'official',
      service_available: true,
      moq: 4,
      list_price: 145,
      currency: 'EUR',
      lead_time_days: 12,
      warranty_years: 2,
      supply_tier: 'China first-tier sensor ecosystem',
      service_term_years: [5, 8],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year sensor support', annual_fee: 90, note: 'Calibration review and replacement planning' },
        { years: 8, label: '8-year lifecycle support', annual_fee: 140, note: 'Long-term sensor refresh planning' },
      ],
      specs_json: { protocol: 'KNX / MQTT variants', scenarios: 'Villa, school, office', intelligence: 'L2-L4', status: 'Available Now' },
    },
    {
      id: 'ai-cctv-poe-camera',
      slug: 'ai-cctv-poe-camera',
      category_id: 'cctv',
      name: 'PoE AI CCTV Camera',
      brand: 'Hikvision / Dahua class supplier',
      description: 'Service-ready IP camera with ONVIF/RTSP support for smart security, video AI projects, and local NVR integration.',
      source_type: 'supplier',
      service_available: true,
      moq: 4,
      list_price: 165,
      currency: 'EUR',
      lead_time_days: 18,
      warranty_years: 2,
      supply_tier: 'China first-tier CCTV ecosystem, not low-cost generic hardware',
      service_term_years: [5, 8],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year CCTV maintenance', annual_fee: 220, note: 'Camera health, NVR checks, firmware planning' },
        { years: 8, label: '8-year security lifecycle', annual_fee: 340, note: 'Spare unit reserve and long-term replacement plan' },
      ],
      specs_json: { protocol: 'ONVIF / RTSP / PoE', scenarios: 'Hotel, school, factory, apartment', intelligence: 'L2-L5', status: 'Available Now' },
    },
    {
      id: 'face-access-terminal',
      slug: 'face-access-terminal',
      category_id: 'access-control',
      name: 'Face Access Control Terminal',
      brand: 'Verified Supplier',
      description: 'Face recognition access terminal for office, hotel, apartment, school, and factory gate projects.',
      source_type: 'supplier',
      service_available: true,
      moq: 2,
      list_price: 420,
      currency: 'EUR',
      lead_time_days: 20,
      warranty_years: 2,
      supply_tier: 'China first-tier access control ecosystem',
      service_term_years: [5, 8],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year access support', annual_fee: 260, note: 'Permission policy review and device health checks' },
        { years: 8, label: '8-year access lifecycle', annual_fee: 390, note: 'Replacement planning and security update support' },
      ],
      specs_json: { protocol: 'TCP/IP, Wiegand, dry contact', scenarios: 'Office, apartment, factory', intelligence: 'L3-L5', status: 'Project Dependent' },
    },
    {
      id: 'edge-ai-building-box',
      slug: 'edge-ai-building-box',
      category_id: 'network',
      name: 'Local AI Building Edge Box',
      brand: 'AinerWise Official',
      description: 'Edge compute box for local AI workflows, building data collection, dashboards, automation logic, and privacy-sensitive deployments.',
      source_type: 'official',
      service_available: true,
      moq: 1,
      currency: 'EUR',
      lead_time_days: 30,
      warranty_years: 3,
      supply_tier: 'AinerWise local AI / China edge compute supply chain',
      service_term_years: [5, 8, 10],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year AI operations support', annual_fee: 680, note: 'Model workflow updates, backup, monitoring' },
        { years: 8, label: '8-year AI lifecycle', annual_fee: 980, note: 'Hardware refresh planning and priority engineering review' },
        { years: 10, label: '10-year enterprise support', annual_fee: 1450, note: 'Custom long-term AI operations contract' },
      ],
      specs_json: { protocol: 'MQTT, REST, Modbus TCP, ONVIF', scenarios: 'Villa, office, school, factory', intelligence: 'L4-L5', status: 'Advanced Custom' },
    },
    {
      id: 'solar-energy-gateway',
      slug: 'solar-energy-gateway',
      category_id: 'energy',
      name: 'Solar / Battery / EV Energy Gateway',
      brand: 'Huawei Digital Power / Sungrow class',
      description: 'Gateway layer for inverter, battery, EV charger, meter, tariff, and building load visualization.',
      source_type: 'official',
      service_available: true,
      moq: 1,
      list_price: 690,
      currency: 'EUR',
      lead_time_days: 21,
      warranty_years: 3,
      supply_tier: 'China first-tier energy ecosystem: Huawei, Sungrow, LONGi class',
      service_term_years: [5, 8, 10],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year energy monitoring', annual_fee: 520, note: 'Inverter, meter, EV and alert review' },
        { years: 8, label: '8-year commercial energy support', annual_fee: 780, note: 'Annual optimization and spare gateway planning' },
        { years: 10, label: '10-year energy lifecycle', annual_fee: 1150, note: 'Custom enterprise support and upgrade roadmap' },
      ],
      specs_json: { protocol: 'Modbus TCP/RTU, MQTT', scenarios: 'Energy site, factory, villa, office', intelligence: 'L3-L5', status: 'Project Dependent' },
    },
    {
      id: 'industrial-plc-gateway',
      slug: 'industrial-plc-gateway',
      category_id: 'factory-automation',
      name: 'Industrial PLC / Modbus / OPC UA Gateway',
      brand: 'Verified Industrial Supplier',
      description: 'Factory data gateway for machine status, power usage, alarms, compressed air, and maintenance workflows.',
      source_type: 'supplier',
      service_available: true,
      moq: 1,
      list_price: 880,
      currency: 'EUR',
      lead_time_days: 28,
      warranty_years: 2,
      supply_tier: 'China first-tier industrial gateway / automation ecosystem',
      service_term_years: [5, 8, 10],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year factory gateway support', annual_fee: 850, note: 'OT gateway health, alarm rules, backup' },
        { years: 8, label: '8-year industrial lifecycle', annual_fee: 1280, note: 'SLA planning, spare gateway, protocol change support' },
        { years: 10, label: '10-year factory support', annual_fee: 1800, note: 'Custom plant-level lifecycle contract' },
      ],
      specs_json: { protocol: 'Modbus, OPC UA, MQTT, Ethernet/IP options', scenarios: 'Factory, warehouse, production line', intelligence: 'L3-L5', status: 'Project Dependent' },
    },
    {
      id: 'amr-ready-docking-interface',
      slug: 'amr-ready-docking-interface',
      category_id: 'robotics',
      name: 'AMR / Service Robot Docking Interface',
      brand: 'Concept Partner',
      description: 'Robot-ready integration placeholder for doors, elevators, charging docks, routes, and facility permissions.',
      source_type: 'supplier',
      service_available: false,
      moq: 1,
      currency: 'EUR',
      lead_time_days: 60,
      warranty_years: 1,
      supply_tier: 'China first-tier robotics / AMR ecosystem, concept-stage integration',
      service_term_years: [5, 8],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year robot-ready support', annual_fee: 1200, note: 'Docking API review and facility permission updates' },
        { years: 8, label: '8-year robot lifecycle', annual_fee: 1800, note: 'Custom integration roadmap and safety review' },
      ],
      specs_json: { protocol: 'API / MQTT / dry contact', scenarios: 'Hotel, office, factory', intelligence: 'L5-L6', status: 'Concept Demo' },
    },
    {
      id: 'lifecycle-support-5y',
      slug: 'lifecycle-support-5y',
      category_id: 'service-packages',
      name: 'Lifecycle Support 5 Years',
      brand: 'AinerWise Service',
      description: 'Remote monitoring, annual inspection, spare parts planning, firmware support, and AI operations reports.',
      source_type: 'official',
      service_available: true,
      moq: 1,
      currency: 'EUR',
      warranty_years: 5,
      supply_tier: 'AinerWise lifecycle service',
      service_term_years: [5, 8, 10],
      lifecycle_pricing_json: [
        { years: 5, label: '5-year lifecycle support', annual_fee: 2600, note: 'Remote monitoring, annual inspection, AI report' },
        { years: 8, label: '8-year commercial support', annual_fee: 4200, note: 'SLA planning, spare parts, quarterly review' },
        { years: 10, label: '10-year enterprise support', annual_fee: 6800, note: 'Dedicated long-term lifecycle contract' },
      ],
      specs_json: { coverage: 'Remote support, inspection, AI report', scenarios: 'Commercial, hotel, school, factory', status: 'Available Now' },
    },
  ].map((product: any) => ({
    service_pricing_note: 'Device price is only a reference. Final project pricing includes design, installation, commissioning, spare parts reserve, support period, site survey, supplier confirmation, and signed contract.',
    project_pricing_mode: product.list_price ? 'device_reference_plus_project_service' : 'project_based_quote',
    price_options_json: product.list_price
      ? [
          { label: 'Device reference', value: `EUR ${product.list_price}`, note: 'Reference hardware price, not final project quote' },
          { label: 'Project supply + commissioning', value: 'Request project quote', note: 'Depends on quantity, region, installation, and support term' },
        ]
      : [
          { label: 'Project-based estimate', value: 'Request quote', note: 'Custom engineering and supplier confirmation required' },
        ],
    supply_tier: 'China first-tier / project-grade supply chain',
    service_term_years: [5, 8],
    lifecycle_pricing_json: [
      { years: 5, label: '5-year lifecycle support', annual_fee: 300, note: 'Remote support and annual health review' },
      { years: 8, label: '8-year commercial support', annual_fee: 480, note: 'Long-term spare parts and SLA planning' },
    ],
    ...product,
  }))

  const demoServicePackages = [
    {
      id: 'included-remote-assurance',
      slug: 'basic-support',
      name: 'Included Remote Assurance',
      years: 3,
      description: 'Included with qualifying delivered projects: practical remote support without bundling costly site visits.',
      included_services_json: ['Remote diagnosis and technical consultation', 'Handover documentation and configuration records', 'Supplier warranty coordination', 'Remote configuration backup guidance'],
      price_rule_json: { term_label: '3 years included' },
    },
    {
      id: 'lifecycle-care-annual',
      slug: 'standard-3yr',
      name: 'Lifecycle Care Plan',
      years: 1,
      description: 'A renewable annual plan for customers who want proactive remote maintenance and clearer lifecycle planning.',
      included_services_json: ['Scheduled remote health review', 'Configuration backup audit', 'Compatibility and upgrade advice', 'Spare parts pool planning', 'Priority remote response'],
      price_rule_json: { term_label: 'Annual paid plan' },
    },
    {
      id: 'managed-sla-plan',
      slug: 'lifecycle-5yr',
      name: 'Managed SLA Plan',
      years: 8,
      description: 'A custom plan for business-critical sites that need agreed response targets, monitoring strategy, and local dispatch coordination.',
      included_services_json: ['Agreed SLA response targets', 'Monitoring and maintenance calendar', 'Dedicated spare parts strategy', 'Local partner dispatch coordination', 'Quarterly service summary'],
      price_rule_json: { term_label: 'Custom SLA quote' },
    },
  ]

  return {
    demoCategories,
    demoProducts,
    demoServicePackages,
    demoSolutions,
    demoSupplyPartners,
  }
}
