"""cebu payment configuration and reconciliation

Revision ID: 052
Revises: 051
Create Date: 2026-06-12 18:51:05.933401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '052'
down_revision: Union[str, None] = '051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_configs',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('minor_unit', sa.Integer(), nullable=False),
    sa.Column('is_fiat', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_configs_code'), 'currency_configs', ['code'], unique=True)
    op.create_index(op.f('ix_currency_configs_is_enabled'), 'currency_configs', ['is_enabled'], unique=False)
    op.create_table('fee_rules',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('fee_type', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fixed_fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('variable_bps', sa.Integer(), nullable=False),
    sa.Column('min_fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('max_fee_minor', sa.BigInteger(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_rules_country_code'), 'fee_rules', ['country_code'], unique=False)
    op.create_index(op.f('ix_fee_rules_fee_type'), 'fee_rules', ['fee_type'], unique=False)
    op.create_index(op.f('ix_fee_rules_is_enabled'), 'fee_rules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_fee_rules_payment_method'), 'fee_rules', ['payment_method'], unique=False)
    op.create_table('fx_quotes',
    sa.Column('source_currency', sa.String(length=10), nullable=False),
    sa.Column('target_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_source', sa.String(length=80), nullable=False),
    sa.Column('provider_quote_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_quotes_expires_at'), 'fx_quotes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_fx_quotes_source_currency'), 'fx_quotes', ['source_currency'], unique=False)
    op.create_index(op.f('ix_fx_quotes_target_currency'), 'fx_quotes', ['target_currency'], unique=False)
    op.create_table('payment_method_configs',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('method_code', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'method_code', 'currency', name='uq_payment_method_config_scope')
    )
    op.create_index(op.f('ix_payment_method_configs_country_code'), 'payment_method_configs', ['country_code'], unique=False)
    op.create_index(op.f('ix_payment_method_configs_currency'), 'payment_method_configs', ['currency'], unique=False)
    op.create_index(op.f('ix_payment_method_configs_is_enabled'), 'payment_method_configs', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_payment_method_configs_method_code'), 'payment_method_configs', ['method_code'], unique=False)
    op.create_table('region_payment_configs',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('local_currency', sa.String(length=10), nullable=False),
    sa.Column('default_settlement_currency', sa.String(length=10), nullable=False),
    sa.Column('default_transaction_mode', sa.String(length=64), nullable=False),
    sa.Column('enabled_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled_payment_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cross_border_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('force_usd_bridge', sa.Boolean(), nullable=False),
    sa.Column('allow_supplier_payout_currency', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_payment_configs_country_code'), 'region_payment_configs', ['country_code'], unique=True)
    op.create_index(op.f('ix_region_payment_configs_is_active'), 'region_payment_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_region_payment_configs_local_currency'), 'region_payment_configs', ['local_currency'], unique=False)
    op.create_table('payment_quotes',
    sa.Column('buyer_country', sa.String(length=2), nullable=False),
    sa.Column('supplier_country', sa.String(length=2), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('order_currency', sa.String(length=10), nullable=False),
    sa.Column('payer_currency', sa.String(length=10), nullable=False),
    sa.Column('settlement_currency', sa.String(length=10), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('payer_total_minor', sa.BigInteger(), nullable=False),
    sa.Column('escrow_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('supplier_estimated_net_minor', sa.BigInteger(), nullable=False),
    sa.Column('platform_revenue_minor', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rate_source', sa.String(length=80), nullable=True),
    sa.Column('fx_quote_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fx_quote_id'], ['fx_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_quotes_buyer_country'), 'payment_quotes', ['buyer_country'], unique=False)
    op.create_index(op.f('ix_payment_quotes_expires_at'), 'payment_quotes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_payment_quotes_fx_quote_id'), 'payment_quotes', ['fx_quote_id'], unique=False)
    op.create_index(op.f('ix_payment_quotes_mode'), 'payment_quotes', ['mode'], unique=False)
    op.create_index(op.f('ix_payment_quotes_payment_method'), 'payment_quotes', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payment_quotes_status'), 'payment_quotes', ['status'], unique=False)
    op.create_index(op.f('ix_payment_quotes_supplier_country'), 'payment_quotes', ['supplier_country'], unique=False)
    op.create_table('provider_payment_intents',
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['commerce_orders.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['payment_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_payment_intents_order_id'), 'provider_payment_intents', ['order_id'], unique=False)
    op.create_index(op.f('ix_provider_payment_intents_provider_reference'), 'provider_payment_intents', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_provider_payment_intents_quote_id'), 'provider_payment_intents', ['quote_id'], unique=False)
    op.create_index(op.f('ix_provider_payment_intents_status'), 'provider_payment_intents', ['status'], unique=False)
    op.create_table('fee_line_items',
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('payment_intent_id', sa.UUID(), nullable=True),
    sa.Column('fee_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['provider_payment_intents.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['payment_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_line_items_fee_type'), 'fee_line_items', ['fee_type'], unique=False)
    op.create_index(op.f('ix_fee_line_items_payment_intent_id'), 'fee_line_items', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_fee_line_items_quote_id'), 'fee_line_items', ['quote_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('escrow_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_transactions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['commerce_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_events_provider'), 'payment_events', ['provider'], unique=False)
    op.create_table('settlement_events',
    sa.Column('payment_intent_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('gross_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['provider_payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_events_payment_intent_id'), 'settlement_events', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_settlement_events_provider'), 'settlement_events', ['provider'], unique=False)
    op.create_index(op.f('ix_settlement_events_provider_reference'), 'settlement_events', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_settlement_events_status'), 'settlement_events', ['status'], unique=False)
    op.create_table('settlement_adjustments',
    sa.Column('settlement_event_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=80), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['settlement_event_id'], ['settlement_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_adjustments_adjustment_type'), 'settlement_adjustments', ['adjustment_type'], unique=False)
    op.create_index(op.f('ix_settlement_adjustments_settlement_event_id'), 'settlement_adjustments', ['settlement_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_adjustments_settlement_event_id'), table_name='settlement_adjustments')
    op.drop_index(op.f('ix_settlement_adjustments_adjustment_type'), table_name='settlement_adjustments')
    op.drop_table('settlement_adjustments')
    op.drop_index(op.f('ix_settlement_events_status'), table_name='settlement_events')
    op.drop_index(op.f('ix_settlement_events_provider_reference'), table_name='settlement_events')
    op.drop_index(op.f('ix_settlement_events_provider'), table_name='settlement_events')
    op.drop_index(op.f('ix_settlement_events_payment_intent_id'), table_name='settlement_events')
    op.drop_table('settlement_events')
    op.drop_index(op.f('ix_payment_events_provider'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_fee_line_items_quote_id'), table_name='fee_line_items')
    op.drop_index(op.f('ix_fee_line_items_payment_intent_id'), table_name='fee_line_items')
    op.drop_index(op.f('ix_fee_line_items_fee_type'), table_name='fee_line_items')
    op.drop_table('fee_line_items')
    op.drop_index(op.f('ix_provider_payment_intents_status'), table_name='provider_payment_intents')
    op.drop_index(op.f('ix_provider_payment_intents_quote_id'), table_name='provider_payment_intents')
    op.drop_index(op.f('ix_provider_payment_intents_provider_reference'), table_name='provider_payment_intents')
    op.drop_index(op.f('ix_provider_payment_intents_order_id'), table_name='provider_payment_intents')
    op.drop_table('provider_payment_intents')
    op.drop_index(op.f('ix_payment_quotes_supplier_country'), table_name='payment_quotes')
    op.drop_index(op.f('ix_payment_quotes_status'), table_name='payment_quotes')
    op.drop_index(op.f('ix_payment_quotes_payment_method'), table_name='payment_quotes')
    op.drop_index(op.f('ix_payment_quotes_mode'), table_name='payment_quotes')
    op.drop_index(op.f('ix_payment_quotes_fx_quote_id'), table_name='payment_quotes')
    op.drop_index(op.f('ix_payment_quotes_expires_at'), table_name='payment_quotes')
    op.drop_index(op.f('ix_payment_quotes_buyer_country'), table_name='payment_quotes')
    op.drop_table('payment_quotes')
    op.drop_index(op.f('ix_region_payment_configs_local_currency'), table_name='region_payment_configs')
    op.drop_index(op.f('ix_region_payment_configs_is_active'), table_name='region_payment_configs')
    op.drop_index(op.f('ix_region_payment_configs_country_code'), table_name='region_payment_configs')
    op.drop_table('region_payment_configs')
    op.drop_index(op.f('ix_payment_method_configs_method_code'), table_name='payment_method_configs')
    op.drop_index(op.f('ix_payment_method_configs_is_enabled'), table_name='payment_method_configs')
    op.drop_index(op.f('ix_payment_method_configs_currency'), table_name='payment_method_configs')
    op.drop_index(op.f('ix_payment_method_configs_country_code'), table_name='payment_method_configs')
    op.drop_table('payment_method_configs')
    op.drop_index(op.f('ix_fx_quotes_target_currency'), table_name='fx_quotes')
    op.drop_index(op.f('ix_fx_quotes_source_currency'), table_name='fx_quotes')
    op.drop_index(op.f('ix_fx_quotes_expires_at'), table_name='fx_quotes')
    op.drop_table('fx_quotes')
    op.drop_index(op.f('ix_fee_rules_payment_method'), table_name='fee_rules')
    op.drop_index(op.f('ix_fee_rules_is_enabled'), table_name='fee_rules')
    op.drop_index(op.f('ix_fee_rules_fee_type'), table_name='fee_rules')
    op.drop_index(op.f('ix_fee_rules_country_code'), table_name='fee_rules')
    op.drop_table('fee_rules')
    op.drop_index(op.f('ix_currency_configs_is_enabled'), table_name='currency_configs')
    op.drop_index(op.f('ix_currency_configs_code'), table_name='currency_configs')
    op.drop_table('currency_configs')
    # ### end Alembic commands ###
