"""buyer project reports metrics and trust events

Revision ID: 053
Revises: 052
Create Date: 2026-06-12 19:01:48.821347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '053'
down_revision: Union[str, None] = '052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_project_metric_values',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_metric_values_key'), 'buyer_project_metric_values', ['key'], unique=False)
    op.create_index(op.f('ix_buyer_project_metric_values_project_id'), 'buyer_project_metric_values', ['project_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_metric_values_template_id'), 'buyer_project_metric_values', ['template_id'], unique=False)
    op.create_table('buyer_project_price_snapshots',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('line_item_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('min_unit_price', sa.Float(), nullable=True),
    sa.Column('avg_unit_price', sa.Float(), nullable=True),
    sa.Column('median_unit_price', sa.Float(), nullable=True),
    sa.Column('p20_unit_price', sa.Float(), nullable=True),
    sa.Column('p80_unit_price', sa.Float(), nullable=True),
    sa.Column('price_tiers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('samples_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_price_snapshots_line_item_id'), 'buyer_project_price_snapshots', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_price_snapshots_project_id'), 'buyer_project_price_snapshots', ['project_id'], unique=False)
    op.create_table('buyer_project_report_change_logs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('patch_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_report_change_logs_actor_id'), 'buyer_project_report_change_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_change_logs_project_id'), 'buyer_project_report_change_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_change_logs_report_id'), 'buyer_project_report_change_logs', ['report_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_change_logs_status'), 'buyer_project_report_change_logs', ['status'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_change_logs_version_id'), 'buyer_project_report_change_logs', ['version_id'], unique=False)
    op.create_table('buyer_project_report_columns',
    sa.Column('report_version_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_version_id', 'key', name='uq_buyer_project_report_column_key')
    )
    op.create_index(op.f('ix_buyer_project_report_columns_key'), 'buyer_project_report_columns', ['key'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_columns_report_version_id'), 'buyer_project_report_columns', ['report_version_id'], unique=False)
    op.create_table('buyer_project_report_rows',
    sa.Column('report_version_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('line_item_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quality_tier', sa.String(length=20), nullable=False),
    sa.Column('selected_tier', sa.String(length=20), nullable=False),
    sa.Column('include_in_total', sa.Boolean(), nullable=False),
    sa.Column('selected_for_purchase', sa.Boolean(), nullable=False),
    sa.Column('price_tiers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('samples_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_report_rows_category_id'), 'buyer_project_report_rows', ['category_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_rows_line_item_id'), 'buyer_project_report_rows', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_rows_project_id'), 'buyer_project_report_rows', ['project_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_rows_report_version_id'), 'buyer_project_report_rows', ['report_version_id'], unique=False)
    op.create_table('buyer_project_report_versions',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('totals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version_number', name='uq_buyer_project_report_version_number')
    )
    op.create_index(op.f('ix_buyer_project_report_versions_created_by'), 'buyer_project_report_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_versions_project_id'), 'buyer_project_report_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_versions_report_id'), 'buyer_project_report_versions', ['report_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_report_versions_status'), 'buyer_project_report_versions', ['status'], unique=False)
    op.create_table('buyer_project_reports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('frozen_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_reports_current_version_id'), 'buyer_project_reports', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_reports_frozen_version_id'), 'buyer_project_reports', ['frozen_version_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_reports_project_id'), 'buyer_project_reports', ['project_id'], unique=False)
    op.create_table('trust_score_events',
    sa.Column('trust_profile_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('before_score', sa.Integer(), nullable=False),
    sa.Column('after_score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trust_profile_id'], ['trust_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_score_events_created_by'), 'trust_score_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_trust_score_events_event_type'), 'trust_score_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trust_score_events_related_entity_id'), 'trust_score_events', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_trust_score_events_related_entity_type'), 'trust_score_events', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_trust_score_events_trust_profile_id'), 'trust_score_events', ['trust_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_score_events_trust_profile_id'), table_name='trust_score_events')
    op.drop_index(op.f('ix_trust_score_events_related_entity_type'), table_name='trust_score_events')
    op.drop_index(op.f('ix_trust_score_events_related_entity_id'), table_name='trust_score_events')
    op.drop_index(op.f('ix_trust_score_events_event_type'), table_name='trust_score_events')
    op.drop_index(op.f('ix_trust_score_events_created_by'), table_name='trust_score_events')
    op.drop_table('trust_score_events')
    op.drop_index(op.f('ix_buyer_project_reports_project_id'), table_name='buyer_project_reports')
    op.drop_index(op.f('ix_buyer_project_reports_frozen_version_id'), table_name='buyer_project_reports')
    op.drop_index(op.f('ix_buyer_project_reports_current_version_id'), table_name='buyer_project_reports')
    op.drop_table('buyer_project_reports')
    op.drop_index(op.f('ix_buyer_project_report_versions_status'), table_name='buyer_project_report_versions')
    op.drop_index(op.f('ix_buyer_project_report_versions_report_id'), table_name='buyer_project_report_versions')
    op.drop_index(op.f('ix_buyer_project_report_versions_project_id'), table_name='buyer_project_report_versions')
    op.drop_index(op.f('ix_buyer_project_report_versions_created_by'), table_name='buyer_project_report_versions')
    op.drop_table('buyer_project_report_versions')
    op.drop_index(op.f('ix_buyer_project_report_rows_report_version_id'), table_name='buyer_project_report_rows')
    op.drop_index(op.f('ix_buyer_project_report_rows_project_id'), table_name='buyer_project_report_rows')
    op.drop_index(op.f('ix_buyer_project_report_rows_line_item_id'), table_name='buyer_project_report_rows')
    op.drop_index(op.f('ix_buyer_project_report_rows_category_id'), table_name='buyer_project_report_rows')
    op.drop_table('buyer_project_report_rows')
    op.drop_index(op.f('ix_buyer_project_report_columns_report_version_id'), table_name='buyer_project_report_columns')
    op.drop_index(op.f('ix_buyer_project_report_columns_key'), table_name='buyer_project_report_columns')
    op.drop_table('buyer_project_report_columns')
    op.drop_index(op.f('ix_buyer_project_report_change_logs_version_id'), table_name='buyer_project_report_change_logs')
    op.drop_index(op.f('ix_buyer_project_report_change_logs_status'), table_name='buyer_project_report_change_logs')
    op.drop_index(op.f('ix_buyer_project_report_change_logs_report_id'), table_name='buyer_project_report_change_logs')
    op.drop_index(op.f('ix_buyer_project_report_change_logs_project_id'), table_name='buyer_project_report_change_logs')
    op.drop_index(op.f('ix_buyer_project_report_change_logs_actor_id'), table_name='buyer_project_report_change_logs')
    op.drop_table('buyer_project_report_change_logs')
    op.drop_index(op.f('ix_buyer_project_price_snapshots_project_id'), table_name='buyer_project_price_snapshots')
    op.drop_index(op.f('ix_buyer_project_price_snapshots_line_item_id'), table_name='buyer_project_price_snapshots')
    op.drop_table('buyer_project_price_snapshots')
    op.drop_index(op.f('ix_buyer_project_metric_values_template_id'), table_name='buyer_project_metric_values')
    op.drop_index(op.f('ix_buyer_project_metric_values_project_id'), table_name='buyer_project_metric_values')
    op.drop_index(op.f('ix_buyer_project_metric_values_key'), table_name='buyer_project_metric_values')
    op.drop_table('buyer_project_metric_values')
    # ### end Alembic commands ###
