"""buyer project metric value uniqueness

Revision ID: 054
Revises: 053
Create Date: 2026-06-12 19:05:49.534999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054'
down_revision: Union[str, None] = '053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_buyer_project_metric_value_key', 'buyer_project_metric_values', ['project_id', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_buyer_project_metric_value_key', 'buyer_project_metric_values', type_='unique')
    # ### end Alembic commands ###
