"""buyer project zero loss fields

Revision ID: 055
Revises: 054
Create Date: 2026-06-12 19:10:22.359663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '055'
down_revision: Union[str, None] = '054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer_project_line_items', sa.Column('sourcing_notes', sa.Text(), nullable=True))
    op.add_column('buyer_project_line_items', sa.Column('category_hint', sa.String(length=200), nullable=True))
    op.add_column('buyer_projects', sa.Column('acceptance_criteria_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyer_projects', 'acceptance_criteria_json')
    op.drop_column('buyer_project_line_items', 'category_hint')
    op.drop_column('buyer_project_line_items', 'sourcing_notes')
    # ### end Alembic commands ###
