"""add kyc verification and buyer project tables

Revision ID: 74ba695300ac
Revises: c560dad4048c
Create Date: 2026-06-12 05:27:19.165876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74ba695300ac'
down_revision: Union[str, None] = 'c560dad4048c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_project_ai_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('structured_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_ai_runs_project_id'), 'buyer_project_ai_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_ai_runs_status'), 'buyer_project_ai_runs', ['status'], unique=False)
    op.create_table('buyer_project_files',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('vision_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_files_project_id'), 'buyer_project_files', ['project_id'], unique=False)
    op.create_table('buyer_project_line_items',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('procurement_request_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quality_tier', sa.String(length=20), nullable=False),
    sa.Column('estimated_unit_price', sa.Float(), nullable=True),
    sa.Column('estimated_total_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('price_tiers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('include_in_estimate', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_line_items_project_id'), 'buyer_project_line_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_buyer_project_line_items_status'), 'buyer_project_line_items', ['status'], unique=False)
    op.create_table('buyer_project_messages',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('workflow_node', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structured_delta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_project_messages_project_id'), 'buyer_project_messages', ['project_id'], unique=False)
    op.create_table('buyer_projects',
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('area_value', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=50), nullable=True),
    sa.Column('scale_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quality_preference', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('missing_questions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_notes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_budget_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_projects_buyer_id'), 'buyer_projects', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_projects_status'), 'buyer_projects', ['status'], unique=False)
    op.create_table('company_documents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_documents_company_id'), 'company_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_documents_doc_type'), 'company_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_company_documents_status'), 'company_documents', ['status'], unique=False)
    op.create_table('kyc_analysis_results',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('analyzed_by', sa.UUID(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('authenticity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=32), nullable=False),
    sa.Column('tamper_suspected', sa.Boolean(), nullable=False),
    sa.Column('photoshop_suspected', sa.Boolean(), nullable=False),
    sa.Column('text_photo_consistency', sa.Boolean(), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_analysis_results_analyzed_by'), 'kyc_analysis_results', ['analyzed_by'], unique=False)
    op.create_index(op.f('ix_kyc_analysis_results_company_id'), 'kyc_analysis_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_kyc_analysis_results_document_id'), 'kyc_analysis_results', ['document_id'], unique=False)
    op.create_table('verification_reviews',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('user_facing_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reviews_company_id'), 'verification_reviews', ['company_id'], unique=False)
    op.create_index(op.f('ix_verification_reviews_status'), 'verification_reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_reviews_status'), table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_company_id'), table_name='verification_reviews')
    op.drop_table('verification_reviews')
    op.drop_index(op.f('ix_kyc_analysis_results_document_id'), table_name='kyc_analysis_results')
    op.drop_index(op.f('ix_kyc_analysis_results_company_id'), table_name='kyc_analysis_results')
    op.drop_index(op.f('ix_kyc_analysis_results_analyzed_by'), table_name='kyc_analysis_results')
    op.drop_table('kyc_analysis_results')
    op.drop_index(op.f('ix_company_documents_status'), table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_doc_type'), table_name='company_documents')
    op.drop_index(op.f('ix_company_documents_company_id'), table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_index(op.f('ix_buyer_projects_status'), table_name='buyer_projects')
    op.drop_index(op.f('ix_buyer_projects_buyer_id'), table_name='buyer_projects')
    op.drop_table('buyer_projects')
    op.drop_index(op.f('ix_buyer_project_messages_project_id'), table_name='buyer_project_messages')
    op.drop_table('buyer_project_messages')
    op.drop_index(op.f('ix_buyer_project_line_items_status'), table_name='buyer_project_line_items')
    op.drop_index(op.f('ix_buyer_project_line_items_project_id'), table_name='buyer_project_line_items')
    op.drop_table('buyer_project_line_items')
    op.drop_index(op.f('ix_buyer_project_files_project_id'), table_name='buyer_project_files')
    op.drop_table('buyer_project_files')
    op.drop_index(op.f('ix_buyer_project_ai_runs_status'), table_name='buyer_project_ai_runs')
    op.drop_index(op.f('ix_buyer_project_ai_runs_project_id'), table_name='buyer_project_ai_runs')
    op.drop_table('buyer_project_ai_runs')
    # ### end Alembic commands ###
