"""add cebu trade tables: wallets, deposits, addresses, shipping, ads, escrow, payouts

Revision ID: c560dad4048c
Revises: 040
Create Date: 2026-06-11 22:29:07.819546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c560dad4048c'
down_revision: Union[str, None] = '040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_routes',
    sa.Column('origin_country', sa.String(length=5), nullable=False),
    sa.Column('origin_region', sa.String(length=100), nullable=True),
    sa.Column('dest_country', sa.String(length=5), nullable=False),
    sa.Column('dest_region', sa.String(length=100), nullable=True),
    sa.Column('shipping_method', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_routes_dest_country'), 'shipping_routes', ['dest_country'], unique=False)
    op.create_index(op.f('ix_shipping_routes_origin_country'), 'shipping_routes', ['origin_country'], unique=False)
    op.create_table('shipping_rates',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('weight_min_kg', sa.Float(), nullable=False),
    sa.Column('weight_max_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('min_charge_minor', sa.BigInteger(), nullable=False),
    sa.Column('volume_factor', sa.Float(), nullable=False),
    sa.Column('estimated_days_min', sa.Integer(), nullable=False),
    sa.Column('estimated_days_max', sa.Integer(), nullable=False),
    sa.Column('surcharges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['shipping_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_rates_route_id'), 'shipping_rates', ['route_id'], unique=False)
    op.create_table('ad_campaigns',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('placement', sa.String(length=32), nullable=False),
    sa.Column('target_category_id', sa.UUID(), nullable=True),
    sa.Column('target_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_minor', sa.BigInteger(), nullable=False),
    sa.Column('spent_minor', sa.BigInteger(), nullable=False),
    sa.Column('bid_per_click_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['supplier_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_company_id'), 'ad_campaigns', ['company_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_listing_id'), 'ad_campaigns', ['listing_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_status'), 'ad_campaigns', ['status'], unique=False)
    op.create_table('addresses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('address_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_country_code'), 'addresses', ['country_code'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('available_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('locked_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_deposited_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_currency'), 'wallets', ['currency'], unique=False)
    op.create_index(op.f('ix_wallets_owner_user_id'), 'wallets', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_wallets_status'), 'wallets', ['status'], unique=False)
    op.create_table('wallet_deposits',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('source_currency', sa.String(length=10), nullable=True),
    sa.Column('target_currency', sa.String(length=10), nullable=True),
    sa.Column('deposit_address', sa.String(length=255), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitter_note', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_deposits_owner_user_id'), 'wallet_deposits', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_wallet_deposits_status'), 'wallet_deposits', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_deposits_tx_hash'), 'wallet_deposits', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_wallet_deposits_wallet_id'), 'wallet_deposits', ['wallet_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('tx_type', sa.String(length=64), nullable=False),
    sa.Column('amount_delta_minor', sa.BigInteger(), nullable=False),
    sa.Column('available_balance_after_minor', sa.BigInteger(), nullable=False),
    sa.Column('locked_balance_after_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_owner_user_id'), 'wallet_transactions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_tx_type'), 'wallet_transactions', ['tx_type'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('escrow_transactions',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('auth_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('captured_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('released_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('refunded_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_event_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['commerce_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_transactions_order_id'), 'escrow_transactions', ['order_id'], unique=True)
    op.create_index(op.f('ix_escrow_transactions_status'), 'escrow_transactions', ['status'], unique=False)
    op.create_table('order_shipping',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('shipping_method', sa.String(length=32), nullable=False),
    sa.Column('origin_address_id', sa.UUID(), nullable=True),
    sa.Column('dest_address_id', sa.UUID(), nullable=True),
    sa.Column('chargeable_weight_kg', sa.Float(), nullable=True),
    sa.Column('shipping_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('estimated_days_min', sa.Integer(), nullable=True),
    sa.Column('estimated_days_max', sa.Integer(), nullable=True),
    sa.Column('tracking_number', sa.String(length=200), nullable=True),
    sa.Column('carrier_name', sa.String(length=200), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dest_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['commerce_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_shipping_order_id'), 'order_shipping', ['order_id'], unique=True)
    op.create_index(op.f('ix_order_shipping_status'), 'order_shipping', ['status'], unique=False)
    op.create_table('payouts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_hold', sa.Boolean(), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_transactions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['commerce_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_company_id'), 'payouts', ['company_id'], unique=False)
    op.create_index(op.f('ix_payouts_order_id'), 'payouts', ['order_id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.alter_column('commerce_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_messages_thread'), table_name='commerce_messages')
    op.create_index(op.f('ix_commerce_messages_thread_id'), 'commerce_messages', ['thread_id'], unique=False)
    op.alter_column('commerce_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_orders_legacy'), table_name='commerce_orders')
    op.create_index(op.f('ix_commerce_orders_procurement_request_id'), 'commerce_orders', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_commerce_orders_status'), 'commerce_orders', ['status'], unique=False)
    op.create_unique_constraint(None, 'commerce_orders', ['legacy_order_id'])
    op.alter_column('commerce_payment_intents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_payment_intents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_commerce_payment_intents_payment_plan_id'), 'commerce_payment_intents', ['payment_plan_id'], unique=False)
    op.alter_column('commerce_reconciliation_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_reconciliation_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_recon_runs_status'), table_name='commerce_reconciliation_runs')
    op.create_index(op.f('ix_commerce_reconciliation_runs_status'), 'commerce_reconciliation_runs', ['status'], unique=False)
    op.alter_column('commerce_settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_settlements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_settlements_order'), table_name='commerce_settlements')
    op.create_index(op.f('ix_commerce_settlements_commerce_order_id'), 'commerce_settlements', ['commerce_order_id'], unique=False)
    op.create_index(op.f('ix_commerce_settlements_milestone_id'), 'commerce_settlements', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_commerce_settlements_payment_intent_id'), 'commerce_settlements', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_commerce_settlements_psp_settlement_ref'), 'commerce_settlements', ['psp_settlement_ref'], unique=False)
    op.alter_column('commerce_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_threads_order'), table_name='commerce_threads')
    op.drop_index(op.f('ix_commerce_threads_request'), table_name='commerce_threads')
    op.create_index(op.f('ix_commerce_threads_buyer_company_id'), 'commerce_threads', ['buyer_company_id'], unique=False)
    op.create_index(op.f('ix_commerce_threads_commerce_order_id'), 'commerce_threads', ['commerce_order_id'], unique=False)
    op.create_index(op.f('ix_commerce_threads_portal_key'), 'commerce_threads', ['portal_key'], unique=False)
    op.create_index(op.f('ix_commerce_threads_procurement_request_id'), 'commerce_threads', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_commerce_threads_status'), 'commerce_threads', ['status'], unique=False)
    op.create_index(op.f('ix_commerce_threads_supplier_company_id'), 'commerce_threads', ['supplier_company_id'], unique=False)
    op.alter_column('crew_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crew_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_crew_memberships_crew_id'), 'crew_memberships', ['crew_id'], unique=False)
    op.create_index(op.f('ix_crew_memberships_user_id'), 'crew_memberships', ['user_id'], unique=False)
    op.alter_column('field_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_field_tasks_task_type'), 'field_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_field_tasks_work_package_id'), 'field_tasks', ['work_package_id'], unique=False)
    op.drop_index(op.f('ix_legacy_bridge_idempotency_created_at'), table_name='legacy_bridge_idempotency')
    op.drop_index(op.f('ix_legacy_identity_mappings_core_user'), table_name='legacy_identity_mappings')
    op.drop_constraint(op.f('legacy_identity_mappings_core_user_id_fkey'), 'legacy_identity_mappings', type_='foreignkey')
    op.drop_index(op.f('ix_marketing_brief_versions_brief_id'), table_name='marketing_creative_brief_versions')
    op.drop_index(op.f('ix_marketing_brief_versions_status'), table_name='marketing_creative_brief_versions')
    op.create_index(op.f('ix_marketing_creative_brief_versions_brief_id'), 'marketing_creative_brief_versions', ['brief_id'], unique=False)
    op.create_index(op.f('ix_marketing_creative_brief_versions_status'), 'marketing_creative_brief_versions', ['status'], unique=False)
    op.alter_column('order_deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_deliveries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_order_deliveries_order_id'), table_name='order_deliveries')
    op.create_index(op.f('ix_order_deliveries_commerce_order_id'), 'order_deliveries', ['commerce_order_id'], unique=False)
    op.create_index(op.f('ix_order_deliveries_legacy_delivery_id'), 'order_deliveries', ['legacy_delivery_id'], unique=False)
    op.create_index(op.f('ix_order_deliveries_tracking_number'), 'order_deliveries', ['tracking_number'], unique=False)
    op.alter_column('order_disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_disputes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_order_disputes_legacy'), table_name='order_disputes')
    op.drop_index(op.f('ix_order_disputes_order_id'), table_name='order_disputes')
    op.create_index(op.f('ix_order_disputes_commerce_order_id'), 'order_disputes', ['commerce_order_id'], unique=False)
    op.create_unique_constraint(None, 'order_disputes', ['legacy_dispute_id'])
    op.alter_column('partner_crews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_crews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_partner_crews_partner_company_id'), 'partner_crews', ['partner_company_id'], unique=False)
    op.alter_column('portal_grants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portal_grants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_portal_grants_portal_key'), 'portal_grants', ['portal_key'], unique=False)
    op.create_index(op.f('ix_portal_grants_workspace_id'), 'portal_grants', ['workspace_id'], unique=False)
    op.alter_column('portal_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portal_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_portal_notifications_user_status'), table_name='portal_notifications')
    op.create_index(op.f('ix_portal_notifications_aggregate_id'), 'portal_notifications', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_portal_notifications_domain'), 'portal_notifications', ['domain'], unique=False)
    op.create_index(op.f('ix_portal_notifications_event_type'), 'portal_notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_portal_notifications_portal_key'), 'portal_notifications', ['portal_key'], unique=False)
    op.create_index(op.f('ix_portal_notifications_status'), 'portal_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_portal_notifications_user_id'), 'portal_notifications', ['user_id'], unique=False)
    op.alter_column('procurement_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('procurement_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_procurement_requests_legacy'), table_name='procurement_requests')
    op.create_index(op.f('ix_procurement_requests_buyer_company_id'), 'procurement_requests', ['buyer_company_id'], unique=False)
    op.create_index(op.f('ix_procurement_requests_lead_id'), 'procurement_requests', ['lead_id'], unique=False)
    op.create_index(op.f('ix_procurement_requests_portal_key'), 'procurement_requests', ['portal_key'], unique=False)
    op.create_unique_constraint(None, 'procurement_requests', ['legacy_request_id'])
    op.alter_column('risk_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_risk_flags_subject'), table_name='risk_flags')
    op.create_index(op.f('ix_risk_flags_company_id'), 'risk_flags', ['company_id'], unique=False)
    op.create_index(op.f('ix_risk_flags_subject_id'), 'risk_flags', ['subject_id'], unique=False)
    op.create_index(op.f('ix_risk_flags_subject_type'), 'risk_flags', ['subject_type'], unique=False)
    op.alter_column('supplier_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_supplier_listings_legacy_catalog_item_id'), 'supplier_listings', ['legacy_catalog_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_listings_region_id'), 'supplier_listings', ['region_id'], unique=False)
    op.create_index(op.f('ix_supplier_listings_status'), 'supplier_listings', ['status'], unique=False)
    op.alter_column('supplier_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_supplier_offers_legacy_offer_id'), 'supplier_offers', ['legacy_offer_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_procurement_request_id'), 'supplier_offers', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_supplier_offers_status'), 'supplier_offers', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_offers_supplier_company_id'), 'supplier_offers', ['supplier_company_id'], unique=False)
    op.alter_column('task_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_task_assignments_assignee'), table_name='task_assignments')
    op.create_index(op.f('ix_task_assignments_assignee_user_id'), 'task_assignments', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_field_task_id'), 'task_assignments', ['field_task_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_status'), 'task_assignments', ['status'], unique=False)
    op.alter_column('task_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_evidence', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_task_evidence_field_task_id'), 'task_evidence', ['field_task_id'], unique=False)
    op.alter_column('trade_category_schemas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_category_schemas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_transaction_reviews_order'), table_name='transaction_reviews')
    op.create_index(op.f('ix_transaction_reviews_commerce_order_id'), 'transaction_reviews', ['commerce_order_id'], unique=False)
    op.create_index(op.f('ix_transaction_reviews_reviewer_user_id'), 'transaction_reviews', ['reviewer_user_id'], unique=False)
    op.create_index(op.f('ix_transaction_reviews_status'), 'transaction_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_transaction_reviews_supplier_company_id'), 'transaction_reviews', ['supplier_company_id'], unique=False)
    op.alter_column('trust_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trust_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_trust_profiles_company'), table_name='trust_profiles')
    op.create_index(op.f('ix_trust_profiles_company_id'), 'trust_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_trust_profiles_portal_key'), 'trust_profiles', ['portal_key'], unique=False)
    op.alter_column('work_packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_work_packages_project_id'), 'work_packages', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_packages_workspace_id'), 'work_packages', ['workspace_id'], unique=False)
    op.alter_column('workspace_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_workspace_memberships_membership_type'), 'workspace_memberships', ['membership_type'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_membership_type'), table_name='workspace_memberships')
    op.alter_column('workspace_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_work_packages_workspace_id'), table_name='work_packages')
    op.drop_index(op.f('ix_work_packages_project_id'), table_name='work_packages')
    op.alter_column('work_packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_trust_profiles_portal_key'), table_name='trust_profiles')
    op.drop_index(op.f('ix_trust_profiles_company_id'), table_name='trust_profiles')
    op.create_index(op.f('ix_trust_profiles_company'), 'trust_profiles', ['company_id'], unique=False)
    op.alter_column('trust_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trust_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_transaction_reviews_supplier_company_id'), table_name='transaction_reviews')
    op.drop_index(op.f('ix_transaction_reviews_status'), table_name='transaction_reviews')
    op.drop_index(op.f('ix_transaction_reviews_reviewer_user_id'), table_name='transaction_reviews')
    op.drop_index(op.f('ix_transaction_reviews_commerce_order_id'), table_name='transaction_reviews')
    op.create_index(op.f('ix_transaction_reviews_order'), 'transaction_reviews', ['commerce_order_id'], unique=False)
    op.alter_column('transaction_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transaction_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_category_schemas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trade_category_schemas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_task_evidence_field_task_id'), table_name='task_evidence')
    op.alter_column('task_evidence', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_task_assignments_status'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_field_task_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_assignee_user_id'), table_name='task_assignments')
    op.create_index(op.f('ix_task_assignments_assignee'), 'task_assignments', ['assignee_user_id'], unique=False)
    op.alter_column('task_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_supplier_offers_supplier_company_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_status'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_procurement_request_id'), table_name='supplier_offers')
    op.drop_index(op.f('ix_supplier_offers_legacy_offer_id'), table_name='supplier_offers')
    op.alter_column('supplier_offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_supplier_listings_status'), table_name='supplier_listings')
    op.drop_index(op.f('ix_supplier_listings_region_id'), table_name='supplier_listings')
    op.drop_index(op.f('ix_supplier_listings_legacy_catalog_item_id'), table_name='supplier_listings')
    op.alter_column('supplier_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_risk_flags_subject_type'), table_name='risk_flags')
    op.drop_index(op.f('ix_risk_flags_subject_id'), table_name='risk_flags')
    op.drop_index(op.f('ix_risk_flags_company_id'), table_name='risk_flags')
    op.create_index(op.f('ix_risk_flags_subject'), 'risk_flags', ['subject_type', 'subject_id'], unique=False)
    op.alter_column('risk_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'procurement_requests', type_='unique')
    op.drop_index(op.f('ix_procurement_requests_portal_key'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_lead_id'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_buyer_company_id'), table_name='procurement_requests')
    op.create_index(op.f('ix_procurement_requests_legacy'), 'procurement_requests', ['legacy_request_id'], unique=True)
    op.alter_column('procurement_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('procurement_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_portal_notifications_user_id'), table_name='portal_notifications')
    op.drop_index(op.f('ix_portal_notifications_status'), table_name='portal_notifications')
    op.drop_index(op.f('ix_portal_notifications_portal_key'), table_name='portal_notifications')
    op.drop_index(op.f('ix_portal_notifications_event_type'), table_name='portal_notifications')
    op.drop_index(op.f('ix_portal_notifications_domain'), table_name='portal_notifications')
    op.drop_index(op.f('ix_portal_notifications_aggregate_id'), table_name='portal_notifications')
    op.create_index(op.f('ix_portal_notifications_user_status'), 'portal_notifications', ['user_id', 'status'], unique=False)
    op.alter_column('portal_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portal_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_portal_grants_workspace_id'), table_name='portal_grants')
    op.drop_index(op.f('ix_portal_grants_portal_key'), table_name='portal_grants')
    op.alter_column('portal_grants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portal_grants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_partner_crews_partner_company_id'), table_name='partner_crews')
    op.alter_column('partner_crews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('partner_crews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'order_disputes', type_='unique')
    op.drop_index(op.f('ix_order_disputes_commerce_order_id'), table_name='order_disputes')
    op.create_index(op.f('ix_order_disputes_order_id'), 'order_disputes', ['commerce_order_id'], unique=False)
    op.create_index(op.f('ix_order_disputes_legacy'), 'order_disputes', ['legacy_dispute_id'], unique=True)
    op.alter_column('order_disputes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_order_deliveries_tracking_number'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_legacy_delivery_id'), table_name='order_deliveries')
    op.drop_index(op.f('ix_order_deliveries_commerce_order_id'), table_name='order_deliveries')
    op.create_index(op.f('ix_order_deliveries_order_id'), 'order_deliveries', ['commerce_order_id'], unique=False)
    op.alter_column('order_deliveries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_marketing_creative_brief_versions_status'), table_name='marketing_creative_brief_versions')
    op.drop_index(op.f('ix_marketing_creative_brief_versions_brief_id'), table_name='marketing_creative_brief_versions')
    op.create_index(op.f('ix_marketing_brief_versions_status'), 'marketing_creative_brief_versions', ['status'], unique=False)
    op.create_index(op.f('ix_marketing_brief_versions_brief_id'), 'marketing_creative_brief_versions', ['brief_id'], unique=False)
    op.create_foreign_key(op.f('legacy_identity_mappings_core_user_id_fkey'), 'legacy_identity_mappings', 'users', ['core_user_id'], ['id'])
    op.create_index(op.f('ix_legacy_identity_mappings_core_user'), 'legacy_identity_mappings', ['core_user_id'], unique=False)
    op.create_index(op.f('ix_legacy_bridge_idempotency_created_at'), 'legacy_bridge_idempotency', ['created_at'], unique=False)
    op.drop_index(op.f('ix_field_tasks_work_package_id'), table_name='field_tasks')
    op.drop_index(op.f('ix_field_tasks_task_type'), table_name='field_tasks')
    op.alter_column('field_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_crew_memberships_user_id'), table_name='crew_memberships')
    op.drop_index(op.f('ix_crew_memberships_crew_id'), table_name='crew_memberships')
    op.alter_column('crew_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crew_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_threads_supplier_company_id'), table_name='commerce_threads')
    op.drop_index(op.f('ix_commerce_threads_status'), table_name='commerce_threads')
    op.drop_index(op.f('ix_commerce_threads_procurement_request_id'), table_name='commerce_threads')
    op.drop_index(op.f('ix_commerce_threads_portal_key'), table_name='commerce_threads')
    op.drop_index(op.f('ix_commerce_threads_commerce_order_id'), table_name='commerce_threads')
    op.drop_index(op.f('ix_commerce_threads_buyer_company_id'), table_name='commerce_threads')
    op.create_index(op.f('ix_commerce_threads_request'), 'commerce_threads', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_commerce_threads_order'), 'commerce_threads', ['commerce_order_id'], unique=False)
    op.alter_column('commerce_threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_settlements_psp_settlement_ref'), table_name='commerce_settlements')
    op.drop_index(op.f('ix_commerce_settlements_payment_intent_id'), table_name='commerce_settlements')
    op.drop_index(op.f('ix_commerce_settlements_milestone_id'), table_name='commerce_settlements')
    op.drop_index(op.f('ix_commerce_settlements_commerce_order_id'), table_name='commerce_settlements')
    op.create_index(op.f('ix_commerce_settlements_order'), 'commerce_settlements', ['commerce_order_id'], unique=False)
    op.alter_column('commerce_settlements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_reconciliation_runs_status'), table_name='commerce_reconciliation_runs')
    op.create_index(op.f('ix_commerce_recon_runs_status'), 'commerce_reconciliation_runs', ['status'], unique=False)
    op.alter_column('commerce_reconciliation_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_reconciliation_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_payment_intents_payment_plan_id'), table_name='commerce_payment_intents')
    op.alter_column('commerce_payment_intents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_payment_intents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'commerce_orders', type_='unique')
    op.drop_index(op.f('ix_commerce_orders_status'), table_name='commerce_orders')
    op.drop_index(op.f('ix_commerce_orders_procurement_request_id'), table_name='commerce_orders')
    op.create_index(op.f('ix_commerce_orders_legacy'), 'commerce_orders', ['legacy_order_id'], unique=True)
    op.alter_column('commerce_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commerce_messages_thread_id'), table_name='commerce_messages')
    op.create_index(op.f('ix_commerce_messages_thread'), 'commerce_messages', ['thread_id'], unique=False)
    op.alter_column('commerce_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commerce_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_order_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_company_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_order_shipping_status'), table_name='order_shipping')
    op.drop_index(op.f('ix_order_shipping_order_id'), table_name='order_shipping')
    op.drop_table('order_shipping')
    op.drop_index(op.f('ix_escrow_transactions_status'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_order_id'), table_name='escrow_transactions')
    op.drop_table('escrow_transactions')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_tx_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_owner_user_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_deposits_wallet_id'), table_name='wallet_deposits')
    op.drop_index(op.f('ix_wallet_deposits_tx_hash'), table_name='wallet_deposits')
    op.drop_index(op.f('ix_wallet_deposits_status'), table_name='wallet_deposits')
    op.drop_index(op.f('ix_wallet_deposits_owner_user_id'), table_name='wallet_deposits')
    op.drop_table('wallet_deposits')
    op.drop_index(op.f('ix_wallets_status'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_owner_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_currency'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_country_code'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_ad_campaigns_status'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_listing_id'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_company_id'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    op.drop_index(op.f('ix_shipping_rates_route_id'), table_name='shipping_rates')
    op.drop_table('shipping_rates')
    op.drop_index(op.f('ix_shipping_routes_origin_country'), table_name='shipping_routes')
    op.drop_index(op.f('ix_shipping_routes_dest_country'), table_name='shipping_routes')
    op.drop_table('shipping_routes')
    # ### end Alembic commands ###
