import {
  Button,
  Cell,
  CellGroup,
  Field,
  Form,
  NavBar,
  Tabbar,
  TabbarItem,
  Tab,
  Tabs,
  Tag,
  Badge,
  Icon,
  Image as VanImage,
  List,
  PullRefresh,
  Popup,
  Picker,
  DatePicker,
  TimePicker,
  Stepper,
  Slider,
  Switch,
  Checkbox,
  CheckboxGroup,
  Radio,
  RadioGroup,
  Uploader,
  Loading,
  Overlay,
  Toast,
  Dialog,
  ActionSheet,
  SwipeCell,
  Swipe,
  SwipeItem,
  Step,
  Steps,
  Empty,
  Divider,
  NoticeBar,
  DropdownMenu,
  DropdownItem,
  Search,
  Skeleton,
  SkeletonTitle,
  SkeletonImage,
  SkeletonAvatar,
  SkeletonParagraph,
  showToast,
  showDialog,
  showConfirmDialog,
  showLoadingToast,
  closeToast,
} from "vant";

export default defineNuxtPlugin((nuxtApp) => {
  const components = [
    Button, Cell, CellGroup, Field, Form, NavBar, Tabbar, TabbarItem,
    Tab, Tabs, Tag, Badge, Icon, VanImage, List, PullRefresh, Popup,
    Picker, DatePicker, TimePicker, Stepper, Slider, Switch, Checkbox,
    CheckboxGroup, Radio, RadioGroup, Uploader, Loading, Overlay,
    Toast, Dialog, ActionSheet, SwipeCell, Swipe, SwipeItem, Step,
    Steps, Empty, Divider, NoticeBar, DropdownMenu, DropdownItem,
    Search, Skeleton, SkeletonTitle, SkeletonImage, SkeletonAvatar,
    SkeletonParagraph,
  ];

  components.forEach((c) => nuxtApp.vueApp.use(c));

  return {
    provide: {
      toast: showToast,
      dialog: showDialog,
      confirmDialog: showConfirmDialog,
      loadingToast: showLoadingToast,
      closeToast,
    },
  };
});
