/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./composables/**/*.{js,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./stores/**/*.{js,ts}",
    "./utils/**/*.{js,ts}",
    "./app.config.{js,ts}",
    "./app.vue",
    "./error.vue",
    "./node_modules/@nuxt/ui/dist/**/*.{js,mjs,ts,vue}",
    "./node_modules/@nuxt/ui/dist/runtime/**/*.{vue,js,mjs,ts}",
    "./node_modules/@nuxt/ui/dist/runtime/ui.config/**/*.{js,mjs,ts}",
    "./node_modules/@nuxt/ui/dist/runtime/components/**/*.{vue,js,mjs,ts}",
    "./.nuxt/**/*.{vue,js,mjs,ts}",
  ],
  safelist: [
    "absolute",
    "relative",
    "inset-y-0",
    "start-0",
    "end-0",
    "left-0",
    "left-3",
    "left-1/2",
    "right-0",
    "right-3",
    "bottom-0",
    "top-0",
    "top-1/2",
    "translate-x-1/2",
    "-translate-y-1/2",
    "pointer-events-none",
    "flex",
    "items-center",
    "justify-center",
    "ps-8",
    "ps-9",
    "ps-10",
    "ps-11",
    "ps-12",
    "ps-7",
    "pe-8",
    "pe-9",
    "pe-10",
    "pe-11",
    "pe-12",
    "pe-7",
    "pl-8",
    "pl-9",
    "pl-10",
    "pl-11",
    "pl-12",
    "pr-8",
    "pr-9",
    "pr-10",
    "pr-11",
    "pr-12",
    "h-4",
    "h-5",
    "h-6",
    "h-7",
    "w-4",
    "w-5",
    "w-6",
    "w-7",
    "h-0.5",
    "h-1",
    "h-2",
    "h-3",
    "h-4",
    "h-5",
    "h-px",
    "form-input",
    "form-select",
    "form-checkbox",
    "ui-input-leading",
    "ui-input-trailing",
    "ui-select-leading",
    "ui-range-thumb",
    "ui-range-track",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#4f46e5",
          700: "#4338ca",
          800: "#3730a3",
          900: "#312e81",
          950: "#1e1b4b",
        },
        success: "#16a34a",
        warning: "#d97706",
        danger: "#dc2626",
        slate: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
        },
      },
      spacing: {
        "safe-bottom": "var(--safe-area-bottom)",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        card: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "card-hover": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        bottom: "0 -2px 8px 0 rgb(0 0 0 / 0.08)",
      },
    },
  },
  plugins: [],
};
