import { defineStore } from 'pinia'

type LanguageCode = 'EN' | 'ZH' | 'JA' | 'ES' | 'TL' | 'KO' | 'TH' | 'VI' | 'ID' | 'AR'

interface SelectOption {
  code: string
  label: string
}

interface AppState {
  language: LanguageCode
  currency: string
  regionCountry: string
  enabledCurrencies: string[]
  paymentRegionConfig: Record<string, any> | null
}

const messages: Record<LanguageCode, Record<string, string>> = {
  EN: {
    'nav.how': 'How it works',
    'nav.categories': 'Categories',
    'nav.suppliers': 'For Suppliers',
    'nav.trust': 'Trust & Safety',
    'auth.login': 'Login',
    'categories.title': 'Browse Categories',
    'categories.subtitle': 'Find verified suppliers across {count}+ industries worldwide.',
    'categories.browse': 'Browse',
    'categories.empty': 'No categories found.',
    'categories.ctaTitle': "Can't find what you need?",
    'categories.ctaDesc': 'Post a purchase request and let verified suppliers come to you.',
    'action.postRequest': 'Post Request',
    'action.newRequest': 'New Request',
    'action.browseMarketplace': 'Browse Marketplace',
    'action.findSuppliers': 'Find Suppliers',
    'action.viewAll': 'View all',
    'action.viewAllMessages': 'View all messages',
    'action.compareOffers': 'Compare Offers',
    'action.viewPublicProfile': 'View Public Profile',
    'action.viewPings': 'View Pings',
    'action.quoteNow': 'Quote Now',
    'action.uploadProof': 'Upload Proof',
    'action.reply': 'Reply',
    'project.loading': 'Loading...',
    'project.loadingProject': 'Loading project...',
    'project.forge': 'AI Project Forge',
    'project.forgeDesc': 'Conversationally collect project details, optionally attach files, generate an editable demand form, then match catalog items and supplier quotes.',
    'project.progress': 'Progress',
    'project.refresh': 'Refresh',
    'project.aiAnalyze': 'AI Analyze',
    'project.refreshPrices': 'Refresh Prices',
    'project.freezeForm': 'Freeze Form',
    'project.publishItems': 'Publish {count} Items',
    'project.langgraphIntake': 'LangGraph Intake',
    'project.collectStep': 'Collect project information step by step',
    'project.chatGoalTitle': 'Tell AI your project goal first',
    'project.chatGoalExample': 'Example: I want to build a 200 sqm villa in Cebu, prefer premium materials, and need estimates for rebar, cement, PVC, and lighting.',
    'project.chatPlaceholder': 'Describe the project, answer AI follow-ups, or explain key points from uploaded files... (Ctrl+Enter to send)',
    'project.attachFiles': 'Attach files',
    'project.send': 'Send',
    'project.proceed': 'Proceed',
    'project.uploading': 'Uploading...',
    'project.providerMissing': 'AI provider is not configured. Please ask an admin to configure Admin → Integrations → AI Provider and enable AI Project Forge.',
    'project.oldDeepseekEndpoint': 'This failed run used an old DeepSeek endpoint. The backend now uses the exact Admin AI Provider Base URL. Please retry analysis.',
    'project.status.done': 'Done',
    'project.status.active': 'Active',
    'project.status.pending': 'Pending',
    'project.stage.goal': 'Goal',
    'project.stage.coreNeed': 'Core need',
    'project.stage.metrics': 'Metrics',
    'project.stage.indicators': 'Indicators',
    'project.stage.files': 'Files',
    'project.stage.optional': 'Optional',
    'project.stage.demandModel': 'Demand Model',
    'project.stage.lineItems': 'Line items',
    'project.stage.compare': 'Compare',
    'project.stage.pricing': 'Pricing',
    'project.stage.finalReport': 'Final Report',
    'project.stage.freeze': 'Freeze',
    'project.preview.coreNeed': 'Core Need',
    'project.preview.waitGoal': 'Waiting for the user to describe the project goal',
    'project.preview.projectMetrics': 'Project Metrics',
    'project.preview.indicatorsMissing': '{count} indicators missing',
    'project.preview.indicatorsCollected': '{count} indicators collected',
    'project.preview.supportingFiles': 'Supporting Files',
    'project.preview.filesAttached': '{count} files attached for optional text/multimodal extraction',
    'project.preview.demandForm': 'Demand Form',
    'project.preview.itemsIncluded': '{items} items, {included} included in estimate',
    'project.preview.matchingQuotes': 'Matching & Quotes',
    'project.preview.comparisonIssues': '{groups} comparison groups, {issues} issues to review',
    'project.preview.frozenReady': 'Frozen and ready to publish',
    'project.preview.waitFreeze': 'Waiting for user review and freeze',
    'layout.settings': 'Settings',
    'layout.catalogRules': 'Catalog & Rules',
    'layout.business': 'Business',
    'layout.searchBuyer': 'Search requests, orders...',
    'layout.buyerAccount': 'Buyer Account',
    'layout.companyProfile': 'Company Profile',
    'layout.team': 'Team',
    'layout.logout': 'Log out',
    'layout.supplierBadge': 'SUPPLIER',
    'layout.supplierPortal': 'Supplier Portal',
    'layout.onlinePings': 'Online & Receiving Pings',
    'layout.verifiedSupplier': 'Verified Supplier',
    'layout.myBusiness': 'My Business',
    'layout.shoppingFirst': 'Shopping First',
    'layout.marketplaceShortcutDesc': 'Keep sourcing one click away from every buyer page.',
    'buyer.nav.dashboard': 'Dashboard',
    'buyer.nav.marketplace': 'Marketplace',
    'buyer.nav.requests': 'My Requests',
    'buyer.nav.orders': 'Orders',
    'buyer.nav.messages': 'Messages',
    'buyer.nav.disputes': 'Dispute Center',
    'buyer.nav.idealList': 'Ideal List',
    'buyer.nav.settings': 'Account Settings',
    'buyer.nav.wallet': 'Wallet & Escrow',
    'supplier.nav.dashboard': 'Dashboard',
    'supplier.nav.inbox': 'Ping Inbox',
    'supplier.nav.offers': 'My Offers',
    'supplier.nav.orders': 'Orders & Delivery',
    'supplier.nav.messages': 'Messages',
    'supplier.nav.catalog': 'My Catalog',
    'supplier.nav.triggers': 'Matching Triggers',
    'supplier.nav.payouts': 'Payout Settings',
    'supplier.nav.reviews': 'Reviews & Trust',
    'supplier.nav.settings': 'Settings',
    'buyer.dashboard.title': 'Buyer Dashboard',
    'buyer.dashboard.activeRequests': 'Active Requests',
    'buyer.dashboard.offersReceived': 'Offers Received',
    'buyer.dashboard.ordersProgress': 'Orders in Progress',
    'buyer.dashboard.escrowHeld': 'Escrow Held',
    'buyer.dashboard.trustTitle': 'Buyer Trust Profile',
    'buyer.dashboard.trustDesc': 'Based on profile completion, deal completion, deposit and platform risk signals.',
    'buyer.dashboard.shopTitle': 'Back to sourcing',
    'buyer.dashboard.shopDesc': 'Browse the product waterfall, filter by category and region, then buy now or request quotes without losing your dashboard context.',
    'buyer.dashboard.shopPrimary': 'Open Marketplace',
    'buyer.dashboard.shopSecondary': 'Find trusted suppliers',
    'buyer.dashboard.shopStatProducts': 'Live products',
    'buyer.dashboard.shopStatModes': 'B2B + B2C',
    'buyer.dashboard.shopStatRank': 'Rank by trust, cost, distance',
    'trust.score': 'Score',
    'trust.dealRate': 'Deal Rate',
    'trust.profile': 'Profile',
    'trust.deposit': 'Deposit',
    'trust.disputes': 'Disputes',
    'trust.tier.BRONZE': 'Bronze',
    'trust.tier.SILVER': 'Silver',
    'trust.tier.GOLD': 'Gold',
    'trust.tier.PLATINUM': 'Platinum',
    'trust.tier.DIAMOND': 'Diamond',
    'buyer.dashboard.recentMessages': 'Recent Messages',
    'buyer.dashboard.messagePreview': 'Can we deliver this on Tuesday instead?',
    'buyer.dashboard.recommended': 'Recommended for You',
    'buyer.table.requestTitle': 'Request Title',
    'buyer.table.budget': 'Budget',
    'buyer.table.status': 'Status',
    'buyer.table.offers': 'Offers',
    'buyer.table.actions': 'Actions',
    'buyer.status.receivingOffers': 'Receiving Offers',
    'buyer.status.reviewing': 'Reviewing',
    'supplier.dashboard.title': 'Supplier Dashboard',
    'supplier.dashboard.subtitle': "Here's what's happening with your business today.",
    'supplier.dashboard.newPings': 'New Pings',
    'supplier.dashboard.activeOffers': 'Active Offers',
    'supplier.dashboard.awardedOrders': 'Awarded Orders',
    'supplier.dashboard.pendingDelivery': 'Pending Delivery',
    'supplier.dashboard.escrowPayout': 'Escrow Pending Payout',
    'supplier.dashboard.responseSla': 'Response Time SLA',
    'supplier.dashboard.rating': 'Rating',
    'supplier.dashboard.disputeRate': 'Dispute Rate',
    'supplier.dashboard.recentPings': 'Recent Pings',
    'supplier.dashboard.actionRequired': 'Action Required',
    'supplier.dashboard.away': 'away',
    'supplier.dashboard.preFunded': 'Pre-funded',
    'supplier.dashboard.budget': 'Budget',
    'supplier.dashboard.deliveryProof': 'Upload Delivery Proof',
    'supplier.dashboard.deliveryProofDesc': 'Order #ORD-99120 has been marked as shipped. Upload proof of delivery to allow the buyer to release funds.',
    'supplier.dashboard.unreadMessage': 'Unread Message from Buyer',
    'supplier.dashboard.unreadMessageDesc': 'Regarding Offer #OFF-4412 for "Marine Engine Parts".',
    'footer.buyers': 'Buyers',
    'footer.suppliers': 'Suppliers',
    'footer.settings': 'Settings',
    'footer.postRequest': 'Post a Request',
    'footer.escrow': 'Escrow Protection',
    'footer.becomeSupplier': 'Become a Supplier',
    'footer.pricing': 'Fees & Pricing',
    'footer.verification': 'Supplier Verification',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
  },
  ZH: {
    'nav.how': '如何运作',
    'nav.categories': '品类',
    'nav.suppliers': '供应商入驻',
    'nav.trust': '信任与安全',
    'auth.login': '登录',
    'categories.title': '浏览品类',
    'categories.subtitle': '在全球 {count}+ 个行业中寻找已认证供应商。',
    'categories.browse': '浏览',
    'categories.empty': '暂无品类。',
    'categories.ctaTitle': '没有找到需要的商品？',
    'categories.ctaDesc': '发布采购需求，让已认证供应商主动给你报价。',
    'action.postRequest': '发布需求',
    'action.newRequest': '新建需求',
    'action.browseMarketplace': '浏览市场',
    'action.findSuppliers': '寻找供应商',
    'action.viewAll': '查看全部',
    'action.viewAllMessages': '查看全部消息',
    'action.compareOffers': '比较报价',
    'action.viewPublicProfile': '查看公开主页',
    'action.viewPings': '查看匹配需求',
    'action.quoteNow': '立即报价',
    'action.uploadProof': '上传交付凭证',
    'action.reply': '回复',
    'project.loading': '加载中...',
    'project.loadingProject': '项目加载中...',
    'project.forge': 'AI Project Forge',
    'project.forgeDesc': '通过对话收集项目资料，可选上传文件，生成可编辑需求表单，再匹配商品和供应商报价。',
    'project.progress': '进度',
    'project.refresh': '刷新',
    'project.aiAnalyze': 'AI 分析',
    'project.refreshPrices': '刷新价格',
    'project.freezeForm': '冻结表单',
    'project.publishItems': '发布 {count} 项',
    'project.langgraphIntake': 'LangGraph 信息收集',
    'project.collectStep': '逐步收集项目资料',
    'project.chatGoalTitle': '先告诉 AI 你的项目目标',
    'project.chatGoalExample': '例如：我要在 Cebu 建 200 平米别墅，偏高端，需要钢筋、水泥、PVC、灯具等预估。',
    'project.chatPlaceholder': '描述项目、回答 AI 追问，或说明上传文件中的重点...（Ctrl+Enter 发送）',
    'project.attachFiles': '上传文件',
    'project.send': '发送',
    'project.proceed': '进入下一步',
    'project.uploading': '上传中...',
    'project.providerMissing': 'AI Provider 未配置。请管理员到 Admin → Integrations → AI Provider 配置并启用 AI Project Forge。',
    'project.oldDeepseekEndpoint': '这次失败运行使用了旧的 DeepSeek endpoint。后端现在会使用 Admin AI Provider 中配置的精确 Base URL，请重新分析。',
    'project.status.done': '完成',
    'project.status.active': '进行中',
    'project.status.pending': '待处理',
    'project.stage.goal': '定位',
    'project.stage.coreNeed': '核心需求',
    'project.stage.metrics': '指标',
    'project.stage.indicators': '项目指标',
    'project.stage.files': '资料',
    'project.stage.optional': '可选',
    'project.stage.demandModel': '需求模型',
    'project.stage.lineItems': '需求项',
    'project.stage.compare': '比价',
    'project.stage.pricing': '价格',
    'project.stage.finalReport': '最终报表',
    'project.stage.freeze': '冻结',
    'project.preview.coreNeed': '核心需求',
    'project.preview.waitGoal': '等待用户描述项目目标',
    'project.preview.projectMetrics': '项目指标',
    'project.preview.indicatorsMissing': '缺少 {count} 个指标',
    'project.preview.indicatorsCollected': '已收集 {count} 个指标',
    'project.preview.supportingFiles': '辅助资料',
    'project.preview.filesAttached': '已上传 {count} 个文件，可用于文本/多模态抽取',
    'project.preview.demandForm': '需求表格',
    'project.preview.itemsIncluded': '{items} 个项目，{included} 个参与估算',
    'project.preview.matchingQuotes': '匹配与报价',
    'project.preview.comparisonIssues': '{groups} 个比价组，{issues} 个问题待确认',
    'project.preview.frozenReady': '已冻结，可发布',
    'project.preview.waitFreeze': '等待用户确认并冻结',
    'layout.settings': '设置',
    'layout.catalogRules': '目录与规则',
    'layout.business': '业务',
    'layout.searchBuyer': '搜索需求、订单...',
    'layout.buyerAccount': '买家账户',
    'layout.companyProfile': '企业资料',
    'layout.team': '团队',
    'layout.logout': '退出登录',
    'layout.supplierBadge': '供应商',
    'layout.supplierPortal': '供应商工作台',
    'layout.onlinePings': '在线接收匹配需求',
    'layout.verifiedSupplier': '已认证供应商',
    'layout.myBusiness': '我的企业',
    'layout.shoppingFirst': '采购优先',
    'layout.marketplaceShortcutDesc': '在每个买家页面都能一键回到商品瀑布流。',
    'buyer.nav.dashboard': '买家仪表盘',
    'buyer.nav.marketplace': '采购市场',
    'buyer.nav.requests': '我的需求',
    'buyer.nav.orders': '订单',
    'buyer.nav.messages': '消息',
    'buyer.nav.disputes': '争议中心',
    'buyer.nav.idealList': '理想清单',
    'buyer.nav.settings': '账户设置',
    'buyer.nav.wallet': '钱包与托管',
    'supplier.nav.dashboard': '供应商仪表盘',
    'supplier.nav.inbox': '匹配需求',
    'supplier.nav.offers': '我的报价',
    'supplier.nav.orders': '订单与交付',
    'supplier.nav.messages': '消息',
    'supplier.nav.catalog': '商品目录',
    'supplier.nav.triggers': '匹配规则',
    'supplier.nav.payouts': '收款设置',
    'supplier.nav.reviews': '评价与信用',
    'supplier.nav.settings': '设置',
    'buyer.dashboard.title': '买家仪表盘',
    'buyer.dashboard.activeRequests': '进行中的需求',
    'buyer.dashboard.offersReceived': '收到的报价',
    'buyer.dashboard.ordersProgress': '进行中的订单',
    'buyer.dashboard.escrowHeld': '托管资金',
    'buyer.dashboard.trustTitle': '买家信用档案',
    'buyer.dashboard.trustDesc': '基于资料完整度、成交率、押金和平台风控信号计算。',
    'buyer.dashboard.shopTitle': '回到采购市场',
    'buyer.dashboard.shopDesc': '浏览商品瀑布流，按品类和区域筛选，然后直接购买或发起报价，不需要离开买家工作流。',
    'buyer.dashboard.shopPrimary': '打开采购市场',
    'buyer.dashboard.shopSecondary': '寻找可信供应商',
    'buyer.dashboard.shopStatProducts': '实时商品',
    'buyer.dashboard.shopStatModes': 'B2B + B2C',
    'buyer.dashboard.shopStatRank': '按信用、成本、距离排序',
    'trust.score': '信誉值',
    'trust.dealRate': '成交率',
    'trust.profile': '资料完整度',
    'trust.deposit': '押金',
    'trust.disputes': '争议率',
    'trust.tier.BRONZE': '青铜',
    'trust.tier.SILVER': '白银',
    'trust.tier.GOLD': '黄金',
    'trust.tier.PLATINUM': '铂金',
    'trust.tier.DIAMOND': '钻石',
    'buyer.dashboard.recentMessages': '最近消息',
    'buyer.dashboard.messagePreview': '我们可以改到周二交付吗？',
    'buyer.dashboard.recommended': '为你推荐',
    'buyer.table.requestTitle': '需求标题',
    'buyer.table.budget': '预算',
    'buyer.table.status': '状态',
    'buyer.table.offers': '报价',
    'buyer.table.actions': '操作',
    'buyer.status.receivingOffers': '接收报价中',
    'buyer.status.reviewing': '审核中',
    'supplier.dashboard.title': '供应商仪表盘',
    'supplier.dashboard.subtitle': '这里展示今天和你业务相关的关键事项。',
    'supplier.dashboard.newPings': '新匹配需求',
    'supplier.dashboard.activeOffers': '有效报价',
    'supplier.dashboard.awardedOrders': '已中标订单',
    'supplier.dashboard.pendingDelivery': '待交付',
    'supplier.dashboard.escrowPayout': '待结算托管',
    'supplier.dashboard.responseSla': '响应时效',
    'supplier.dashboard.rating': '评分',
    'supplier.dashboard.disputeRate': '争议率',
    'supplier.dashboard.recentPings': '最近匹配需求',
    'supplier.dashboard.actionRequired': '待处理事项',
    'supplier.dashboard.away': '距离',
    'supplier.dashboard.preFunded': '已预存资金',
    'supplier.dashboard.budget': '预算',
    'supplier.dashboard.deliveryProof': '上传交付凭证',
    'supplier.dashboard.deliveryProofDesc': '订单 #ORD-99120 已标记为发货。请上传交付凭证，便于买家释放托管资金。',
    'supplier.dashboard.unreadMessage': '买家未读消息',
    'supplier.dashboard.unreadMessageDesc': '关于 "Marine Engine Parts" 的报价 #OFF-4412。',
    'footer.buyers': '买家',
    'footer.suppliers': '供应商',
    'footer.settings': '设置',
    'footer.postRequest': '发布需求',
    'footer.escrow': '托管保障',
    'footer.becomeSupplier': '成为供应商',
    'footer.pricing': '费用与定价',
    'footer.verification': '供应商认证',
    'footer.terms': '条款',
    'footer.privacy': '隐私',
  },
  JA: {
    'nav.how': '使い方',
    'nav.categories': 'カテゴリ',
    'nav.suppliers': 'サプライヤー向け',
    'nav.trust': '信頼と安全',
    'auth.login': 'ログイン',
    'action.postRequest': '依頼を投稿',
    'action.newRequest': '新しい依頼',
    'action.viewAll': 'すべて表示',
    'action.viewAllMessages': 'すべてのメッセージを表示',
    'action.compareOffers': '見積もりを比較',
    'action.viewPublicProfile': '公開プロフィールを表示',
    'action.viewPings': 'マッチングを確認',
    'action.quoteNow': '今すぐ見積もり',
    'action.uploadProof': '証明書をアップロード',
    'action.reply': '返信',
    'layout.settings': '設定',
    'layout.catalogRules': 'カタログとルール',
    'layout.business': 'ビジネス',
    'layout.searchBuyer': '依頼・注文を検索...',
    'layout.buyerAccount': 'バイヤーアカウント',
    'layout.companyProfile': '会社プロフィール',
    'layout.team': 'チーム',
    'layout.logout': 'ログアウト',
    'layout.supplierBadge': 'サプライヤー',
    'layout.supplierPortal': 'サプライヤーポータル',
    'layout.onlinePings': 'オンライン・マッチング受信中',
    'layout.verifiedSupplier': '認証済みサプライヤー',
    'layout.myBusiness': '私のビジネス',
    'buyer.nav.dashboard': 'ダッシュボード',
    'buyer.nav.requests': '依頼一覧',
    'buyer.nav.orders': '注文',
    'buyer.nav.messages': 'メッセージ',
    'buyer.nav.disputes': '紛争センター',
    'buyer.nav.idealList': '希望リスト',
    'buyer.nav.settings': 'アカウント設定',
    'buyer.nav.wallet': '財布とエスクロー',
    'supplier.nav.dashboard': 'ダッシュボード',
    'supplier.nav.inbox': 'マッチング受信箱',
    'supplier.nav.offers': '見積もり一覧',
    'supplier.nav.orders': '注文と配送',
    'supplier.nav.messages': 'メッセージ',
    'supplier.nav.catalog': 'カタログ',
    'supplier.nav.triggers': 'マッチングルール',
    'supplier.nav.payouts': '支払い設定',
    'supplier.nav.reviews': 'レビューと信頼',
    'supplier.nav.settings': '設定',
    'buyer.dashboard.title': 'バイヤーダッシュボード',
    'buyer.dashboard.activeRequests': '進行中の依頼',
    'buyer.dashboard.offersReceived': '受信済み見積もり',
    'buyer.dashboard.ordersProgress': '進行中の注文',
    'buyer.dashboard.escrowHeld': 'エスクロー保管中',
    'buyer.dashboard.trustTitle': 'バイヤー信頼プロフィール',
    'buyer.dashboard.trustDesc': 'プロフィール完成度、成約率、保証金、プラットフォームリスクシグナルに基づいて算出。',
    'trust.score': 'スコア',
    'trust.dealRate': '成約率',
    'trust.profile': 'プロフィール',
    'trust.deposit': '保証金',
    'trust.disputes': '紛争',
    'trust.tier.BRONZE': 'ブロンズ',
    'trust.tier.SILVER': 'シルバー',
    'trust.tier.GOLD': 'ゴールド',
    'trust.tier.PLATINUM': 'プラチナ',
    'trust.tier.DIAMOND': 'ダイヤモンド',
    'buyer.dashboard.recentMessages': '最近のメッセージ',
    'buyer.dashboard.messagePreview': '火曜日に配達に変更できますか？',
    'buyer.dashboard.recommended': 'おすすめ',
    'buyer.table.requestTitle': '依頼タイトル',
    'buyer.table.budget': '予算',
    'buyer.table.status': 'ステータス',
    'buyer.table.offers': '見積もり',
    'buyer.table.actions': 'アクション',
    'buyer.status.receivingOffers': '見積もり受付中',
    'buyer.status.reviewing': '審査中',
    'supplier.dashboard.title': 'サプライヤーダッシュボード',
    'supplier.dashboard.subtitle': '今日のビジネス状況をご確認ください。',
    'supplier.dashboard.newPings': '新着マッチング',
    'supplier.dashboard.activeOffers': '有効な見積もり',
    'supplier.dashboard.awardedOrders': '受注済み注文',
    'supplier.dashboard.pendingDelivery': '配送待ち',
    'supplier.dashboard.escrowPayout': 'エスクロー精算待ち',
    'supplier.dashboard.responseSla': '応答時間SLA',
    'supplier.dashboard.rating': '評価',
    'supplier.dashboard.disputeRate': '紛争率',
    'supplier.dashboard.recentPings': '最近のマッチング',
    'supplier.dashboard.actionRequired': '要対応',
    'supplier.dashboard.away': '離れています',
    'supplier.dashboard.preFunded': '前払い済み',
    'supplier.dashboard.budget': '予算',
    'supplier.dashboard.deliveryProof': '配送証明をアップロード',
    'supplier.dashboard.deliveryProofDesc': '注文 #ORD-99120 が発送済みとしてマークされました。買い手が資金を解放できるよう配送証明をアップロードしてください。',
    'supplier.dashboard.unreadMessage': '買い手からの未読メッセージ',
    'supplier.dashboard.unreadMessageDesc': '"Marine Engine Parts" の見積もり #OFF-4412 について。',
    'footer.buyers': 'バイヤー',
    'footer.suppliers': 'サプライヤー',
    'footer.settings': '設定',
    'footer.postRequest': '依頼を投稿',
    'footer.escrow': 'エスクロー保護',
    'footer.becomeSupplier': 'サプライヤー登録',
    'footer.pricing': '料金',
    'footer.verification': 'サプライヤー認証',
    'footer.terms': '利用規約',
    'footer.privacy': 'プライバシー',
  },
  ES: {
    'nav.how': 'Como funciona',
    'nav.categories': 'Categorias',
    'nav.suppliers': 'Para proveedores',
    'nav.trust': 'Confianza y seguridad',
    'auth.login': 'Iniciar sesion',
    'action.postRequest': 'Publicar solicitud',
    'footer.buyers': 'Compradores',
    'footer.suppliers': 'Proveedores',
    'footer.settings': 'Ajustes',
    'footer.postRequest': 'Publicar solicitud',
    'footer.escrow': 'Proteccion escrow',
    'footer.becomeSupplier': 'Ser proveedor',
    'footer.pricing': 'Tarifas',
    'footer.verification': 'Verificacion de proveedor',
    'footer.terms': 'Terminos',
    'footer.privacy': 'Privacidad',
  },
  TL: {
    'nav.how': 'Paano ito gumagana',
    'nav.categories': 'Mga Kategorya',
    'nav.suppliers': 'Para sa mga Supplier',
    'nav.trust': 'Tiwala at Kaligtasan',
    'auth.login': 'Mag-login',
    'action.postRequest': 'Mag-post ng Kahilingan',
    'action.newRequest': 'Bagong Kahilingan',
    'action.viewAll': 'Tingnan lahat',
    'action.viewAllMessages': 'Tingnan lahat ng mensahe',
    'action.compareOffers': 'Ikumpara ang Alok',
    'action.viewPublicProfile': 'Tingnan ang Pampublikong Profile',
    'action.viewPings': 'Tingnan ang mga Ping',
    'action.quoteNow': 'Mag-quote Ngayon',
    'action.uploadProof': 'Mag-upload ng Patunay',
    'action.reply': 'Tumugon',
    'layout.settings': 'Mga Setting',
    'layout.catalogRules': 'Katalogo at Mga Patakaran',
    'layout.business': 'Negosyo',
    'layout.searchBuyer': 'Maghanap ng kahilingan, order...',
    'layout.buyerAccount': 'Account ng Mamimili',
    'layout.companyProfile': 'Profile ng Kumpanya',
    'layout.team': 'Koponan',
    'layout.logout': 'Mag-logout',
    'layout.supplierBadge': 'SUPPLIER',
    'layout.supplierPortal': 'Portal ng Supplier',
    'layout.onlinePings': 'Online at Tumatanggap ng Ping',
    'layout.verifiedSupplier': 'Verified na Supplier',
    'layout.myBusiness': 'Aking Negosyo',
    'buyer.nav.dashboard': 'Dashboard',
    'buyer.nav.requests': 'Aking mga Kahilingan',
    'buyer.nav.orders': 'Mga Order',
    'buyer.nav.messages': 'Mga Mensahe',
    'buyer.nav.disputes': 'Sentro ng Dispute',
    'buyer.nav.idealList': 'Ideal na Listahan',
    'buyer.nav.settings': 'Mga Setting ng Account',
    'buyer.nav.wallet': 'Pitaka at Escrow',
    'supplier.nav.dashboard': 'Dashboard',
    'supplier.nav.inbox': 'Ping Inbox',
    'supplier.nav.offers': 'Aking mga Alok',
    'supplier.nav.orders': 'Mga Order at Paghahatid',
    'supplier.nav.messages': 'Mga Mensahe',
    'supplier.nav.catalog': 'Aking Katalogo',
    'supplier.nav.triggers': 'Matching Triggers',
    'supplier.nav.payouts': 'Mga Setting ng Bayad',
    'supplier.nav.reviews': 'Mga Review at Tiwala',
    'supplier.nav.settings': 'Mga Setting',
    'buyer.dashboard.title': 'Dashboard ng Mamimili',
    'buyer.dashboard.activeRequests': 'Mga Aktibong Kahilingan',
    'buyer.dashboard.offersReceived': 'Mga Natanggap na Alok',
    'buyer.dashboard.ordersProgress': 'Mga Order sa Proseso',
    'buyer.dashboard.escrowHeld': 'Nakatago sa Escrow',
    'trust.score': 'Puntos',
    'trust.dealRate': 'Rate ng Deal',
    'trust.profile': 'Profile',
    'trust.deposit': 'Deposito',
    'trust.disputes': 'Mga Dispute',
    'footer.buyers': 'Mga Mamimili',
    'footer.suppliers': 'Mga Supplier',
    'footer.settings': 'Mga Setting',
    'footer.postRequest': 'Mag-post ng Kahilingan',
    'footer.escrow': 'Proteksyon ng Escrow',
    'footer.becomeSupplier': 'Maging Supplier',
    'footer.pricing': 'Bayad at Presyo',
    'footer.verification': 'Verification ng Supplier',
    'footer.terms': 'Mga Tuntunin',
    'footer.privacy': 'Privacy',
  },
  KO: {
    'nav.how': '이용 방법',
    'nav.categories': '카테고리',
    'nav.suppliers': '공급업체 등록',
    'nav.trust': '신뢰 및 안전',
    'auth.login': '로그인',
    'action.postRequest': '요청 등록',
    'action.newRequest': '새 요청',
    'action.viewAll': '모두 보기',
    'action.viewAllMessages': '모든 메시지 보기',
    'action.compareOffers': '견적 비교',
    'action.viewPublicProfile': '공개 프로필 보기',
    'action.viewPings': '매칭 보기',
    'action.quoteNow': '지금 견적',
    'action.uploadProof': '증빙 업로드',
    'action.reply': '답장',
    'layout.settings': '설정',
    'layout.catalogRules': '카탈로그 및 규칙',
    'layout.business': '비즈니스',
    'layout.searchBuyer': '요청, 주문 검색...',
    'layout.buyerAccount': '구매자 계정',
    'layout.companyProfile': '회사 프로필',
    'layout.team': '팀',
    'layout.logout': '로그아웃',
    'layout.supplierBadge': '공급업체',
    'layout.supplierPortal': '공급업체 포털',
    'layout.onlinePings': '온라인 및 핑 수신 중',
    'layout.verifiedSupplier': '인증된 공급업체',
    'layout.myBusiness': '내 비즈니스',
    'buyer.nav.dashboard': '대시보드',
    'buyer.nav.requests': '내 요청',
    'buyer.nav.orders': '주문',
    'buyer.nav.messages': '메시지',
    'buyer.nav.disputes': '분쟁 센터',
    'buyer.nav.idealList': '이상적 목록',
    'buyer.nav.settings': '계정 설정',
    'buyer.nav.wallet': '지갑 및 에스크로',
    'supplier.nav.dashboard': '대시보드',
    'supplier.nav.inbox': '핑 받은편지함',
    'supplier.nav.offers': '내 견적',
    'supplier.nav.orders': '주문 및 배송',
    'supplier.nav.messages': '메시지',
    'supplier.nav.catalog': '내 카탈로그',
    'supplier.nav.triggers': '매칭 트리거',
    'supplier.nav.payouts': '출금 설정',
    'supplier.nav.reviews': '리뷰 및 신뢰',
    'supplier.nav.settings': '설정',
    'buyer.dashboard.title': '구매자 대시보드',
    'buyer.dashboard.activeRequests': '활성 요청',
    'buyer.dashboard.offersReceived': '받은 견적',
    'buyer.dashboard.ordersProgress': '진행 중인 주문',
    'buyer.dashboard.escrowHeld': '에스크로 보관',
    'trust.score': '점수',
    'trust.dealRate': '거래 성사율',
    'trust.profile': '프로필',
    'trust.deposit': '보증금',
    'trust.disputes': '분쟁',
    'footer.buyers': '구매자',
    'footer.suppliers': '공급업체',
    'footer.settings': '설정',
    'footer.postRequest': '요청 등록',
    'footer.escrow': '에스크로 보호',
    'footer.becomeSupplier': '공급업체 등록',
    'footer.pricing': '요금 안내',
    'footer.verification': '공급업체 인증',
    'footer.terms': '이용약관',
    'footer.privacy': '개인정보처리방침',
  },
  TH: {
    'nav.how': 'วิธีการใช้งาน',
    'nav.categories': 'หมวดหมู่',
    'nav.suppliers': 'สำหรับผู้จัดหา',
    'nav.trust': 'ความน่าเชื่อถือและความปลอดภัย',
    'auth.login': 'เข้าสู่ระบบ',
    'action.postRequest': 'โพสต์คำขอ',
    'action.newRequest': 'คำขอใหม่',
    'action.viewAll': 'ดูทั้งหมด',
    'action.viewAllMessages': 'ดูข้อความทั้งหมด',
    'action.compareOffers': 'เปรียบเทียบข้อเสนอ',
    'action.viewPublicProfile': 'ดูโปรไฟล์สาธารณะ',
    'action.viewPings': 'ดูการจับคู่',
    'action.quoteNow': 'เสนอราคาตอนนี้',
    'action.uploadProof': 'อัปโหลดหลักฐาน',
    'action.reply': 'ตอบกลับ',
    'layout.settings': 'การตั้งค่า',
    'layout.logout': 'ออกจากระบบ',
    'layout.supplierPortal': 'พอร์ทัลผู้จัดหา',
    'buyer.nav.dashboard': 'แดชบอร์ด',
    'buyer.nav.requests': 'คำขอของฉัน',
    'buyer.nav.orders': 'คำสั่งซื้อ',
    'buyer.nav.messages': 'ข้อความ',
    'buyer.nav.disputes': 'ศูนย์ข้อพิพาท',
    'buyer.nav.wallet': 'กระเป๋าเงินและเอสโครว์',
    'supplier.nav.dashboard': 'แดชบอร์ด',
    'supplier.nav.inbox': 'กล่องข้อความ Ping',
    'supplier.nav.orders': 'คำสั่งซื้อและการจัดส่ง',
    'supplier.nav.catalog': 'แคตตาล็อกของฉัน',
    'buyer.dashboard.title': 'แดชบอร์ดผู้ซื้อ',
    'trust.score': 'คะแนน',
    'trust.dealRate': 'อัตราการทำข้อตกลง',
    'footer.buyers': 'ผู้ซื้อ',
    'footer.suppliers': 'ผู้จัดหา',
    'footer.terms': 'ข้อกำหนด',
    'footer.privacy': 'ความเป็นส่วนตัว',
  },
  VI: {
    'nav.how': 'Cách hoạt động',
    'nav.categories': 'Danh mục',
    'nav.suppliers': 'Cho nhà cung cấp',
    'nav.trust': 'Tin cậy & An toàn',
    'auth.login': 'Đăng nhập',
    'action.postRequest': 'Đăng yêu cầu',
    'action.newRequest': 'Yêu cầu mới',
    'action.viewAll': 'Xem tất cả',
    'action.viewAllMessages': 'Xem tất cả tin nhắn',
    'action.compareOffers': 'So sánh báo giá',
    'action.viewPublicProfile': 'Xem hồ sơ công khai',
    'action.viewPings': 'Xem ghép nối',
    'action.quoteNow': 'Báo giá ngay',
    'action.uploadProof': 'Tải bằng chứng',
    'action.reply': 'Trả lời',
    'layout.settings': 'Cài đặt',
    'layout.logout': 'Đăng xuất',
    'layout.supplierPortal': 'Cổng nhà cung cấp',
    'buyer.nav.dashboard': 'Tổng quan',
    'buyer.nav.requests': 'Yêu cầu của tôi',
    'buyer.nav.orders': 'Đơn hàng',
    'buyer.nav.messages': 'Tin nhắn',
    'buyer.nav.disputes': 'Trung tâm tranh chấp',
    'buyer.nav.wallet': 'Ví & Escrow',
    'supplier.nav.dashboard': 'Tổng quan',
    'supplier.nav.inbox': 'Hộp thư Ping',
    'supplier.nav.orders': 'Đơn hàng & Giao hàng',
    'supplier.nav.catalog': 'Danh mục của tôi',
    'buyer.dashboard.title': 'Tổng quan người mua',
    'trust.score': 'Điểm',
    'trust.dealRate': 'Tỷ lệ giao dịch',
    'footer.buyers': 'Người mua',
    'footer.suppliers': 'Nhà cung cấp',
    'footer.terms': 'Điều khoản',
    'footer.privacy': 'Quyền riêng tư',
  },
  ID: {
    'nav.how': 'Cara Kerja',
    'nav.categories': 'Kategori',
    'nav.suppliers': 'Untuk Pemasok',
    'nav.trust': 'Kepercayaan & Keamanan',
    'auth.login': 'Masuk',
    'action.postRequest': 'Posting Permintaan',
    'action.newRequest': 'Permintaan Baru',
    'action.viewAll': 'Lihat semua',
    'action.viewAllMessages': 'Lihat semua pesan',
    'action.compareOffers': 'Bandingkan Penawaran',
    'action.viewPublicProfile': 'Lihat Profil Publik',
    'action.viewPings': 'Lihat Pencocokan',
    'action.quoteNow': 'Minta Penawaran',
    'action.uploadProof': 'Unggah Bukti',
    'action.reply': 'Balas',
    'layout.settings': 'Pengaturan',
    'layout.logout': 'Keluar',
    'layout.supplierPortal': 'Portal Pemasok',
    'buyer.nav.dashboard': 'Dasbor',
    'buyer.nav.requests': 'Permintaan Saya',
    'buyer.nav.orders': 'Pesanan',
    'buyer.nav.messages': 'Pesan',
    'buyer.nav.disputes': 'Pusat Sengketa',
    'buyer.nav.wallet': 'Dompet & Escrow',
    'supplier.nav.dashboard': 'Dasbor',
    'supplier.nav.inbox': 'Kotak Masuk Ping',
    'supplier.nav.orders': 'Pesanan & Pengiriman',
    'supplier.nav.catalog': 'Katalog Saya',
    'buyer.dashboard.title': 'Dasbor Pembeli',
    'trust.score': 'Skor',
    'trust.dealRate': 'Tingkat Transaksi',
    'footer.buyers': 'Pembeli',
    'footer.suppliers': 'Pemasok',
    'footer.terms': 'Ketentuan',
    'footer.privacy': 'Privasi',
  },
  AR: {
    'nav.how': 'كيف يعمل',
    'nav.categories': 'الفئات',
    'nav.suppliers': 'للموردين',
    'nav.trust': 'الثقة والسلامة',
    'auth.login': 'تسجيل الدخول',
    'action.postRequest': 'نشر طلب',
    'action.newRequest': 'طلب جديد',
    'action.viewAll': 'عرض الكل',
    'action.viewAllMessages': 'عرض جميع الرسائل',
    'action.compareOffers': 'مقارنة العروض',
    'action.viewPublicProfile': 'عرض الملف الشخصي العام',
    'action.viewPings': 'عرض التطابقات',
    'action.quoteNow': 'اطلب عرض أسعار',
    'action.uploadProof': 'رفع الدليل',
    'action.reply': 'رد',
    'layout.settings': 'الإعدادات',
    'layout.logout': 'تسجيل الخروج',
    'layout.supplierPortal': 'بوابة المورد',
    'layout.companyProfile': 'ملف الشركة',
    'layout.team': 'الفريق',
    'layout.buyerAccount': 'حساب المشتري',
    'layout.myBusiness': 'أعمالي',
    'buyer.nav.dashboard': 'لوحة التحكم',
    'buyer.nav.requests': 'طلباتي',
    'buyer.nav.orders': 'الطلبات',
    'buyer.nav.messages': 'الرسائل',
    'buyer.nav.disputes': 'مركز النزاعات',
    'buyer.nav.wallet': 'المحفظة والضمان',
    'buyer.nav.settings': 'إعدادات الحساب',
    'supplier.nav.dashboard': 'لوحة التحكم',
    'supplier.nav.inbox': 'صندوق البريد',
    'supplier.nav.orders': 'الطلبات والتسليم',
    'supplier.nav.catalog': 'كتالوجي',
    'buyer.dashboard.title': 'لوحة تحكم المشتري',
    'buyer.dashboard.activeRequests': 'الطلبات النشطة',
    'buyer.dashboard.offersReceived': 'العروض المستلمة',
    'buyer.dashboard.ordersProgress': 'الطلبات قيد التنفيذ',
    'buyer.dashboard.escrowHeld': 'محتجز في الضمان',
    'trust.score': 'النقاط',
    'trust.dealRate': 'معدل الصفقات',
    'trust.profile': 'الملف الشخصي',
    'trust.deposit': 'الوديعة',
    'trust.disputes': 'النزاعات',
    'footer.buyers': 'المشترون',
    'footer.suppliers': 'الموردون',
    'footer.settings': 'الإعدادات',
    'footer.postRequest': 'نشر طلب',
    'footer.escrow': 'حماية الضمان',
    'footer.becomeSupplier': 'كن موردًا',
    'footer.pricing': 'الرسوم والأسعار',
    'footer.verification': 'التحقق من المورد',
    'footer.terms': 'الشروط',
    'footer.privacy': 'الخصوصية',
  },
}

export const useAppStore = defineStore('app', {
  state: (): AppState => ({
    language: 'EN',
    currency: 'PHP',
    regionCountry: 'PH',
    enabledCurrencies: ['PHP'],
    paymentRegionConfig: null,
  }),
  getters: {
    languageOptions: (): SelectOption[] => [
      { code: 'EN', label: 'English' },
      { code: 'ZH', label: '中文' },
      { code: 'TL', label: 'Filipino' },
      { code: 'JA', label: '日本語' },
      { code: 'KO', label: '한국어' },
      { code: 'ES', label: 'Español' },
      { code: 'TH', label: 'ภาษาไทย' },
      { code: 'VI', label: 'Tiếng Việt' },
      { code: 'ID', label: 'Bahasa Indonesia' },
      { code: 'AR', label: 'العربية' },
    ],
    allCurrencyOptions: (): SelectOption[] => [
      { code: 'USD', label: 'USD - US Dollar' },
      { code: 'PHP', label: 'PHP - Philippine Peso' },
      { code: 'EUR', label: 'EUR - Euro' },
      { code: 'JPY', label: 'JPY - Japanese Yen' },
      { code: 'CNY', label: 'CNY - Chinese Yuan' },
      { code: 'SGD', label: 'SGD - Singapore Dollar' },
      { code: 'HKD', label: 'HKD - Hong Kong Dollar' },
      { code: 'AUD', label: 'AUD - Australian Dollar' },
      { code: 'GBP', label: 'GBP - British Pound' },
      { code: 'CAD', label: 'CAD - Canadian Dollar' },
      { code: 'KRW', label: 'KRW - Korean Won' },
      { code: 'AED', label: 'AED - UAE Dirham' },
      { code: 'INR', label: 'INR - Indian Rupee' },
      { code: 'THB', label: 'THB - Thai Baht' },
      { code: 'USDT', label: 'USDT - Tether' },
    ],
    currencyOptions(state): SelectOption[] {
      const enabled = new Set(state.enabledCurrencies?.length ? state.enabledCurrencies : ['PHP'])
      return this.allCurrencyOptions.filter(option => enabled.has(option.code))
    },
    t: (state) => (key: string): string => messages[state.language]?.[key] ?? messages.EN[key] ?? key,
  },
  actions: {
    setLanguage(lang: string) {
      if (this.languageOptions.some(option => option.code === lang)) {
        this.language = lang as LanguageCode
        this.applyDocumentLocale()
        this.persist()
      }
    },
    setCurrency(curr: string) {
      if (this.currencyOptions.some(option => option.code === curr)) {
        this.currency = curr
        this.persist()
      }
    },
    async fetchPaymentRegionConfig(country = 'PH') {
      this.regionCountry = country.toUpperCase()
      try {
        const config = useRuntimeConfig()
        const data = await $fetch<Record<string, any>>(`${config.public.apiBase}/payments/region-config`, {
          query: { country: this.regionCountry },
        })
        this.paymentRegionConfig = data
        const enabled = Array.isArray(data.enabled_currencies) && data.enabled_currencies.length
          ? data.enabled_currencies.map((c: string) => c.toUpperCase())
          : [String(data.local_currency || 'PHP').toUpperCase()]
        this.enabledCurrencies = enabled
        const localCurrency = String(data.local_currency || enabled[0] || 'PHP').toUpperCase()
        if (!enabled.includes(this.currency)) {
          this.currency = enabled.includes(localCurrency) ? localCurrency : enabled[0]
          this.persist()
        }
      } catch {
        this.enabledCurrencies = ['PHP']
        this.currency = 'PHP'
      }
    },
    hydrate() {
      if (!import.meta.client) return
      this.setLanguage(localStorage.getItem('pp_language') || this.language)
      this.setCurrency(localStorage.getItem('pp_currency') || this.currency)
    },
    persist() {
      if (!import.meta.client) return
      localStorage.setItem('pp_language', this.language)
      localStorage.setItem('pp_currency', this.currency)
      const maxAge = 60 * 60 * 24 * 365
      document.cookie = `pp_language=${encodeURIComponent(this.language)}; Path=/; Max-Age=${maxAge}; SameSite=Lax`
      document.cookie = `pp_currency=${encodeURIComponent(this.currency)}; Path=/; Max-Age=${maxAge}; SameSite=Lax`
    },
    applyDocumentLocale() {
      if (!import.meta.client) return
      const langMap: Record<LanguageCode, string> = {
        EN: 'en',
        ZH: 'zh-CN',
        JA: 'ja',
        ES: 'es',
        TL: 'tl',
        KO: 'ko',
        TH: 'th',
        VI: 'vi',
        ID: 'id',
        AR: 'ar',
      }
      document.documentElement.lang = langMap[this.language]
      // RTL support
      document.documentElement.dir = this.language === 'AR' ? 'rtl' : 'ltr'
    }
  }
})
