import { defineStore } from 'pinia'
import {
  LANGUAGE_TO_URI_LOCALE_PREFIX,
  normalizeLanguageCode,
  withLocalePrefix,
} from '~/utils/localeRoutes'
import {
  FALLBACK_PAYMENT_POLICIES,
  currencyOptionLabel,
  normalizeCurrencyCode,
  normalizePaymentPolicy,
} from '~/utils/currencyPolicy'

type LanguageCode = 'EN' | 'ZH' | 'JA' | 'ES' | 'TL' | 'KO' | 'TH' | 'VI' | 'ID' | 'AR' | 'SR' | 'BS' | 'PL' | 'DE' | 'RO'

interface SelectOption {
  code: string
  label: string
}

interface AppState {
  language: LanguageCode
  currency: string
  regionCountry: string
  enabledLanguageCodes: LanguageCode[] | null
  routeLocalePrefix: string
  enabledCurrencies: string[]
  marketLocalizationConfig: Record<string, any> | null
  paymentRegionConfig: Record<string, any> | null
}

const MARKET_LANGUAGE_OPTIONS: SelectOption[] = [
  { code: 'EN', label: 'English' },
  { code: 'SR', label: 'Srpski' },
  { code: 'BS', label: 'Bosanski' },
  { code: 'PL', label: 'Polski' },
  { code: 'DE', label: 'Deutsch' },
  { code: 'RO', label: 'Română' },
  { code: 'ZH', label: '中文' },
]

const messages: Partial<Record<LanguageCode, Record<string, string>>> = {
  EN: {
    'nav.how': 'How it works',
    'nav.categories': 'Categories',
    'nav.suppliers': 'For Suppliers',
    'nav.trust': 'Trust & Safety',
    'nav.marketplace': 'Marketplace',
    'nav.aiProjects': 'Projects',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'categories.title': 'Browse Categories',
    'categories.subtitle': 'Find verified suppliers across {count}+ industries worldwide.',
    'categories.browse': 'Browse',
    'categories.empty': 'No categories found.',
    'categories.ctaTitle': "Can't find what you need?",
    'categories.ctaDesc': 'Post a purchase request and let verified suppliers come to you.',
    'action.postRequest': 'Post Request',
    'action.search': 'Search',
    'action.newRequest': 'New Request',
    'action.browseMarketplace': 'Browse Marketplace',
    'action.findSuppliers': 'Find Suppliers',
    'action.viewAll': 'View all',
    'action.viewAllMessages': 'View all messages',
    'action.compareOffers': 'Compare Offers',
    'action.viewPublicProfile': 'View Public Profile',
    'action.viewPings': 'View Pings',
    'action.quoteNow': 'Quote Now',
    'action.uploadProof': 'Upload Proof',
    'action.reply': 'Reply',
    'market.title': 'Marketplace',
    'market.items': 'items',
    'market.searchPlaceholder': 'Search products...',
    'market.allModes': 'All (B2B + B2C)',
    'market.b2bOnly': 'B2B Only',
    'market.b2cOnly': 'B2C Only',
    'market.bestMatch': 'Best Match',
    'market.newest': 'Newest',
    'market.mostOrders': 'Most Orders',
    'market.priceAsc': 'Price ↑',
    'market.priceDesc': 'Price ↓',
    'market.originCountry': 'Origin Country',
    'market.allCountries': 'All Countries',
    'market.sellerType': 'Seller Type',
    'market.allSellers': 'All Sellers',
    'market.individual': 'Individual / Freelancer',
    'market.business': 'Business / Company',
    'market.verifiedOnly': 'Verified businesses only',
    'market.sponsored': 'Sponsored',
    'market.recommended': 'Recommended for you',
    'market.official': 'Official',
    'market.noProducts': 'No products found',
    'market.tryFilters': 'Try adjusting your filters or',
    'market.postRequestInstead': 'post a request',
    'market.couldNotLoad': 'Could not load marketplace products',
    'market.retry': 'Try again',
    'market.loading': 'Loading...',
    'market.loadMore': 'Load More',
    'market.buyNow': 'Buy Now',
    'market.requestQuote': 'Request Quote',
    'market.moq': 'MOQ',
    'market.orders': 'orders',
    'market.bannerOfficialCta': 'Open AinerWise official',
    'market.bannerDeckKicker': 'Official spotlight',
    'market.bannerDeckTitle': 'AI + KNX deals',
    'market.bannerDeckLink': 'Official site',
    'market.banner1Kicker': 'AI + KNX',
    'market.banner1Title': 'Smart building brain',
    'market.banner1Subtitle': 'Shop devices first, then upgrade into AI design, BOQ, RFQ and delivery.',
    'market.banner1CardTitle': 'AI building',
    'market.banner1CardText': 'KNX, energy, security and service.',
    'market.banner2Kicker': 'Smart villa',
    'market.banner2Title': 'Villa smart home upgrade',
    'market.banner2Subtitle': 'Lighting, scenes, access, energy and devices sourced from one marketplace.',
    'market.banner2CardTitle': 'Villa pack',
    'market.banner2CardText': 'Products plus local installation.',
    'market.banner3Kicker': 'Small hotel',
    'market.banner3Title': 'Hotel AI upgrade kits',
    'market.banner3Subtitle': 'Turn rooms, locks, CCTV and energy into a managed smart-building project.',
    'market.banner3CardTitle': 'Hotel upgrade',
    'market.banner3CardText': 'Room, access and lifecycle service.',
    'project.loading': 'Loading...',
    'project.loadingProject': 'Loading project...',
    'project.forge': 'AI Project Forge',
    'project.forgeDesc': 'Conversationally collect project details, optionally attach files, generate an editable demand form, then match catalog items and supplier quotes.',
    'project.progress': 'Progress',
    'project.refresh': 'Refresh',
    'project.aiAnalyze': 'AI Analyze',
    'project.refreshPrices': 'Refresh Prices',
    'project.freezeForm': 'Freeze Form',
    'project.publishItems': 'Publish {count} Items',
    'project.langgraphIntake': 'LangGraph Intake',
    'project.collectStep': 'Collect project information step by step',
    'project.chatGoalTitle': 'Tell AI your project goal first',
    'project.chatGoalExample': 'Example: I want to build a 200 sqm villa in Cebu, prefer premium materials, and need estimates for rebar, cement, PVC, and lighting.',
    'project.chatPlaceholder': 'Describe the project, answer AI follow-ups, or explain key points from uploaded files... (Ctrl+Enter to send)',
    'project.attachFiles': 'Attach files',
    'project.send': 'Send',
    'project.proceed': 'Proceed',
    'project.uploading': 'Uploading...',
    'project.providerMissing': 'AI provider is not configured. Please ask an admin to configure Admin → Integrations → AI Provider and enable AI Project Forge.',
    'project.oldDeepseekEndpoint': 'This failed run used an old DeepSeek endpoint. The backend now uses the exact Admin AI Provider Base URL. Please retry analysis.',
    'project.status.done': 'Done',
    'project.status.active': 'Active',
    'project.status.pending': 'Pending',
    'project.stage.goal': 'Goal',
    'project.stage.coreNeed': 'Core need',
    'project.stage.metrics': 'Metrics',
    'project.stage.indicators': 'Indicators',
    'project.stage.files': 'Files',
    'project.stage.optional': 'Optional',
    'project.stage.demandModel': 'Demand Model',
    'project.stage.lineItems': 'Line items',
    'project.stage.compare': 'Compare',
    'project.stage.pricing': 'Pricing',
    'project.stage.finalReport': 'Final Report',
    'project.stage.freeze': 'Freeze',
    'project.preview.coreNeed': 'Core Need',
    'project.preview.waitGoal': 'Waiting for the user to describe the project goal',
    'project.preview.projectMetrics': 'Project Metrics',
    'project.preview.indicatorsMissing': '{count} indicators missing',
    'project.preview.indicatorsCollected': '{count} indicators collected',
    'project.preview.supportingFiles': 'Supporting Files',
    'project.preview.filesAttached': '{count} files attached for optional text/multimodal extraction',
    'project.preview.demandForm': 'Demand Form',
    'project.preview.itemsIncluded': '{items} items, {included} included in estimate',
    'project.preview.matchingQuotes': 'Matching & Quotes',
    'project.preview.comparisonIssues': '{groups} comparison groups, {issues} issues to review',
    'project.preview.frozenReady': 'Frozen and ready to publish',
    'project.preview.waitFreeze': 'Waiting for user review and freeze',
    'layout.settings': 'Settings',
    'layout.catalogRules': 'Catalog & Rules',
    'layout.business': 'Business',
    'layout.searchBuyer': 'Search requests, orders...',
    'layout.buyerAccount': 'Buyer Account',
    'layout.companyProfile': 'Company Profile',
    'layout.team': 'Team',
    'layout.logout': 'Log out',
    'layout.supplierBadge': 'SUPPLIER',
    'layout.supplierPortal': 'Supplier Portal',
    'layout.onlinePings': 'Online & Receiving Pings',
    'layout.verifiedSupplier': 'Verified Supplier',
    'layout.myBusiness': 'My Business',
    'layout.shoppingFirst': 'Shopping First',
    'layout.marketplaceShortcutDesc': 'Keep sourcing one click away from every buyer page.',
    'layout.aiProjects': 'AI Projects',
    'layout.myProfile': 'My Profile',
    'layout.deliveryAddresses': 'Delivery Addresses',
    'layout.notificationSettings': 'Notification Settings',
    'layout.notifications': 'Notifications',
    'layout.markAllRead': 'Mark all read',
    'layout.loading': 'Loading...',
    'layout.noNotifications': 'No notifications yet',
    'layout.viewAllNotifications': 'View all notifications',
    'layout.dashboard': 'Dashboard',
    'layout.ainerwiseSite': 'AinerWise Official Site',
    'layout.operatingCountry': 'Operating Country',
    'layout.settlementCurrency': 'Settlement',
    'buyer.nav.dashboard': 'Dashboard',
    'buyer.nav.marketplace': 'Marketplace',
    'buyer.nav.requests': 'My Requests',
    'buyer.nav.orders': 'Orders',
    'buyer.nav.messages': 'Messages',
    'buyer.nav.disputes': 'Dispute Center',
    'buyer.nav.idealList': 'Ideal List',
    'buyer.nav.settings': 'Account Settings',
    'buyer.nav.wallet': 'Payments Ledger',
    'supplier.nav.dashboard': 'Dashboard',
    'supplier.nav.inbox': 'Ping Inbox',
    'supplier.nav.offers': 'My Offers',
    'supplier.nav.orders': 'Orders & Delivery',
    'supplier.nav.messages': 'Messages',
    'supplier.nav.catalog': 'My Catalog',
    'supplier.nav.triggers': 'Matching Triggers',
    'supplier.nav.payouts': 'Payout Settings',
    'supplier.nav.reviews': 'Reviews & Trust',
    'supplier.nav.settings': 'Settings',
    'buyer.dashboard.title': 'Buyer Dashboard',
    'buyer.dashboard.activeRequests': 'Active Requests',
    'buyer.dashboard.offersReceived': 'Offers Received',
    'buyer.dashboard.ordersProgress': 'Orders in Progress',
    'buyer.dashboard.escrowHeld': 'Payments On Record',
    'buyer.dashboard.trustTitle': 'Buyer Trust Profile',
    'buyer.dashboard.trustDesc': 'Based on profile completion, deal completion, deposit and platform risk signals.',
    'buyer.dashboard.shopTitle': 'Back to sourcing',
    'buyer.dashboard.shopDesc': 'Browse the product waterfall, filter by category and region, then buy now or request quotes without losing your dashboard context.',
    'buyer.dashboard.shopPrimary': 'Open Marketplace',
    'buyer.dashboard.shopSecondary': 'Find trusted suppliers',
    'buyer.dashboard.shopStatProducts': 'Live products',
    'buyer.dashboard.shopStatModes': 'B2B + B2C',
    'buyer.dashboard.shopStatRank': 'Rank by trust, cost, distance',
    'trust.score': 'Score',
    'trust.dealRate': 'Deal Rate',
    'trust.profile': 'Profile',
    'trust.deposit': 'Deposit',
    'trust.disputes': 'Disputes',
    'trust.tier.BRONZE': 'Bronze',
    'trust.tier.SILVER': 'Silver',
    'trust.tier.GOLD': 'Gold',
    'trust.tier.PLATINUM': 'Platinum',
    'trust.tier.DIAMOND': 'Diamond',
    'buyer.dashboard.recentMessages': 'Recent Messages',
    'buyer.dashboard.messagePreview': 'Can we deliver this on Tuesday instead?',
    'buyer.dashboard.recommended': 'Recommended for You',
    'buyer.table.requestTitle': 'Request Title',
    'buyer.table.budget': 'Budget',
    'buyer.table.status': 'Status',
    'buyer.table.offers': 'Offers',
    'buyer.table.actions': 'Actions',
    'buyer.status.receivingOffers': 'Receiving Offers',
    'buyer.status.reviewing': 'Reviewing',
    'supplier.dashboard.title': 'Supplier Dashboard',
    'supplier.dashboard.subtitle': "Here's what's happening with your business today.",
    'supplier.dashboard.newPings': 'New Pings',
    'supplier.dashboard.activeOffers': 'Active Offers',
    'supplier.dashboard.awardedOrders': 'Awarded Orders',
    'supplier.dashboard.pendingDelivery': 'Pending Delivery',
    'supplier.dashboard.escrowPayout': 'Completed Order Value',
    'supplier.dashboard.responseSla': 'Response Time SLA',
    'supplier.dashboard.rating': 'Rating',
    'supplier.dashboard.disputeRate': 'Dispute Rate',
    'supplier.dashboard.recentPings': 'Recent Pings',
    'supplier.dashboard.actionRequired': 'Action Required',
    'supplier.dashboard.away': 'away',
    'supplier.dashboard.preFunded': 'Pre-funded',
    'supplier.dashboard.budget': 'Budget',
    'supplier.dashboard.deliveryProof': 'Upload Delivery Proof',
    'supplier.dashboard.deliveryProofDesc': 'Order #ORD-99120 has been marked as shipped. Upload proof of delivery to allow the buyer to release funds.',
    'supplier.dashboard.unreadMessage': 'Unread Message from Buyer',
    'supplier.dashboard.unreadMessageDesc': 'Regarding Offer #OFF-4412 for "Marine Engine Parts".',
    'buyer.settings.title': 'Buyer Settings',
    'buyer.settings.subtitle': 'Control receiving addresses, reminder channels, and the contact details tied to your buyer account.',
    'buyer.settings.auditNotice': 'In-site chat and transaction records remain the canonical source for disputes and audits.',
    'buyer.settings.guardTitle': 'Reminder channels are optional. Order evidence is not.',
    'buyer.settings.guardDesc': 'Email, Telegram, WhatsApp, and Viber can pull you back into the platform quickly, but messages, commitments, and settlement-sensitive details always stay in-site.',
    'buyer.settings.contactTitle': 'Account Contact',
    'buyer.settings.contactDesc': 'Keep the buyer identity and callback details current.',
    'buyer.settings.fullName': 'Full Name',
    'buyer.settings.fullNamePlaceholder': 'Buyer name',
    'buyer.settings.mobile': 'Mobile Number',
    'buyer.settings.email': 'Email',
    'buyer.settings.telegram': 'Telegram Chat ID',
    'buyer.settings.telegramPlaceholder': 'Optional: @username or chat ID',
    'buyer.settings.whatsapp': 'WhatsApp Number',
    'buyer.settings.whatsappPlaceholder': 'Optional: +381...',
    'buyer.settings.viber': 'Viber Number',
    'buyer.settings.viberPlaceholder': 'Optional: +381...',
    'buyer.settings.saveContact': 'Save Contact Details',
    'buyer.settings.addressTitle': 'Receiving Address Book',
    'buyer.settings.addressDesc': 'These are the drop-off destinations buyers can switch to quickly during checkout.',
    'buyer.settings.loadingAddresses': 'Loading addresses...',
    'buyer.settings.noAddress': 'No receiving address yet. Add your most common warehouse, site office, or delivery point.',
    'buyer.settings.default': 'Default',
    'buyer.settings.edit': 'Edit',
    'buyer.settings.setDefault': 'Set Default',
    'buyer.settings.delete': 'Delete',
    'buyer.settings.editAddress': 'Edit Receiving Address',
    'buyer.settings.addAddress': 'Add Receiving Address',
    'buyer.settings.addressLabelPlaceholder': 'Label: Main warehouse',
    'buyer.settings.receiverNamePlaceholder': 'Receiver name',
    'buyer.settings.receiverPhonePlaceholder': 'Receiver phone',
    'buyer.settings.cityPlaceholder': 'City',
    'buyer.settings.addressLinePlaceholder': 'Address line 1',
    'buyer.settings.postalPlaceholder': 'Postal code',
    'buyer.settings.cancel': 'Cancel',
    'buyer.settings.saveAddress': 'Save Address',
    'buyer.settings.addAddressButton': 'Add Address',
    'buyer.settings.notificationsTitle': 'Notification Settings',
    'buyer.settings.notificationsDesc': 'Choose which reminder channels are allowed to pull you back to the in-site workflow.',
    'buyer.settings.reminderChannels': 'Reminder Channels',
    'buyer.settings.emailReminder': 'Email reminders',
    'buyer.settings.emailReminderDesc': 'Send a summary when a new message, order change, or supplier response needs attention.',
    'buyer.settings.telegramReminder': 'Telegram reminders',
    'buyer.settings.telegramReminderDesc': 'Only enabled when a Telegram chat ID is saved above.',
    'buyer.settings.whatsappReminder': 'WhatsApp reminders',
    'buyer.settings.whatsappReminderDesc': 'Only enabled when a WhatsApp number is saved above.',
    'buyer.settings.viberReminder': 'Viber reminders',
    'buyer.settings.viberReminderDesc': 'Only enabled when a Viber number is saved above.',
    'buyer.settings.eventTriggers': 'Event Triggers',
    'buyer.settings.event.newMessage': 'New in-site messages',
    'buyer.settings.event.newMessageDesc': 'Alert me when a supplier replies in a thread that affects a live order or quote.',
    'buyer.settings.event.intentMatch': 'Request matches',
    'buyer.settings.event.intentMatchDesc': 'Tell me when my posted buying needs have fresh marketplace matches.',
    'buyer.settings.event.offerReceived': 'New offers received',
    'buyer.settings.event.offerReceivedDesc': 'Notify me when suppliers respond with a concrete quotation.',
    'buyer.settings.event.offerAwarded': 'Award follow-up reminders',
    'buyer.settings.event.offerAwardedDesc': 'Keep me aware when an awarded flow needs follow-up action.',
    'buyer.settings.event.orderUpdate': 'Order status updates',
    'buyer.settings.event.orderUpdateDesc': 'Payment, acceptance, and order progress changes should pull me back in quickly.',
    'buyer.settings.event.deliveryUpdate': 'Delivery updates',
    'buyer.settings.event.deliveryUpdateDesc': 'Remind me when shipment or arrival status changes.',
    'buyer.settings.saveNotifications': 'Save Notification Settings',
    'buyer.settings.profileUpdated': 'Buyer profile updated',
    'buyer.settings.profileFailed': 'Failed to update buyer profile',
    'buyer.settings.notificationsUpdated': 'Notification settings updated',
    'buyer.settings.notificationsFailed': 'Failed to update notification settings',
    'buyer.settings.addressUpdated': 'Address book updated',
    'buyer.settings.addressFailed': 'Failed to save address',
    'buyer.settings.defaultAddressUpdated': 'Default address updated',
    'buyer.settings.defaultAddressFailed': 'Failed to update default address',
    'buyer.settings.addressRemoved': 'Address removed',
    'buyer.settings.addressRemoveFailed': 'Failed to remove address',
    'wallet.title': 'Payments Ledger',
    'wallet.subtitle': 'A record trail of your order payments. AinerWise Market never holds your funds.',
    'wallet.refresh': 'Refresh',
    'wallet.directTitle': 'Direct-payment mode',
    'wallet.directDesc': 'You pay suppliers directly per the milestone plan you agree together. This page keeps the paper trail — recorded payments, references, and settlement status.',
    'wallet.recordedPayments': 'Recorded Payments',
    'wallet.recordedDesc': 'Direct payments you logged on orders',
    'wallet.settled': 'Settled',
    'wallet.settledDesc': 'Delivery confirmed & closed',
    'wallet.awaiting': 'Awaiting Payment Record',
    'wallet.awaitingDesc': 'Orders without a recorded payment',
    'wallet.orderRecords': 'Order Payment Records',
    'wallet.records': 'records',
    'wallet.historical': 'Historical Account Records',
    'wallet.historicalDesc': 'Read-only history from the legacy balance system.',
    'wallet.column.order': 'Order',
    'wallet.column.date': 'Date',
    'wallet.column.amount': 'Amount',
    'wallet.column.status': 'Status',
    'wallet.column.reference': 'Reference',
    'wallet.column.description': 'Description',
    'wallet.status.AWAITING_PAYMENT': 'Awaiting payment record',
    'wallet.status.PAID_IN_ESCROW': 'Payment recorded',
    'wallet.status.IN_PROGRESS': 'In progress',
    'wallet.status.DELIVERED': 'Delivered',
    'wallet.status.ACCEPTED': 'Completed',
    'wallet.status.PAYOUT_RELEASED': 'Settled',
    'wallet.status.DISPUTED': 'Disputed',
    'wallet.status.CANCELED': 'Cancelled',
    'wallet.status.CREATED': 'Created',
    'wallet.currencyNote': 'Showing totals for the currency selected in the top bar. Orders in other currencies are kept separate and are not mixed into this total.',
    'wallet.localReference': 'Local reference:',
    'buyer.notifications.title': 'Notifications',
    'buyer.notifications.subtitle': 'Buyer alerts for new offers, order updates, disputes, and messages.',
    'buyer.notifications.loading': 'Loading notifications...',
    'buyer.notifications.empty': 'No notifications yet.',
    'buyer.notifications.new': 'New',
    'buyer.notifications.type.NEW_OFFER_FOR_BUYER': 'New offer received',
    'buyer.notifications.type.OFFER_UPDATED_BUYER': 'Offer updated',
    'buyer.notifications.type.ORDER_CREATED_BUYER': 'Order created',
    'buyer.notifications.type.DELIVERY_UPDATED_BUYER': 'Delivery updated',
    'buyer.notifications.type.DISPUTE_OPENED': 'Dispute opened',
    'buyer.notifications.type.MESSAGE_RECEIVED': 'New message',
    'buyer.notifications.type.ADMIN_TEST': 'Admin notification',
    'time.justNow': 'just now',
    'footer.buyers': 'Buyers',
    'footer.suppliers': 'Suppliers',
    'footer.settings': 'Settings',
    'footer.postRequest': 'Post a Request',
    'footer.escrow': 'Buyer Protection',
    'footer.becomeSupplier': 'Become a Supplier',
    'footer.pricing': 'Fees & Pricing',
    'footer.verification': 'Supplier Verification',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
  },
  BS: {
    'nav.how': 'Kako funkcioniše',
    'nav.categories': 'Kategorije',
    'nav.suppliers': 'Za dobavljače',
    'nav.trust': 'Povjerenje i sigurnost',
    'nav.marketplace': 'Tržište',
    'auth.login': 'Prijava',
    'auth.logout': 'Odjava',
    'categories.title': 'Pregledaj kategorije',
    'categories.browse': 'Pregledaj',
    'categories.empty': 'Nema kategorija.',
    'categories.ctaTitle': 'Ne možete pronaći ono što vam treba?',
    'categories.ctaDesc': 'Objavite zahtjev za nabavku i neka vam se jave provjereni dobavljači.',
    'action.postRequest': 'Objavi zahtjev',
    'action.search': 'Pretraga',
    'action.newRequest': 'Novi zahtjev',
    'action.browseMarketplace': 'Pregledaj tržište',
    'action.findSuppliers': 'Pronađi dobavljače',
    'action.viewAll': 'Prikaži sve',
    'action.compareOffers': 'Usporedi ponude',
    'action.quoteNow': 'Pošalji ponudu',
    'action.reply': 'Odgovori',
    'footer.buyers': 'Kupci',
    'footer.suppliers': 'Dobavljači',
    'footer.postRequest': 'Objavi zahtjev',
    'footer.becomeSupplier': 'Postanite dobavljač',
    'footer.pricing': 'Cijene i naknade',
    'footer.terms': 'Uslovi korištenja',
    'footer.privacy': 'Privatnost',
  },
  DE: {
    'nav.how': 'So funktioniert es',
    'nav.categories': 'Kategorien',
    'nav.suppliers': 'Für Lieferanten',
    'nav.trust': 'Vertrauen & Sicherheit',
    'nav.marketplace': 'Marktplatz',
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'categories.title': 'Kategorien durchsuchen',
    'categories.browse': 'Durchsuchen',
    'categories.empty': 'Keine Kategorien gefunden.',
    'categories.ctaTitle': 'Nicht das Richtige gefunden?',
    'categories.ctaDesc': 'Stellen Sie eine Anfrage und lassen Sie geprüfte Lieferanten auf Sie zukommen.',
    'action.postRequest': 'Anfrage stellen',
    'action.search': 'Suchen',
    'action.newRequest': 'Neue Anfrage',
    'action.browseMarketplace': 'Marktplatz durchsuchen',
    'action.findSuppliers': 'Lieferanten finden',
    'action.viewAll': 'Alle anzeigen',
    'action.compareOffers': 'Angebote vergleichen',
    'action.quoteNow': 'Angebot abgeben',
    'action.reply': 'Antworten',
    'footer.buyers': 'Käufer',
    'footer.suppliers': 'Lieferanten',
    'footer.postRequest': 'Anfrage stellen',
    'footer.becomeSupplier': 'Lieferant werden',
    'footer.pricing': 'Gebühren & Preise',
    'footer.terms': 'AGB',
    'footer.privacy': 'Datenschutz',
  },
  PL: {
    'nav.how': 'Jak to działa',
    'nav.categories': 'Kategorie',
    'nav.suppliers': 'Dla dostawców',
    'nav.trust': 'Zaufanie i bezpieczeństwo',
    'nav.marketplace': 'Rynek',
    'auth.login': 'Zaloguj się',
    'auth.logout': 'Wyloguj',
    'categories.title': 'Przeglądaj kategorie',
    'categories.browse': 'Przeglądaj',
    'categories.empty': 'Brak kategorii.',
    'categories.ctaTitle': 'Nie możesz znaleźć tego, czego szukasz?',
    'categories.ctaDesc': 'Opublikuj zapytanie ofertowe, a zweryfikowani dostawcy sami się zgłoszą.',
    'action.postRequest': 'Dodaj zapytanie',
    'action.search': 'Szukaj',
    'action.newRequest': 'Nowe zapytanie',
    'action.browseMarketplace': 'Przeglądaj rynek',
    'action.findSuppliers': 'Znajdź dostawców',
    'action.viewAll': 'Zobacz wszystko',
    'action.compareOffers': 'Porównaj oferty',
    'action.quoteNow': 'Złóż ofertę',
    'action.reply': 'Odpowiedz',
    'footer.buyers': 'Kupujący',
    'footer.suppliers': 'Dostawcy',
    'footer.postRequest': 'Dodaj zapytanie',
    'footer.becomeSupplier': 'Zostań dostawcą',
    'footer.pricing': 'Opłaty i cennik',
    'footer.terms': 'Regulamin',
    'footer.privacy': 'Prywatność',
  },
  RO: {
    'nav.how': 'Cum funcționează',
    'nav.categories': 'Categorii',
    'nav.suppliers': 'Pentru furnizori',
    'nav.trust': 'Încredere și siguranță',
    'nav.marketplace': 'Piață',
    'auth.login': 'Autentificare',
    'auth.logout': 'Deconectare',
    'categories.title': 'Răsfoiește categoriile',
    'categories.browse': 'Răsfoiește',
    'categories.empty': 'Nicio categorie găsită.',
    'categories.ctaTitle': 'Nu găsiți ce aveți nevoie?',
    'categories.ctaDesc': 'Publicați o cerere și lăsați furnizorii verificați să vină la dvs.',
    'action.postRequest': 'Publică cerere',
    'action.search': 'Căutare',
    'action.newRequest': 'Cerere nouă',
    'action.browseMarketplace': 'Răsfoiește piața',
    'action.findSuppliers': 'Găsește furnizori',
    'action.viewAll': 'Vezi tot',
    'action.compareOffers': 'Compară ofertele',
    'action.quoteNow': 'Trimite ofertă',
    'action.reply': 'Răspunde',
    'footer.buyers': 'Cumpărători',
    'footer.suppliers': 'Furnizori',
    'footer.postRequest': 'Publică o cerere',
    'footer.becomeSupplier': 'Devino furnizor',
    'footer.pricing': 'Taxe și prețuri',
    'footer.terms': 'Termeni',
    'footer.privacy': 'Confidențialitate',
  },
  ZH: {
    'nav.how': '如何运作',
    'nav.aiProjects': '项目',
    'nav.categories': '品类',
    'nav.suppliers': '供应商入驻',
    'nav.trust': '信任与安全',
    'nav.marketplace': '采购市场',
    'auth.login': '登录',
    'auth.logout': '退出',
    'categories.title': '浏览品类',
    'categories.subtitle': '在全球 {count}+ 个行业中寻找已认证供应商。',
    'categories.browse': '浏览',
    'categories.empty': '暂无品类。',
    'categories.ctaTitle': '没有找到需要的商品？',
    'categories.ctaDesc': '发布采购需求，让已认证供应商主动给你报价。',
    'action.postRequest': '发布需求',
    'action.search': '搜索',
    'action.newRequest': '新建需求',
    'action.browseMarketplace': '浏览市场',
    'action.findSuppliers': '寻找供应商',
    'action.viewAll': '查看全部',
    'action.viewAllMessages': '查看全部消息',
    'action.compareOffers': '比较报价',
    'action.viewPublicProfile': '查看公开主页',
    'action.viewPings': '查看匹配需求',
    'action.quoteNow': '立即报价',
    'action.uploadProof': '上传交付凭证',
    'action.reply': '回复',
    'market.title': '采购市场',
    'market.items': '个商品',
    'market.searchPlaceholder': '搜索商品...',
    'market.allModes': '全部（B2B + B2C）',
    'market.b2bOnly': '仅 B2B',
    'market.b2cOnly': '仅 B2C',
    'market.bestMatch': '最佳匹配',
    'market.newest': '最新',
    'market.mostOrders': '订单最多',
    'market.priceAsc': '价格 ↑',
    'market.priceDesc': '价格 ↓',
    'market.originCountry': '来源国家',
    'market.allCountries': '全部国家',
    'market.sellerType': '卖家类型',
    'market.allSellers': '全部卖家',
    'market.individual': '个人 / 自由职业者',
    'market.business': '企业 / 公司',
    'market.verifiedOnly': '仅看已认证企业',
    'market.sponsored': '赞助',
    'market.recommended': '为你推荐',
    'market.official': '官方',
    'market.noProducts': '没有找到商品',
    'market.tryFilters': '可以调整筛选条件，或',
    'market.postRequestInstead': '发布需求',
    'market.couldNotLoad': '商品列表加载失败',
    'market.retry': '重试',
    'market.loading': '加载中...',
    'market.loadMore': '加载更多',
    'market.buyNow': '立即购买',
    'market.requestQuote': '请求报价',
    'market.moq': '最小起订量',
    'market.orders': '笔订单',
    'market.bannerOfficialCta': '进入 AinerWise 官网',
    'market.bannerDeckKicker': '官网推荐',
    'market.bannerDeckTitle': 'AI + KNX 专区',
    'market.bannerDeckLink': '官网主页',
    'market.banner1Kicker': 'AI + KNX',
    'market.banner1Title': 'AI 智能建筑大脑',
    'market.banner1Subtitle': '先选商品，再进入 AI 设计、BOQ、RFQ 和本地交付。',
    'market.banner1CardTitle': 'AI 智能建筑',
    'market.banner1CardText': 'KNX、能源、安防和服务。',
    'market.banner2Kicker': '智能别墅',
    'market.banner2Title': 'Villa 智能家居升级',
    'market.banner2Subtitle': '灯光、场景、门禁、能源和设备统一选购。',
    'market.banner2CardTitle': '别墅套餐',
    'market.banner2CardText': '商品加本地安装。',
    'market.banner3Kicker': '小酒店',
    'market.banner3Title': '酒店 AI 智能升级包',
    'market.banner3Subtitle': '把客房、门锁、监控和能源变成可交付的智能建筑项目。',
    'market.banner3CardTitle': '酒店升级',
    'market.banner3CardText': '客房、门禁和长期服务。',
    'project.loading': '加载中...',
    'project.loadingProject': '项目加载中...',
    'project.forge': 'AI Project Forge',
    'project.forgeDesc': '通过对话收集项目资料，可选上传文件，生成可编辑需求表单，再匹配商品和供应商报价。',
    'project.progress': '进度',
    'project.refresh': '刷新',
    'project.aiAnalyze': 'AI 分析',
    'project.refreshPrices': '刷新价格',
    'project.freezeForm': '冻结表单',
    'project.publishItems': '发布 {count} 项',
    'project.langgraphIntake': 'LangGraph 信息收集',
    'project.collectStep': '逐步收集项目资料',
    'project.chatGoalTitle': '先告诉 AI 你的项目目标',
    'project.chatGoalExample': '例如：我要在 Cebu 建 200 平米别墅，偏高端，需要钢筋、水泥、PVC、灯具等预估。',
    'project.chatPlaceholder': '描述项目、回答 AI 追问，或说明上传文件中的重点...（Ctrl+Enter 发送）',
    'project.attachFiles': '上传文件',
    'project.send': '发送',
    'project.proceed': '进入下一步',
    'project.uploading': '上传中...',
    'project.providerMissing': 'AI Provider 未配置。请管理员到 Admin → Integrations → AI Provider 配置并启用 AI Project Forge。',
    'project.oldDeepseekEndpoint': '这次失败运行使用了旧的 DeepSeek endpoint。后端现在会使用 Admin AI Provider 中配置的精确 Base URL，请重新分析。',
    'project.status.done': '完成',
    'project.status.active': '进行中',
    'project.status.pending': '待处理',
    'project.stage.goal': '定位',
    'project.stage.coreNeed': '核心需求',
    'project.stage.metrics': '指标',
    'project.stage.indicators': '项目指标',
    'project.stage.files': '资料',
    'project.stage.optional': '可选',
    'project.stage.demandModel': '需求模型',
    'project.stage.lineItems': '需求项',
    'project.stage.compare': '比价',
    'project.stage.pricing': '价格',
    'project.stage.finalReport': '最终报表',
    'project.stage.freeze': '冻结',
    'project.preview.coreNeed': '核心需求',
    'project.preview.waitGoal': '等待用户描述项目目标',
    'project.preview.projectMetrics': '项目指标',
    'project.preview.indicatorsMissing': '缺少 {count} 个指标',
    'project.preview.indicatorsCollected': '已收集 {count} 个指标',
    'project.preview.supportingFiles': '辅助资料',
    'project.preview.filesAttached': '已上传 {count} 个文件，可用于文本/多模态抽取',
    'project.preview.demandForm': '需求表格',
    'project.preview.itemsIncluded': '{items} 个项目，{included} 个参与估算',
    'project.preview.matchingQuotes': '匹配与报价',
    'project.preview.comparisonIssues': '{groups} 个比价组，{issues} 个问题待确认',
    'project.preview.frozenReady': '已冻结，可发布',
    'project.preview.waitFreeze': '等待用户确认并冻结',
    'layout.settings': '设置',
    'layout.catalogRules': '目录与规则',
    'layout.business': '业务',
    'layout.searchBuyer': '搜索需求、订单...',
    'layout.buyerAccount': '买家账户',
    'layout.companyProfile': '企业资料',
    'layout.team': '团队',
    'layout.logout': '退出登录',
    'layout.supplierBadge': '供应商',
    'layout.supplierPortal': '供应商工作台',
    'layout.onlinePings': '在线接收匹配需求',
    'layout.verifiedSupplier': '已认证供应商',
    'layout.myBusiness': '我的企业',
    'layout.shoppingFirst': '采购优先',
    'layout.marketplaceShortcutDesc': '在每个买家页面都能一键回到商品瀑布流。',
    'layout.aiProjects': '人工智能项目',
    'layout.myProfile': '我的资料',
    'layout.deliveryAddresses': '收货地址',
    'layout.notificationSettings': '通知设置',
    'layout.notifications': '通知',
    'layout.markAllRead': '全部标为已读',
    'layout.loading': '加载中...',
    'layout.noNotifications': '暂无通知',
    'layout.viewAllNotifications': '查看全部通知',
    'layout.dashboard': '仪表盘',
    'layout.ainerwiseSite': 'AinerWise 官网',
    'layout.operatingCountry': '运营国家',
    'layout.settlementCurrency': '结算币',
    'buyer.nav.dashboard': '买家仪表盘',
    'buyer.nav.marketplace': '采购市场',
    'buyer.nav.requests': '我的需求',
    'buyer.nav.orders': '订单',
    'buyer.nav.messages': '消息',
    'buyer.nav.disputes': '争议中心',
    'buyer.nav.idealList': '理想清单',
    'buyer.nav.settings': '账户设置',
    'buyer.nav.wallet': '支付台账',
    'supplier.nav.dashboard': '供应商仪表盘',
    'supplier.nav.inbox': '匹配需求',
    'supplier.nav.offers': '我的报价',
    'supplier.nav.orders': '订单与交付',
    'supplier.nav.messages': '消息',
    'supplier.nav.catalog': '商品目录',
    'supplier.nav.triggers': '匹配规则',
    'supplier.nav.payouts': '收款设置',
    'supplier.nav.reviews': '评价与信用',
    'supplier.nav.settings': '设置',
    'buyer.dashboard.title': '买家仪表盘',
    'buyer.dashboard.activeRequests': '进行中的需求',
    'buyer.dashboard.offersReceived': '收到的报价',
    'buyer.dashboard.ordersProgress': '进行中的订单',
    'buyer.dashboard.escrowHeld': '在录支付',
    'buyer.dashboard.trustTitle': '买家信用档案',
    'buyer.dashboard.trustDesc': '基于资料完整度、成交率、押金和平台风控信号计算。',
    'buyer.dashboard.shopTitle': '回到采购市场',
    'buyer.dashboard.shopDesc': '浏览商品瀑布流，按品类和区域筛选，然后直接购买或发起报价，不需要离开买家工作流。',
    'buyer.dashboard.shopPrimary': '打开采购市场',
    'buyer.dashboard.shopSecondary': '寻找可信供应商',
    'buyer.dashboard.shopStatProducts': '实时商品',
    'buyer.dashboard.shopStatModes': 'B2B + B2C',
    'buyer.dashboard.shopStatRank': '按信用、成本、距离排序',
    'trust.score': '信誉值',
    'trust.dealRate': '成交率',
    'trust.profile': '资料完整度',
    'trust.deposit': '押金',
    'trust.disputes': '争议率',
    'trust.tier.BRONZE': '青铜',
    'trust.tier.SILVER': '白银',
    'trust.tier.GOLD': '黄金',
    'trust.tier.PLATINUM': '铂金',
    'trust.tier.DIAMOND': '钻石',
    'buyer.dashboard.recentMessages': '最近消息',
    'buyer.dashboard.messagePreview': '我们可以改到周二交付吗？',
    'buyer.dashboard.recommended': '为你推荐',
    'buyer.table.requestTitle': '需求标题',
    'buyer.table.budget': '预算',
    'buyer.table.status': '状态',
    'buyer.table.offers': '报价',
    'buyer.table.actions': '操作',
    'buyer.status.receivingOffers': '接收报价中',
    'buyer.status.reviewing': '审核中',
    'supplier.dashboard.title': '供应商仪表盘',
    'supplier.dashboard.subtitle': '这里展示今天和你业务相关的关键事项。',
    'supplier.dashboard.newPings': '新匹配需求',
    'supplier.dashboard.activeOffers': '有效报价',
    'supplier.dashboard.awardedOrders': '已中标订单',
    'supplier.dashboard.pendingDelivery': '待交付',
    'supplier.dashboard.escrowPayout': '已完成订单额',
    'supplier.dashboard.responseSla': '响应时效',
    'supplier.dashboard.rating': '评分',
    'supplier.dashboard.disputeRate': '争议率',
    'supplier.dashboard.recentPings': '最近匹配需求',
    'supplier.dashboard.actionRequired': '待处理事项',
    'supplier.dashboard.away': '距离',
    'supplier.dashboard.preFunded': '已预存资金',
    'supplier.dashboard.budget': '预算',
    'supplier.dashboard.deliveryProof': '上传交付凭证',
    'supplier.dashboard.deliveryProofDesc': '订单 #ORD-99120 已标记为发货。请上传交付凭证，便于买家释放托管资金。',
    'supplier.dashboard.unreadMessage': '买家未读消息',
    'supplier.dashboard.unreadMessageDesc': '关于 "Marine Engine Parts" 的报价 #OFF-4412。',
    'buyer.settings.title': '买家设置',
    'buyer.settings.subtitle': '管理与买家账户关联的收货地址、提醒渠道和联系方式。',
    'buyer.settings.auditNotice': '站内聊天记录和交易记录仍然是争议与审计的权威来源。',
    'buyer.settings.guardTitle': '提醒渠道是可选的，订单凭证是必须的。',
    'buyer.settings.guardDesc': '电子邮件、Telegram、WhatsApp 和 Viber 可以让你快速回到平台上，但消息、承诺和结算敏感细节始终保留在站内。',
    'buyer.settings.contactTitle': '客户联系人',
    'buyer.settings.contactDesc': '请确保买家身份信息和回电详情是最新的。',
    'buyer.settings.fullName': '姓名',
    'buyer.settings.fullNamePlaceholder': '买方名称',
    'buyer.settings.mobile': '手机号码',
    'buyer.settings.email': '电子邮件',
    'buyer.settings.telegram': 'Telegram 聊天 ID',
    'buyer.settings.telegramPlaceholder': '可选：@用户名或聊天 ID',
    'buyer.settings.whatsapp': 'WhatsApp 号码',
    'buyer.settings.whatsappPlaceholder': '可选：+381...',
    'buyer.settings.viber': 'Viber 号码',
    'buyer.settings.viberPlaceholder': '可选：+381...',
    'buyer.settings.saveContact': '保存联系方式',
    'buyer.settings.addressTitle': '收货地址簿',
    'buyer.settings.addressDesc': '这些是买家在结账时可以快速切换的收货地址。',
    'buyer.settings.loadingAddresses': '正在加载地址...',
    'buyer.settings.noAddress': '还没有收货地址。请添加常用仓库、现场办公室或交付点。',
    'buyer.settings.default': '默认',
    'buyer.settings.edit': '编辑',
    'buyer.settings.setDefault': '设为默认',
    'buyer.settings.delete': '删除',
    'buyer.settings.editAddress': '编辑收货地址',
    'buyer.settings.addAddress': '新增收货地址',
    'buyer.settings.addressLabelPlaceholder': '标签：主仓库',
    'buyer.settings.receiverNamePlaceholder': '收货人姓名',
    'buyer.settings.receiverPhonePlaceholder': '收货人电话',
    'buyer.settings.cityPlaceholder': '城市',
    'buyer.settings.addressLinePlaceholder': '地址第一行',
    'buyer.settings.postalPlaceholder': '邮政编码',
    'buyer.settings.cancel': '取消',
    'buyer.settings.saveAddress': '保存地址',
    'buyer.settings.addAddressButton': '添加地址',
    'buyer.settings.notificationsTitle': '通知设置',
    'buyer.settings.notificationsDesc': '选择允许哪些提醒渠道把你拉回站内工作流。',
    'buyer.settings.reminderChannels': '提醒渠道',
    'buyer.settings.emailReminder': '电子邮件提醒',
    'buyer.settings.emailReminderDesc': '当有新消息、订单变更或供应商回复需要关注时发送摘要。',
    'buyer.settings.telegramReminder': 'Telegram 提醒',
    'buyer.settings.telegramReminderDesc': '仅当上方保存了 Telegram 聊天 ID 时才启用。',
    'buyer.settings.whatsappReminder': 'WhatsApp 提醒',
    'buyer.settings.whatsappReminderDesc': '仅当上方保存了 WhatsApp 号码时才启用。',
    'buyer.settings.viberReminder': 'Viber 提醒',
    'buyer.settings.viberReminderDesc': '仅当上方保存了 Viber 号码时才启用。',
    'buyer.settings.eventTriggers': '事件触发器',
    'buyer.settings.event.newMessage': '新的站内消息',
    'buyer.settings.event.newMessageDesc': '当供应商在影响进行中订单或报价的讨论中回复时，请提醒我。',
    'buyer.settings.event.intentMatch': '需求匹配',
    'buyer.settings.event.intentMatchDesc': '当我发布的购买需求在市场上出现新的匹配项时，请通知我。',
    'buyer.settings.event.offerReceived': '收到新报价',
    'buyer.settings.event.offerReceivedDesc': '当供应商提交明确报价时通知我。',
    'buyer.settings.event.offerAwarded': '授标后续提醒',
    'buyer.settings.event.offerAwardedDesc': '当已授标流程需要后续操作时提醒我。',
    'buyer.settings.event.orderUpdate': '订单状态更新',
    'buyer.settings.event.orderUpdateDesc': '付款、验收和订单进度变化需要快速把我拉回平台。',
    'buyer.settings.event.deliveryUpdate': '交付更新',
    'buyer.settings.event.deliveryUpdateDesc': '当发货或到达状态发生变化时提醒我。',
    'buyer.settings.saveNotifications': '保存通知设置',
    'buyer.settings.profileUpdated': '买家资料已更新',
    'buyer.settings.profileFailed': '买家资料更新失败',
    'buyer.settings.notificationsUpdated': '通知设置已更新',
    'buyer.settings.notificationsFailed': '通知设置更新失败',
    'buyer.settings.addressUpdated': '地址簿已更新',
    'buyer.settings.addressFailed': '地址保存失败',
    'buyer.settings.defaultAddressUpdated': '默认地址已更新',
    'buyer.settings.defaultAddressFailed': '默认地址更新失败',
    'buyer.settings.addressRemoved': '地址已移除',
    'buyer.settings.addressRemoveFailed': '地址移除失败',
    'wallet.title': '支付账簿',
    'wallet.subtitle': '您的订单付款记录清晰可见。AinerWise Market 绝不会持有您的资金。',
    'wallet.refresh': '刷新',
    'wallet.directTitle': '直接支付方式',
    'wallet.directDesc': '您根据双方商定的阶段性付款计划直接向供应商付款。此页面保留付款记录、凭证、参考信息和结算状态。',
    'wallet.recordedPayments': '已记录的付款',
    'wallet.recordedDesc': '您在订单上记录的直接付款',
    'wallet.settled': '已结算',
    'wallet.settledDesc': '已确认交付并已结束',
    'wallet.awaiting': '待付款记录',
    'wallet.awaitingDesc': '未记录付款的订单',
    'wallet.orderRecords': '订单付款记录',
    'wallet.records': '条记录',
    'wallet.historical': '历史账户记录',
    'wallet.historicalDesc': '来自旧余额系统的只读历史记录。',
    'wallet.column.order': '订单',
    'wallet.column.date': '日期',
    'wallet.column.amount': '金额',
    'wallet.column.status': '状态',
    'wallet.column.reference': '参考',
    'wallet.column.description': '描述',
    'wallet.status.AWAITING_PAYMENT': '等待付款记录',
    'wallet.status.PAID_IN_ESCROW': '已记录付款',
    'wallet.status.IN_PROGRESS': '进行中',
    'wallet.status.DELIVERED': '已交付',
    'wallet.status.ACCEPTED': '已完成',
    'wallet.status.PAYOUT_RELEASED': '已结算',
    'wallet.status.DISPUTED': '争议中',
    'wallet.status.CANCELED': '已取消',
    'wallet.status.CREATED': '已创建',
    'wallet.currencyNote': '当前汇总按顶部选择的币种显示。其它币种订单会单独保留，不会混入这个总数。',
    'wallet.localReference': '本地参考：',
    'buyer.notifications.title': '通知',
    'buyer.notifications.subtitle': '买家关于新报价、订单更新、争议和消息的提醒。',
    'buyer.notifications.loading': '正在加载通知...',
    'buyer.notifications.empty': '暂无通知。',
    'buyer.notifications.new': '新',
    'buyer.notifications.type.NEW_OFFER_FOR_BUYER': '收到新报价',
    'buyer.notifications.type.OFFER_UPDATED_BUYER': '报价已更新',
    'buyer.notifications.type.ORDER_CREATED_BUYER': '订单已创建',
    'buyer.notifications.type.DELIVERY_UPDATED_BUYER': '交付已更新',
    'buyer.notifications.type.DISPUTE_OPENED': '争议已开启',
    'buyer.notifications.type.MESSAGE_RECEIVED': '新消息',
    'buyer.notifications.type.ADMIN_TEST': '管理员通知',
    'time.justNow': '刚刚',
    'footer.buyers': '买家',
    'footer.suppliers': '供应商',
    'footer.settings': '设置',
    'footer.postRequest': '发布需求',
    'footer.escrow': '买家保障',
    'footer.becomeSupplier': '成为供应商',
    'footer.pricing': '费用与定价',
    'footer.verification': '供应商认证',
    'footer.terms': '条款',
    'footer.privacy': '隐私',
  },
  SR: {
    'nav.how': 'Kako radi',
    'nav.categories': 'Kategorije',
    'nav.suppliers': 'Za dobavljace',
    'nav.trust': 'Poverenje i bezbednost',
    'nav.marketplace': 'Trziste',
    'auth.login': 'Prijava',
    'auth.logout': 'Odjava',
    'categories.title': 'Pregled kategorija',
    'categories.subtitle': 'Pronadjite proverene dobavljace za {count}+ industrija.',
    'categories.browse': 'Pregled',
    'categories.empty': 'Nema kategorija.',
    'categories.ctaTitle': 'Ne nalazite sta vam treba?',
    'categories.ctaDesc': 'Objavite zahtev i provereni dobavljaci ce vam poslati ponude.',
    'action.postRequest': 'Objavi zahtev',
    'action.search': 'Pretrazi',
    'action.newRequest': 'Novi zahtev',
    'action.browseMarketplace': 'Otvori trziste',
    'action.findSuppliers': 'Pronadji dobavljace',
    'action.viewAll': 'Prikazi sve',
    'action.viewAllMessages': 'Prikazi sve poruke',
    'action.compareOffers': 'Uporedi ponude',
    'action.viewPublicProfile': 'Javni profil',
    'action.viewPings': 'Pogledaj pingove',
    'action.quoteNow': 'Posalji ponudu',
    'action.uploadProof': 'Dodaj dokaz',
    'action.reply': 'Odgovori',
    'market.title': 'Trziste',
    'market.items': 'stavki',
    'market.searchPlaceholder': 'Pretrazi proizvode...',
    'market.allModes': 'Sve (B2B + B2C)',
    'market.b2bOnly': 'Samo B2B',
    'market.b2cOnly': 'Samo B2C',
    'market.bestMatch': 'Najbolje poklapanje',
    'market.newest': 'Najnovije',
    'market.mostOrders': 'Najvise porudzbina',
    'market.priceAsc': 'Cena ↑',
    'market.priceDesc': 'Cena ↓',
    'market.originCountry': 'Zemlja porekla',
    'market.allCountries': 'Sve zemlje',
    'market.sellerType': 'Tip prodavca',
    'market.allSellers': 'Svi prodavci',
    'market.individual': 'Pojedinac / Freelancer',
    'market.business': 'Firma / Kompanija',
    'market.verifiedOnly': 'Samo proverene firme',
    'market.sponsored': 'Sponzorisano',
    'market.recommended': 'Preporuceno za vas',
    'market.official': 'Zvanicno',
    'market.noProducts': 'Nema pronadjenih proizvoda',
    'market.tryFilters': 'Promenite filtere ili',
    'market.postRequestInstead': 'objavite zahtev',
    'market.couldNotLoad': 'Nije moguce ucitati proizvode',
    'market.retry': 'Pokusaj ponovo',
    'market.loading': 'Ucitavanje...',
    'market.loadMore': 'Ucitaj jos',
    'market.buyNow': 'Kupi sada',
    'market.requestQuote': 'Zatrazi ponudu',
    'market.moq': 'MOQ',
    'market.orders': 'porudzbina',
    'market.bannerOfficialCta': 'Otvori AinerWise sajt',
    'market.bannerDeckKicker': 'Zvanicni fokus',
    'market.bannerDeckTitle': 'AI + KNX ponude',
    'market.bannerDeckLink': 'Zvanicni sajt',
    'market.banner1Kicker': 'AI + KNX',
    'market.banner1Title': 'AI mozak zgrade',
    'market.banner1Subtitle': 'Prvo kupovina proizvoda, zatim AI dizajn, BOQ, RFQ i isporuka.',
    'market.banner1CardTitle': 'AI zgrada',
    'market.banner1CardText': 'KNX, energija, bezbednost i servis.',
    'market.banner2Kicker': 'Smart villa',
    'market.banner2Title': 'Smart home upgrade za vilu',
    'market.banner2Subtitle': 'Rasveta, scene, pristup, energija i uredjaji na jednom mestu.',
    'market.banner2CardTitle': 'Villa paket',
    'market.banner2CardText': 'Proizvodi plus lokalna instalacija.',
    'market.banner3Kicker': 'Mali hotel',
    'market.banner3Title': 'Hotelski AI upgrade kit',
    'market.banner3Subtitle': 'Sobe, brave, CCTV i energija kao vodjen smart-building projekat.',
    'market.banner3CardTitle': 'Hotel upgrade',
    'market.banner3CardText': 'Sobe, pristup i servis.',
    'layout.settings': 'Podesavanja',
    'layout.catalogRules': 'Katalog i pravila',
    'layout.business': 'Poslovanje',
    'layout.searchBuyer': 'Pretrazi zahteve, porudzbine...',
    'layout.buyerAccount': 'Nalog kupca',
    'layout.companyProfile': 'Profil firme',
    'layout.team': 'Tim',
    'layout.logout': 'Odjava',
    'layout.supplierBadge': 'DOBAVLJAC',
    'layout.supplierPortal': 'Portal dobavljaca',
    'layout.onlinePings': 'Online i prima upite',
    'layout.verifiedSupplier': 'Proveren dobavljac',
    'layout.myBusiness': 'Moje poslovanje',
    'layout.shoppingFirst': 'Kupovina prvo',
    'layout.marketplaceShortcutDesc': 'Nabavka je dostupna jednim klikom sa svake buyer stranice.',
    'layout.operatingCountry': 'Zemlja poslovanja',
    'layout.settlementCurrency': 'Valuta obracuna',
    'buyer.nav.dashboard': 'Kontrolna tabla',
    'buyer.nav.marketplace': 'Trziste',
    'buyer.nav.requests': 'Moji zahtevi',
    'buyer.nav.orders': 'Porudzbine',
    'buyer.nav.messages': 'Poruke',
    'buyer.nav.disputes': 'Centar za sporove',
    'buyer.nav.idealList': 'Idealna lista',
    'buyer.nav.settings': 'Podesavanja naloga',
    'buyer.nav.wallet': 'Novcanik i escrow',
    'supplier.nav.dashboard': 'Kontrolna tabla',
    'supplier.nav.inbox': 'Inbox upita',
    'supplier.nav.offers': 'Moje ponude',
    'supplier.nav.orders': 'Porudzbine i isporuka',
    'supplier.nav.messages': 'Poruke',
    'supplier.nav.catalog': 'Moj katalog',
    'supplier.nav.triggers': 'Pravila poklapanja',
    'supplier.nav.payouts': 'Podesavanja isplata',
    'supplier.nav.reviews': 'Ocene i poverenje',
    'supplier.nav.settings': 'Podesavanja',
    'buyer.dashboard.title': 'Kontrolna tabla kupca',
    'buyer.dashboard.activeRequests': 'Aktivni zahtevi',
    'buyer.dashboard.offersReceived': 'Primljene ponude',
    'buyer.dashboard.ordersProgress': 'Porudzbine u toku',
    'buyer.dashboard.escrowHeld': 'Escrow sredstva',
    'buyer.dashboard.trustTitle': 'Profil poverenja kupca',
    'buyer.dashboard.trustDesc': 'Na osnovu popunjenosti profila, zavrsenih poslova, depozita i rizika platforme.',
    'buyer.dashboard.shopTitle': 'Nazad na nabavku',
    'buyer.dashboard.shopDesc': 'Pregledajte proizvode, filtrirajte po kategoriji i regionu, pa kupite ili zatrazite ponudu.',
    'buyer.dashboard.shopPrimary': 'Otvori trziste',
    'buyer.dashboard.shopSecondary': 'Pronadji proverene dobavljace',
    'buyer.dashboard.shopStatProducts': 'Aktivni proizvodi',
    'buyer.dashboard.shopStatModes': 'B2B + B2C',
    'buyer.dashboard.shopStatRank': 'Rang po poverenju, ceni i udaljenosti',
    'trust.score': 'Skor',
    'trust.dealRate': 'Stopa poslova',
    'trust.profile': 'Profil',
    'trust.deposit': 'Depozit',
    'trust.disputes': 'Sporovi',
    'trust.tier.BRONZE': 'Bronza',
    'trust.tier.SILVER': 'Srebro',
    'trust.tier.GOLD': 'Zlato',
    'trust.tier.PLATINUM': 'Platina',
    'trust.tier.DIAMOND': 'Dijamant',
    'buyer.dashboard.recentMessages': 'Skorasnje poruke',
    'buyer.dashboard.messagePreview': 'Mozemo li isporuku pomeriti na utorak?',
    'buyer.dashboard.recommended': 'Preporuceno za vas',
    'buyer.table.requestTitle': 'Naslov zahteva',
    'buyer.table.budget': 'Budzet',
    'buyer.table.status': 'Status',
    'buyer.table.offers': 'Ponude',
    'buyer.table.actions': 'Akcije',
    'buyer.status.receivingOffers': 'Prima ponude',
    'buyer.status.reviewing': 'U pregledu',
    'wallet.localReference': 'Lokalna referenca:',
    'footer.buyers': 'Kupci',
    'footer.suppliers': 'Dobavljaci',
    'footer.settings': 'Podesavanja',
    'footer.postRequest': 'Objavi zahtev',
    'footer.escrow': 'Escrow zastita',
    'footer.becomeSupplier': 'Postani dobavljac',
    'footer.pricing': 'Naknade',
    'footer.verification': 'Verifikacija dobavljaca',
    'footer.terms': 'Uslovi',
    'footer.privacy': 'Privatnost',
  },
  JA: {
    'nav.how': '使い方',
    'nav.categories': 'カテゴリ',
    'nav.suppliers': 'サプライヤー向け',
    'nav.trust': '信頼と安全',
    'auth.login': 'ログイン',
    'action.postRequest': '依頼を投稿',
    'action.newRequest': '新しい依頼',
    'action.viewAll': 'すべて表示',
    'action.viewAllMessages': 'すべてのメッセージを表示',
    'action.compareOffers': '見積もりを比較',
    'action.viewPublicProfile': '公開プロフィールを表示',
    'action.viewPings': 'マッチングを確認',
    'action.quoteNow': '今すぐ見積もり',
    'action.uploadProof': '証明書をアップロード',
    'action.reply': '返信',
    'layout.settings': '設定',
    'layout.catalogRules': 'カタログとルール',
    'layout.business': 'ビジネス',
    'layout.searchBuyer': '依頼・注文を検索...',
    'layout.buyerAccount': 'バイヤーアカウント',
    'layout.companyProfile': '会社プロフィール',
    'layout.team': 'チーム',
    'layout.logout': 'ログアウト',
    'layout.supplierBadge': 'サプライヤー',
    'layout.supplierPortal': 'サプライヤーポータル',
    'layout.onlinePings': 'オンライン・マッチング受信中',
    'layout.verifiedSupplier': '認証済みサプライヤー',
    'layout.myBusiness': '私のビジネス',
    'buyer.nav.dashboard': 'ダッシュボード',
    'buyer.nav.requests': '依頼一覧',
    'buyer.nav.orders': '注文',
    'buyer.nav.messages': 'メッセージ',
    'buyer.nav.disputes': '紛争センター',
    'buyer.nav.idealList': '希望リスト',
    'buyer.nav.settings': 'アカウント設定',
    'buyer.nav.wallet': '財布とエスクロー',
    'supplier.nav.dashboard': 'ダッシュボード',
    'supplier.nav.inbox': 'マッチング受信箱',
    'supplier.nav.offers': '見積もり一覧',
    'supplier.nav.orders': '注文と配送',
    'supplier.nav.messages': 'メッセージ',
    'supplier.nav.catalog': 'カタログ',
    'supplier.nav.triggers': 'マッチングルール',
    'supplier.nav.payouts': '支払い設定',
    'supplier.nav.reviews': 'レビューと信頼',
    'supplier.nav.settings': '設定',
    'buyer.dashboard.title': 'バイヤーダッシュボード',
    'buyer.dashboard.activeRequests': '進行中の依頼',
    'buyer.dashboard.offersReceived': '受信済み見積もり',
    'buyer.dashboard.ordersProgress': '進行中の注文',
    'buyer.dashboard.escrowHeld': 'エスクロー保管中',
    'buyer.dashboard.trustTitle': 'バイヤー信頼プロフィール',
    'buyer.dashboard.trustDesc': 'プロフィール完成度、成約率、保証金、プラットフォームリスクシグナルに基づいて算出。',
    'trust.score': 'スコア',
    'trust.dealRate': '成約率',
    'trust.profile': 'プロフィール',
    'trust.deposit': '保証金',
    'trust.disputes': '紛争',
    'trust.tier.BRONZE': 'ブロンズ',
    'trust.tier.SILVER': 'シルバー',
    'trust.tier.GOLD': 'ゴールド',
    'trust.tier.PLATINUM': 'プラチナ',
    'trust.tier.DIAMOND': 'ダイヤモンド',
    'buyer.dashboard.recentMessages': '最近のメッセージ',
    'buyer.dashboard.messagePreview': '火曜日に配達に変更できますか？',
    'buyer.dashboard.recommended': 'おすすめ',
    'buyer.table.requestTitle': '依頼タイトル',
    'buyer.table.budget': '予算',
    'buyer.table.status': 'ステータス',
    'buyer.table.offers': '見積もり',
    'buyer.table.actions': 'アクション',
    'buyer.status.receivingOffers': '見積もり受付中',
    'buyer.status.reviewing': '審査中',
    'supplier.dashboard.title': 'サプライヤーダッシュボード',
    'supplier.dashboard.subtitle': '今日のビジネス状況をご確認ください。',
    'supplier.dashboard.newPings': '新着マッチング',
    'supplier.dashboard.activeOffers': '有効な見積もり',
    'supplier.dashboard.awardedOrders': '受注済み注文',
    'supplier.dashboard.pendingDelivery': '配送待ち',
    'supplier.dashboard.escrowPayout': 'エスクロー精算待ち',
    'supplier.dashboard.responseSla': '応答時間SLA',
    'supplier.dashboard.rating': '評価',
    'supplier.dashboard.disputeRate': '紛争率',
    'supplier.dashboard.recentPings': '最近のマッチング',
    'supplier.dashboard.actionRequired': '要対応',
    'supplier.dashboard.away': '離れています',
    'supplier.dashboard.preFunded': '前払い済み',
    'supplier.dashboard.budget': '予算',
    'supplier.dashboard.deliveryProof': '配送証明をアップロード',
    'supplier.dashboard.deliveryProofDesc': '注文 #ORD-99120 が発送済みとしてマークされました。買い手が資金を解放できるよう配送証明をアップロードしてください。',
    'supplier.dashboard.unreadMessage': '買い手からの未読メッセージ',
    'supplier.dashboard.unreadMessageDesc': '"Marine Engine Parts" の見積もり #OFF-4412 について。',
    'footer.buyers': 'バイヤー',
    'footer.suppliers': 'サプライヤー',
    'footer.settings': '設定',
    'footer.postRequest': '依頼を投稿',
    'footer.escrow': 'エスクロー保護',
    'footer.becomeSupplier': 'サプライヤー登録',
    'footer.pricing': '料金',
    'footer.verification': 'サプライヤー認証',
    'footer.terms': '利用規約',
    'footer.privacy': 'プライバシー',
  },
  ES: {
    'nav.how': 'Como funciona',
    'nav.categories': 'Categorias',
    'nav.suppliers': 'Para proveedores',
    'nav.trust': 'Confianza y seguridad',
    'auth.login': 'Iniciar sesion',
    'action.postRequest': 'Publicar solicitud',
    'footer.buyers': 'Compradores',
    'footer.suppliers': 'Proveedores',
    'footer.settings': 'Ajustes',
    'footer.postRequest': 'Publicar solicitud',
    'footer.escrow': 'Proteccion escrow',
    'footer.becomeSupplier': 'Ser proveedor',
    'footer.pricing': 'Tarifas',
    'footer.verification': 'Verificacion de proveedor',
    'footer.terms': 'Terminos',
    'footer.privacy': 'Privacidad',
  },
  TL: {
    'nav.how': 'Paano ito gumagana',
    'nav.categories': 'Mga Kategorya',
    'nav.suppliers': 'Para sa mga Supplier',
    'nav.trust': 'Tiwala at Kaligtasan',
    'auth.login': 'Mag-login',
    'action.postRequest': 'Mag-post ng Kahilingan',
    'action.newRequest': 'Bagong Kahilingan',
    'action.viewAll': 'Tingnan lahat',
    'action.viewAllMessages': 'Tingnan lahat ng mensahe',
    'action.compareOffers': 'Ikumpara ang Alok',
    'action.viewPublicProfile': 'Tingnan ang Pampublikong Profile',
    'action.viewPings': 'Tingnan ang mga Ping',
    'action.quoteNow': 'Mag-quote Ngayon',
    'action.uploadProof': 'Mag-upload ng Patunay',
    'action.reply': 'Tumugon',
    'layout.settings': 'Mga Setting',
    'layout.catalogRules': 'Katalogo at Mga Patakaran',
    'layout.business': 'Negosyo',
    'layout.searchBuyer': 'Maghanap ng kahilingan, order...',
    'layout.buyerAccount': 'Account ng Mamimili',
    'layout.companyProfile': 'Profile ng Kumpanya',
    'layout.team': 'Koponan',
    'layout.logout': 'Mag-logout',
    'layout.supplierBadge': 'SUPPLIER',
    'layout.supplierPortal': 'Portal ng Supplier',
    'layout.onlinePings': 'Online at Tumatanggap ng Ping',
    'layout.verifiedSupplier': 'Verified na Supplier',
    'layout.myBusiness': 'Aking Negosyo',
    'buyer.nav.dashboard': 'Dashboard',
    'buyer.nav.requests': 'Aking mga Kahilingan',
    'buyer.nav.orders': 'Mga Order',
    'buyer.nav.messages': 'Mga Mensahe',
    'buyer.nav.disputes': 'Sentro ng Dispute',
    'buyer.nav.idealList': 'Ideal na Listahan',
    'buyer.nav.settings': 'Mga Setting ng Account',
    'buyer.nav.wallet': 'Pitaka at Escrow',
    'supplier.nav.dashboard': 'Dashboard',
    'supplier.nav.inbox': 'Ping Inbox',
    'supplier.nav.offers': 'Aking mga Alok',
    'supplier.nav.orders': 'Mga Order at Paghahatid',
    'supplier.nav.messages': 'Mga Mensahe',
    'supplier.nav.catalog': 'Aking Katalogo',
    'supplier.nav.triggers': 'Matching Triggers',
    'supplier.nav.payouts': 'Mga Setting ng Bayad',
    'supplier.nav.reviews': 'Mga Review at Tiwala',
    'supplier.nav.settings': 'Mga Setting',
    'buyer.dashboard.title': 'Dashboard ng Mamimili',
    'buyer.dashboard.activeRequests': 'Mga Aktibong Kahilingan',
    'buyer.dashboard.offersReceived': 'Mga Natanggap na Alok',
    'buyer.dashboard.ordersProgress': 'Mga Order sa Proseso',
    'buyer.dashboard.escrowHeld': 'Nakatago sa Escrow',
    'trust.score': 'Puntos',
    'trust.dealRate': 'Rate ng Deal',
    'trust.profile': 'Profile',
    'trust.deposit': 'Deposito',
    'trust.disputes': 'Mga Dispute',
    'footer.buyers': 'Mga Mamimili',
    'footer.suppliers': 'Mga Supplier',
    'footer.settings': 'Mga Setting',
    'footer.postRequest': 'Mag-post ng Kahilingan',
    'footer.escrow': 'Proteksyon ng Escrow',
    'footer.becomeSupplier': 'Maging Supplier',
    'footer.pricing': 'Bayad at Presyo',
    'footer.verification': 'Verification ng Supplier',
    'footer.terms': 'Mga Tuntunin',
    'footer.privacy': 'Privacy',
  },
  KO: {
    'nav.how': '이용 방법',
    'nav.categories': '카테고리',
    'nav.suppliers': '공급업체 등록',
    'nav.trust': '신뢰 및 안전',
    'auth.login': '로그인',
    'action.postRequest': '요청 등록',
    'action.newRequest': '새 요청',
    'action.viewAll': '모두 보기',
    'action.viewAllMessages': '모든 메시지 보기',
    'action.compareOffers': '견적 비교',
    'action.viewPublicProfile': '공개 프로필 보기',
    'action.viewPings': '매칭 보기',
    'action.quoteNow': '지금 견적',
    'action.uploadProof': '증빙 업로드',
    'action.reply': '답장',
    'layout.settings': '설정',
    'layout.catalogRules': '카탈로그 및 규칙',
    'layout.business': '비즈니스',
    'layout.searchBuyer': '요청, 주문 검색...',
    'layout.buyerAccount': '구매자 계정',
    'layout.companyProfile': '회사 프로필',
    'layout.team': '팀',
    'layout.logout': '로그아웃',
    'layout.supplierBadge': '공급업체',
    'layout.supplierPortal': '공급업체 포털',
    'layout.onlinePings': '온라인 및 핑 수신 중',
    'layout.verifiedSupplier': '인증된 공급업체',
    'layout.myBusiness': '내 비즈니스',
    'buyer.nav.dashboard': '대시보드',
    'buyer.nav.requests': '내 요청',
    'buyer.nav.orders': '주문',
    'buyer.nav.messages': '메시지',
    'buyer.nav.disputes': '분쟁 센터',
    'buyer.nav.idealList': '이상적 목록',
    'buyer.nav.settings': '계정 설정',
    'buyer.nav.wallet': '지갑 및 에스크로',
    'supplier.nav.dashboard': '대시보드',
    'supplier.nav.inbox': '핑 받은편지함',
    'supplier.nav.offers': '내 견적',
    'supplier.nav.orders': '주문 및 배송',
    'supplier.nav.messages': '메시지',
    'supplier.nav.catalog': '내 카탈로그',
    'supplier.nav.triggers': '매칭 트리거',
    'supplier.nav.payouts': '출금 설정',
    'supplier.nav.reviews': '리뷰 및 신뢰',
    'supplier.nav.settings': '설정',
    'buyer.dashboard.title': '구매자 대시보드',
    'buyer.dashboard.activeRequests': '활성 요청',
    'buyer.dashboard.offersReceived': '받은 견적',
    'buyer.dashboard.ordersProgress': '진행 중인 주문',
    'buyer.dashboard.escrowHeld': '에스크로 보관',
    'trust.score': '점수',
    'trust.dealRate': '거래 성사율',
    'trust.profile': '프로필',
    'trust.deposit': '보증금',
    'trust.disputes': '분쟁',
    'footer.buyers': '구매자',
    'footer.suppliers': '공급업체',
    'footer.settings': '설정',
    'footer.postRequest': '요청 등록',
    'footer.escrow': '에스크로 보호',
    'footer.becomeSupplier': '공급업체 등록',
    'footer.pricing': '요금 안내',
    'footer.verification': '공급업체 인증',
    'footer.terms': '이용약관',
    'footer.privacy': '개인정보처리방침',
  },
  TH: {
    'nav.how': 'วิธีการใช้งาน',
    'nav.categories': 'หมวดหมู่',
    'nav.suppliers': 'สำหรับผู้จัดหา',
    'nav.trust': 'ความน่าเชื่อถือและความปลอดภัย',
    'auth.login': 'เข้าสู่ระบบ',
    'action.postRequest': 'โพสต์คำขอ',
    'action.newRequest': 'คำขอใหม่',
    'action.viewAll': 'ดูทั้งหมด',
    'action.viewAllMessages': 'ดูข้อความทั้งหมด',
    'action.compareOffers': 'เปรียบเทียบข้อเสนอ',
    'action.viewPublicProfile': 'ดูโปรไฟล์สาธารณะ',
    'action.viewPings': 'ดูการจับคู่',
    'action.quoteNow': 'เสนอราคาตอนนี้',
    'action.uploadProof': 'อัปโหลดหลักฐาน',
    'action.reply': 'ตอบกลับ',
    'layout.settings': 'การตั้งค่า',
    'layout.logout': 'ออกจากระบบ',
    'layout.supplierPortal': 'พอร์ทัลผู้จัดหา',
    'buyer.nav.dashboard': 'แดชบอร์ด',
    'buyer.nav.requests': 'คำขอของฉัน',
    'buyer.nav.orders': 'คำสั่งซื้อ',
    'buyer.nav.messages': 'ข้อความ',
    'buyer.nav.disputes': 'ศูนย์ข้อพิพาท',
    'buyer.nav.wallet': 'กระเป๋าเงินและเอสโครว์',
    'supplier.nav.dashboard': 'แดชบอร์ด',
    'supplier.nav.inbox': 'กล่องข้อความ Ping',
    'supplier.nav.orders': 'คำสั่งซื้อและการจัดส่ง',
    'supplier.nav.catalog': 'แคตตาล็อกของฉัน',
    'buyer.dashboard.title': 'แดชบอร์ดผู้ซื้อ',
    'trust.score': 'คะแนน',
    'trust.dealRate': 'อัตราการทำข้อตกลง',
    'footer.buyers': 'ผู้ซื้อ',
    'footer.suppliers': 'ผู้จัดหา',
    'footer.terms': 'ข้อกำหนด',
    'footer.privacy': 'ความเป็นส่วนตัว',
  },
  VI: {
    'nav.how': 'Cách hoạt động',
    'nav.categories': 'Danh mục',
    'nav.suppliers': 'Cho nhà cung cấp',
    'nav.trust': 'Tin cậy & An toàn',
    'auth.login': 'Đăng nhập',
    'action.postRequest': 'Đăng yêu cầu',
    'action.newRequest': 'Yêu cầu mới',
    'action.viewAll': 'Xem tất cả',
    'action.viewAllMessages': 'Xem tất cả tin nhắn',
    'action.compareOffers': 'So sánh báo giá',
    'action.viewPublicProfile': 'Xem hồ sơ công khai',
    'action.viewPings': 'Xem ghép nối',
    'action.quoteNow': 'Báo giá ngay',
    'action.uploadProof': 'Tải bằng chứng',
    'action.reply': 'Trả lời',
    'layout.settings': 'Cài đặt',
    'layout.logout': 'Đăng xuất',
    'layout.supplierPortal': 'Cổng nhà cung cấp',
    'buyer.nav.dashboard': 'Tổng quan',
    'buyer.nav.requests': 'Yêu cầu của tôi',
    'buyer.nav.orders': 'Đơn hàng',
    'buyer.nav.messages': 'Tin nhắn',
    'buyer.nav.disputes': 'Trung tâm tranh chấp',
    'buyer.nav.wallet': 'Ví & Escrow',
    'supplier.nav.dashboard': 'Tổng quan',
    'supplier.nav.inbox': 'Hộp thư Ping',
    'supplier.nav.orders': 'Đơn hàng & Giao hàng',
    'supplier.nav.catalog': 'Danh mục của tôi',
    'buyer.dashboard.title': 'Tổng quan người mua',
    'trust.score': 'Điểm',
    'trust.dealRate': 'Tỷ lệ giao dịch',
    'footer.buyers': 'Người mua',
    'footer.suppliers': 'Nhà cung cấp',
    'footer.terms': 'Điều khoản',
    'footer.privacy': 'Quyền riêng tư',
  },
  ID: {
    'nav.how': 'Cara Kerja',
    'nav.categories': 'Kategori',
    'nav.suppliers': 'Untuk Pemasok',
    'nav.trust': 'Kepercayaan & Keamanan',
    'auth.login': 'Masuk',
    'action.postRequest': 'Posting Permintaan',
    'action.newRequest': 'Permintaan Baru',
    'action.viewAll': 'Lihat semua',
    'action.viewAllMessages': 'Lihat semua pesan',
    'action.compareOffers': 'Bandingkan Penawaran',
    'action.viewPublicProfile': 'Lihat Profil Publik',
    'action.viewPings': 'Lihat Pencocokan',
    'action.quoteNow': 'Minta Penawaran',
    'action.uploadProof': 'Unggah Bukti',
    'action.reply': 'Balas',
    'layout.settings': 'Pengaturan',
    'layout.logout': 'Keluar',
    'layout.supplierPortal': 'Portal Pemasok',
    'buyer.nav.dashboard': 'Dasbor',
    'buyer.nav.requests': 'Permintaan Saya',
    'buyer.nav.orders': 'Pesanan',
    'buyer.nav.messages': 'Pesan',
    'buyer.nav.disputes': 'Pusat Sengketa',
    'buyer.nav.wallet': 'Dompet & Escrow',
    'supplier.nav.dashboard': 'Dasbor',
    'supplier.nav.inbox': 'Kotak Masuk Ping',
    'supplier.nav.orders': 'Pesanan & Pengiriman',
    'supplier.nav.catalog': 'Katalog Saya',
    'buyer.dashboard.title': 'Dasbor Pembeli',
    'trust.score': 'Skor',
    'trust.dealRate': 'Tingkat Transaksi',
    'footer.buyers': 'Pembeli',
    'footer.suppliers': 'Pemasok',
    'footer.terms': 'Ketentuan',
    'footer.privacy': 'Privasi',
  },
  AR: {
    'nav.how': 'كيف يعمل',
    'nav.categories': 'الفئات',
    'nav.suppliers': 'للموردين',
    'nav.trust': 'الثقة والسلامة',
    'auth.login': 'تسجيل الدخول',
    'action.postRequest': 'نشر طلب',
    'action.newRequest': 'طلب جديد',
    'action.viewAll': 'عرض الكل',
    'action.viewAllMessages': 'عرض جميع الرسائل',
    'action.compareOffers': 'مقارنة العروض',
    'action.viewPublicProfile': 'عرض الملف الشخصي العام',
    'action.viewPings': 'عرض التطابقات',
    'action.quoteNow': 'اطلب عرض أسعار',
    'action.uploadProof': 'رفع الدليل',
    'action.reply': 'رد',
    'layout.settings': 'الإعدادات',
    'layout.logout': 'تسجيل الخروج',
    'layout.supplierPortal': 'بوابة المورد',
    'layout.companyProfile': 'ملف الشركة',
    'layout.team': 'الفريق',
    'layout.buyerAccount': 'حساب المشتري',
    'layout.myBusiness': 'أعمالي',
    'buyer.nav.dashboard': 'لوحة التحكم',
    'buyer.nav.requests': 'طلباتي',
    'buyer.nav.orders': 'الطلبات',
    'buyer.nav.messages': 'الرسائل',
    'buyer.nav.disputes': 'مركز النزاعات',
    'buyer.nav.wallet': 'المحفظة والضمان',
    'buyer.nav.settings': 'إعدادات الحساب',
    'supplier.nav.dashboard': 'لوحة التحكم',
    'supplier.nav.inbox': 'صندوق البريد',
    'supplier.nav.orders': 'الطلبات والتسليم',
    'supplier.nav.catalog': 'كتالوجي',
    'buyer.dashboard.title': 'لوحة تحكم المشتري',
    'buyer.dashboard.activeRequests': 'الطلبات النشطة',
    'buyer.dashboard.offersReceived': 'العروض المستلمة',
    'buyer.dashboard.ordersProgress': 'الطلبات قيد التنفيذ',
    'buyer.dashboard.escrowHeld': 'محتجز في الضمان',
    'trust.score': 'النقاط',
    'trust.dealRate': 'معدل الصفقات',
    'trust.profile': 'الملف الشخصي',
    'trust.deposit': 'الوديعة',
    'trust.disputes': 'النزاعات',
    'footer.buyers': 'المشترون',
    'footer.suppliers': 'الموردون',
    'footer.settings': 'الإعدادات',
    'footer.postRequest': 'نشر طلب',
    'footer.escrow': 'حماية الضمان',
    'footer.becomeSupplier': 'كن موردًا',
    'footer.pricing': 'الرسوم والأسعار',
    'footer.verification': 'التحقق من المورد',
    'footer.terms': 'الشروط',
    'footer.privacy': 'الخصوصية',
  },
}

export const useAppStore = defineStore('app', {
  state: (): AppState => ({
    language: 'EN',
    currency: 'EUR',
    regionCountry: 'RS',
    enabledLanguageCodes: null,
    routeLocalePrefix: '',
    enabledCurrencies: ['EUR', 'RSD', 'PLN', 'BAM', 'USD'],
    marketLocalizationConfig: null,
    paymentRegionConfig: null,
  }),
  getters: {
    allLanguageOptions: (): SelectOption[] => MARKET_LANGUAGE_OPTIONS,
    languageOptions(state): SelectOption[] {
      if (!state.enabledLanguageCodes?.length) return MARKET_LANGUAGE_OPTIONS
      const enabled = new Set(state.enabledLanguageCodes)
      return MARKET_LANGUAGE_OPTIONS.filter(option => enabled.has(option.code as LanguageCode))
    },
    allCurrencyOptions: (): SelectOption[] => [
      'USD',
      'PHP',
      'EUR',
      'RSD',
      'PLN',
      'BAM',
      'RON',
      'JPY',
      'CNY',
      'SGD',
      'HKD',
      'AUD',
      'GBP',
      'CAD',
      'KRW',
      'AED',
      'INR',
      'THB',
      'USDT',
    ].map((code) => ({ code, label: currencyOptionLabel(code) })),
    regionOptions(state): SelectOption[] {
      const configured = (state.marketLocalizationConfig?.supported_regions || [])
        .map((region: any) => ({
          code: String(region.code || '').toUpperCase(),
          label: String(region.name || region.label || region.code || '').trim(),
        }))
        .filter((region: SelectOption) => region.code && region.label)
      if (configured.length) return configured
      return Object.values(FALLBACK_PAYMENT_POLICIES).map((policy) => ({
        code: policy.country_code,
        label: policy.country_name,
      }))
    },
    paymentPolicy(state) {
      return normalizePaymentPolicy(state.paymentRegionConfig, state.regionCountry)
    },
    currencyOptions(state): SelectOption[] {
      const policy = normalizePaymentPolicy(state.paymentRegionConfig, state.regionCountry)
      const enabled = new Set(
        policy.settlement_currencies?.length
          ? policy.settlement_currencies
          : state.enabledCurrencies?.length
            ? state.enabledCurrencies
            : [policy.default_settlement_currency]
      )
      return this.allCurrencyOptions.filter(option => enabled.has(option.code))
    },
    localCurrency(state): string {
      return normalizePaymentPolicy(state.paymentRegionConfig, state.regionCountry).local_currency
    },
    defaultSettlementCurrency(state): string {
      return normalizePaymentPolicy(state.paymentRegionConfig, state.regionCountry).default_settlement_currency
    },
    t: (state) => (key: string): string => messages[state.language]?.[key] ?? messages.EN?.[key] ?? key,
    prefixForLanguage: () => (lang: string): string => LANGUAGE_TO_URI_LOCALE_PREFIX[normalizeLanguageCode(lang)] || '',
    localizedPath: (state) => (path: string, lang?: string): string => {
      const prefix = lang
        ? LANGUAGE_TO_URI_LOCALE_PREFIX[normalizeLanguageCode(lang)]
        : state.routeLocalePrefix
      return prefix ? withLocalePrefix(path, prefix) : path
    },
  },
  actions: {
    setLanguage(lang: string) {
      const normalized = normalizeLanguageCode(lang)
      if (this.languageOptions.some(option => option.code === normalized)) {
        this.language = normalized as LanguageCode
        const prefix = LANGUAGE_TO_URI_LOCALE_PREFIX[this.language]
        if (prefix) this.routeLocalePrefix = prefix
        this.applyDocumentLocale()
        this.persist()
      }
    },
    setRouteLocalePrefix(prefix: string) {
      this.routeLocalePrefix = String(prefix || '').trim().toLowerCase()
    },
    setCurrency(curr: string) {
      const normalized = normalizeCurrencyCode(curr, this.defaultSettlementCurrency)
      if (this.currencyOptions.some(option => option.code === normalized)) {
        this.currency = normalized
        this.persist()
      }
    },
    async setRegionCountry(country: string) {
      const normalized = String(country || this.regionCountry || 'RS').toUpperCase().slice(0, 2)
      this.regionCountry = normalized
      this.persist()
      await this.fetchPaymentRegionConfig(normalized)
    },
    async fetchPaymentRegionConfig(country = this.regionCountry || 'RS') {
      this.regionCountry = String(country || 'RS').toUpperCase().slice(0, 2)
      try {
        const config = useRuntimeConfig()
        const data = await $fetch<Record<string, any>>(`${config.public.apiBase}/payments/region-config`, {
          query: { country: this.regionCountry },
        })
        const policy = normalizePaymentPolicy(data, this.regionCountry)
        this.paymentRegionConfig = policy
        const enabled = policy.settlement_currencies?.length
          ? policy.settlement_currencies
          : policy.enabled_currencies
        this.enabledCurrencies = enabled
        const defaultSettlement = policy.default_settlement_currency
        if (!enabled.includes(this.currency)) {
          this.currency = enabled.includes(defaultSettlement) ? defaultSettlement : enabled[0]
          this.persist()
        }
      } catch {
        const policy = normalizePaymentPolicy(null, this.regionCountry)
        this.paymentRegionConfig = policy
        this.enabledCurrencies = policy.settlement_currencies || policy.enabled_currencies
        if (!this.enabledCurrencies.includes(this.currency)) {
          this.currency = this.enabledCurrencies.includes(policy.default_settlement_currency)
            ? policy.default_settlement_currency
            : this.enabledCurrencies[0]
        }
        this.persist()
      }
    },
    async fetchMarketLocalizationConfig() {
      try {
        const config = useRuntimeConfig()
        const data = await $fetch<Record<string, any>>(`${config.public.apiBase}/localization/config`)
        this.marketLocalizationConfig = data
        const enabledCodes = Array.isArray(data.supported_locales)
          ? data.supported_locales
            .map((item: any) => normalizeLanguageCode(item.code))
            .filter((code: string) => MARKET_LANGUAGE_OPTIONS.some(option => option.code === code))
          : []
        if (enabledCodes.length) {
          this.enabledLanguageCodes = Array.from(new Set(enabledCodes)) as LanguageCode[]
          if (!this.enabledLanguageCodes.includes(this.language)) this.setLanguage(this.enabledLanguageCodes[0])
        }
      } catch {
        this.enabledLanguageCodes = null
      }
    },
    hydrate() {
      if (!import.meta.client) return
      this.setLanguage(localStorage.getItem('pp_language') || this.language)
      this.regionCountry = String(localStorage.getItem('pp_region_country') || this.regionCountry || 'RS').toUpperCase().slice(0, 2)
      this.setCurrency(localStorage.getItem('pp_currency') || this.currency)
      this.routeLocalePrefix = localStorage.getItem('pp_locale_prefix') || this.routeLocalePrefix
    },
    persist() {
      if (!import.meta.client) return
      localStorage.setItem('pp_language', this.language)
      localStorage.setItem('pp_currency', this.currency)
      localStorage.setItem('pp_region_country', this.regionCountry)
      if (this.routeLocalePrefix) localStorage.setItem('pp_locale_prefix', this.routeLocalePrefix)
      const maxAge = 60 * 60 * 24 * 365
      document.cookie = `pp_language=${encodeURIComponent(this.language)}; Path=/; Max-Age=${maxAge}; SameSite=Lax`
      document.cookie = `pp_currency=${encodeURIComponent(this.currency)}; Path=/; Max-Age=${maxAge}; SameSite=Lax`
      document.cookie = `pp_region_country=${encodeURIComponent(this.regionCountry)}; Path=/; Max-Age=${maxAge}; SameSite=Lax`
    },
    applyDocumentLocale() {
      if (!import.meta.client) return
      const langMap: Record<LanguageCode, string> = {
        EN: 'en',
        ZH: 'zh-CN',
        JA: 'ja',
        ES: 'es',
        TL: 'tl',
        KO: 'ko',
        TH: 'th',
        VI: 'vi',
        ID: 'id',
        AR: 'ar',
        SR: 'sr-Latn-RS',
        BS: 'bs',
        PL: 'pl',
        DE: 'de',
        RO: 'ro',
      }
      document.documentElement.lang = langMap[this.language]
      // RTL support
      document.documentElement.dir = this.language === 'AR' ? 'rtl' : 'ltr'
    }
  }
})
