<template>
  <div>
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-6">
      <div>
        <h1 class="admin-page-title">Integration Events</h1>
        <p class="admin-page-desc">Telegram and workflow events generated by the platform.</p>
      </div>
      <div class="flex gap-2">
        <select v-model="eventTypeFilter" class="input-field max-w-52" @change="loadEvents">
          <option value="">All event types</option>
          <option value="lead.created">lead.created</option>
          <option value="vendor.applied">vendor.applied</option>
          <option value="product.submitted">product.submitted</option>
          <option value="ai.completed">ai.completed</option>
        </select>
        <select v-model="statusFilter" class="input-field max-w-44" @change="loadEvents">
          <option value="">All statuses</option>
          <option value="pending">Pending</option>
          <option value="sent">Sent</option>
          <option value="skipped">Skipped</option>
          <option value="failed">Failed</option>
        </select>
      </div>
    </div>

    <div class="admin-panel">
      <table class="admin-table w-full text-sm">
        <thead>
          <tr>
            <th class="text-left px-4 py-3 font-medium text-gray-500">Event</th>
            <th class="text-left px-4 py-3 font-medium text-gray-500">Target</th>
            <th class="text-left px-4 py-3 font-medium text-gray-500">Status</th>
            <th class="text-left px-4 py-3 font-medium text-gray-500">Payload</th>
            <th class="text-left px-4 py-3 font-medium text-gray-500">Created</th>
            <th class="text-right px-4 py-3 font-medium text-gray-500">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="event in events" :key="event.id" class="border-b align-top">
            <td class="px-4 py-3">
              <p class="font-medium text-gray-900">{{ event.event_type }}</p>
              <p class="text-xs text-gray-500 font-mono">{{ event.id.slice(0, 8) }}</p>
            </td>
            <td class="px-4 py-3 text-gray-600">{{ event.target_channel || '-' }}</td>
            <td class="px-4 py-3">
              <StatusBadge :status="event.status" />
              <p v-if="event.retry_count" class="text-xs text-gray-500 mt-1">Retries: {{ event.retry_count }}</p>
            </td>
            <td class="px-4 py-3 max-w-md">
              <p class="text-xs text-gray-700 line-clamp-3">{{ summarizePayload(event.payload_json) }}</p>
              <p v-if="event.error_message" class="text-xs text-amber-700 mt-1">{{ event.error_message }}</p>
            </td>
            <td class="px-4 py-3 text-gray-500 whitespace-nowrap">
              {{ new Date(event.created_at).toLocaleString() }}
            </td>
            <td class="px-4 py-3 text-right">
              <button
                v-if="event.status === 'failed'"
                class="px-3 py-1.5 text-xs font-medium rounded-lg bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-60"
                :disabled="retryingId === event.id"
                @click="retryEvent(event.id)"
              >
                {{ retryingId === event.id ? 'Retrying...' : 'Retry' }}
              </button>
            </td>
          </tr>
          <tr v-if="!events.length">
            <td colspan="6" class="px-4 py-8 text-center text-gray-500">No integration events yet.</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'default' })

const { apiFetch } = useApi()
const events = ref<any[]>([])
const statusFilter = ref('')
const eventTypeFilter = ref('')
const retryingId = ref('')

function summarizePayload(payload: any) {
  if (!payload) return '-'
  const parts = [
    payload.lead_id ? `lead=${payload.lead_id.slice(0, 8)}` : '',
    payload.vendor_id ? `vendor=${payload.vendor_id.slice(0, 8)}` : '',
    payload.product_id ? `product=${payload.product_id.slice(0, 8)}` : '',
    payload.contact_name || payload.company_name || payload.name || payload.classification || '',
    payload.country || '',
    payload.budget_range || '',
  ].filter(Boolean)
  return parts.length ? parts.join(' | ') : JSON.stringify(payload)
}

async function loadEvents() {
  const params = new URLSearchParams()
  if (statusFilter.value) params.set('status', statusFilter.value)
  if (eventTypeFilter.value) params.set('event_type', eventTypeFilter.value)
  const query = params.toString() ? `?${params.toString()}` : ''
  try {
    const res = await apiFetch<any>(`/integration-events${query}`)
    events.value = res.items || []
  } catch (e) {
    events.value = []
  }
}

async function retryEvent(id: string) {
  retryingId.value = id
  try {
    await apiFetch(`/integration-events/${id}/retry`, { method: 'POST' })
    await loadEvents()
  } finally {
    retryingId.value = ''
  }
}

onMounted(loadEvents)
</script>
